### ISSUE TITLE
Integrate post-stats into the theme

### ISSUE THREAD

**Issue by silverhook** [Pelican-Elegant/elegant#100]
I find the right sidebar very nicely done, but would suggest adding the support for information from the _post-stats_ plugin. A readability indexes and how much time one needs to read the article would be nice.

If no-one else has interest in this, I'd be happy to tackle it myself to learn about the theme.

We could also use that plugin to generate word-clouds, but I don't have that ambition.

**Comment by talha131** [comment]
Added in dfcdf5dcb9
