### ISSUE TITLE
Make the rendered code W3C compliant

### ISSUE THREAD

**Issue by silverhook** [Pelican-Elegant/elegant#103]
Because staying compliant is just a generally good idea to do.

Currently [W3C's Unicorn checker](http://validator.w3.org/unicorn/) produces:
- ~10 HTML errors,
- ~700 CSS errors,
- and two feed errors (which probably has nothing to do with the theme).

I'll try to help here.

**Comment by silverhook** [comment]
Right now, the running the [W3C validator on our website/documentation](http://validator.w3.org/unicorn/check?ucn_uri=https%3A%2F%2Fpelican-elegant.github.io%2F&ucn_task=conformance#) produces:

- 1 HTML error
- 1 CSS error
- 801 CSS warnings
- 20 HTML “infos”
- 1 feed “info”

So on the HTML side there is great progress already, but after we get rid of Bootstrap in [Elegant 3.0](https://github.com/Pelican-Elegant/elegant/milestone/4), we should revisit this.

**Comment by talha131** [comment]
@iranzo can we have W3C validation automated? I think documentations site would be more apt for it. We can also have it for test pages you added in this repository.

**Comment by iranzo** [comment]
How do you check it ?

**Comment by talha131** [comment]
@iranzo using tools like

1. https://pypi.org/project/Online-W3C-Validator/
1. https://www.npmjs.com/package/html-validator

**Comment by iranzo** [comment]
The PR 243 executes online-w3c on the generated output code, output needs to be examined to check for errors
