### ISSUE TITLE
Add Flattr support

### ISSUE THREAD

**Issue by silverhook** [Pelican-Elegant/elegant#104]
[Flattr](https://flattr.com) is a pretty cool system for awarding creations (e.g. blog posts) with micropayments.

It'd be great to have.

This can be done by simply adding some snippet to the theme, but would it make more sense to write it as a separate plugin and connect it into the theme in an `if` statement?

**Comment by silverhook** [comment]
Can we finally merge that? That’d be so super :3

**Comment by silverhook** [comment]
I did some small research and found out that some other Pelican theme already implemented Flattr 2.0 support. It’s super-easy.

All we would need to is to add a `<meta>` tag (in an `if` statement) – see e.g. https://github.com/Kdecherf/Nicholas/commit/3d3c6c9698cf76494f801d378d8f1e107452e574

Reopening as this is an easy thing to work on.

**Comment by silverhook** [comment]
Personally, I lost interest in Flattr. Since I seem to be the only one who was interested in it for at 4 years, I will close this issue.

If anyone else finds interest in it, feel free to (ask me to) re-open it or create a new issue.

**Comment by iranzo** [comment]
TBH, I haven't seen this issue as interesting as didn't knew about Flattr, seems that as it's easy to do as per previous comments could be good.

I did heard in the past about other things like patron or even the 'ransom' style webs for github issues like
https://www.bountysource.com/ but never tried tbh.

**Comment by silverhook** [comment]
@iranzo, if it scratches your interest, happy to reopen it. It should be rather easy to implement.

**Comment by iranzo** [comment]
https://techcrunch.com/2019/05/23/github-launches-sponsors-lets-you-pay-your-favorite-open-source-contributors/

Another one has come :-)

**Comment by silverhook** [comment]
@iranzo, I haven’t checked the GitHub one yet, but suspect it is limited to things on GitHub. Questionable if it’s only about code.

If there’s interest, I can check it.
