### ISSUE TITLE
when the the code style include ">" symbol ,the page does not show right

### ISSUE THREAD

**Issue by 7rack** [Pelican-Elegant/elegant#118]
i love the elegant theme.when i use markdown syntax to highlight the following code
```c
# include "highgui.h"
# include "cv.h"
# include <stdio.h>

int main(int arg,char*\* argv)
{
...
    int height = src->height ;
    int width = src->width ;
    int step = src->widthStep ;
    int channels = src->nChannels ; 
}
```
the page looks like strange.you can find it on  my [blog](http://7rack.info/simple-example-of-opencv.html) .

**Comment by talha131** [comment]
@all-contributors please add @7rack for bug.
