### ISSUE TITLE
Why is output rendered locally on Firefox different from the one hosted online?

### ISSUE THREAD

**Issue by talha131** [Pelican-Elegant/elegant#121]
@calfzhou @tshepang @silverhook

I have noticed when the localhost output on Firefox is visibly different from the hosted version.

Here is the local version

![screen shot 2014-06-01 at 9 32 25 pm](https://cloud.githubusercontent.com/assets/1094724/3142102/5a2af552-e9aa-11e3-944e-0e8763fc0c05.png)

Here is the hosted version

![screen shot 2014-06-01 at 9 44 49 pm](https://cloud.githubusercontent.com/assets/1094724/3142126/2629ab02-e9ac-11e3-86da-7975617c8500.png)

Please see the enlarged version of both screenshots. You will notice width of the top menu bar is noticeably less than the width in the hosted version.

I am using Firefox 29.0.1 on Max OSX 10.9.3. To view localhost version I run `make devserver` and open http://localhost:8000/ URL in my browser.

I cannot reproduce the issue on Chrome and Safari.

Can you guys please try to reproduce this issue on your end? Any idea what is going on here?

**Comment by silverhook** [comment]
@talha131 Does this still happen to you?

**Comment by talha131** [comment]
Will look and report back.

**Comment by talha131** [comment]
I cannot reproduce the issue anymore.
