### ISSUE TITLE
a bug when embeding GitHub Gist

### ISSUE THREAD

**Issue by seisman** [Pelican-Elegant/elegant#123]
I am trying to embed GitHub Gist into rST files, below is the simplest example :

```
Test for Gist
#############                                                                       

.. raw:: html                                                                       

   <script src="https://gist.github.com/seisman/25337aa9df50fb6ec6c3.js"></script>
```

What I want to see looks like this:

![gist0](https://cloud.githubusercontent.com/assets/3974108/3468644/7097f528-02a1-11e4-8fc4-c2e209560a80.jpg)

But the actual result looks like this:
![gist](https://cloud.githubusercontent.com/assets/3974108/3468566/40701f20-02a0-11e4-8d8a-7711e0536653.jpg)

It seems to be caused by the definition of  table-layout property  in `elegant.css`, so I comment out the table-layout property and it works fine now.

```
/* Syntax Highlight */                                                           
table {
//    table-layout: fixed;
      width: 100%;
}
```

I don not know much about CSS, so I am not sure whether this modification have possible side-effects or not.

**Comment by silverhook** [comment]
Is this still an issue with the latest code?

If so, I think it would make sense to implement @Schnouki’s fix and document it.

**Comment by talha131** [comment]
@all-contributors please add @seisman for bug

**Comment by talha131** [comment]
@all-contributors please add @Schnouki for code

**Comment by talha131** [comment]
04164335e5
