### ISSUE TITLE
Mixed content warnings abound

### ISSUE THREAD

**Issue by mlissner** [Pelican-Elegant/elegant#129]
I haven't dug into this too much yet, but it looks like two different spots in the code use the `http` protocol rather than being protocol agnostic. 

The first is in the `<head>` tag:

```
<link href="http://cdn-images.mailchimp.com/embedcode/slim-081711.css" rel="stylesheet" type="text/css">
```

And the second appears to be in the footer scripts:

```
<script src="http://code.jquery.com/jquery.min.js"></script>
```

Would a pull request be welcomed that did the following:
1. Made a check for the mailchimp variables and only included the first link if they existed; and
2. Changed the second link to make it protocol agnostic

These changes are very important, as without them I am getting mixed content warnings in the browser when I view my pages with HTTPS enabled.

**Comment by silverhook** [comment]
The progress looks good, but I still get mixed content warnings and some of the styling seems to get lost if I use HTTPS (regardless of your patch).

I’m intersted in fixing this as well.

**Comment by talha131** [comment]
Close via https://github.com/Pelican-Elegant/elegant/pull/200
