### ISSUE TITLE
support chinese and could change markdown engine

### ISSUE THREAD

**Issue by xubin0523** [Pelican-Elegant/elegant#134]
Can you make elegent more friendly to chinese language and  could changing markdown engine (I don't like python style)? It looks not perfect to my blog[http://xubin0523.github.io/bits.html]

**Comment by silverhook** [comment]
@xubin0523, does this still happen with latest version?

@calfzhou, can you help here?

**Comment by talha131** [comment]
We can't change Markdown engine. Pelican handles Markdown for us.

If typography is the only issue then we can solve it by adding an article in the documentation.

**Comment by silverhook** [comment]
If it only means to add a font that should not be too hard to do.

**Comment by talha131** [comment]
I can think of two ways to solve this issue

## Using CSS

Tell CSS to use specific fonts for a language. For example special fonts for Chinese or Urdu

But does it mean we will have to ship theme with fonts? How will it affect the size of page that does not use a font?

## Provide CSS configuration

We already have custom CSS. But can we have a file like pelicanconf but for Eelegant CSS.

This file will resize in the root of the blog source code. It will have variables like `BODY_FONT` and then elegant will pick up this variable and use it in its CSS files.

I am not sure if it is even possible.

## Existing solution

1. Use custom.css
1. Add article in docs to tell user to use so and so fonts for so and so languages
   (Can user embed his own fonts easily?)

**Comment by talha131** [comment]
2711aa0f02
