### ISSUE TITLE
Support for Series plugin (which deprecated multi_part)

### ISSUE THREAD

**Issue by silverhook** [Pelican-Elegant/elegant#138]
I just noticed that the `multi_part` plugin is being deprecated by the [`series` plugin](https://github.com/getpelican/pelican-plugins/tree/master/series):

> This plugin has been deprecated. See the series plugin for a better support of multi part articles.

Since we just implemented `multi_part` in bug https://github.com/talha131/pelican-elegant/issues/95 , I guess it is easer now to just port that to `series` Right?.

**Comment by silverhook** [comment]
I have to admit, I haven’t had time to go through all the pull requests – do we actually have one for the series plugin?

**Comment by iranzo** [comment]
https://github.com/Pelican-Elegant/elegant/pull/155 afaik does

**Comment by silverhook** [comment]
Ah, neat. :smile: 

No, other than someone reviewing #155, I don’t see anything blocking it.
