### ISSUE TITLE
Footnotes and references are not shown correctly

### ISSUE THREAD

**Issue by fladd** [Pelican-Elegant/elegant#143]
When using footnotes or references i restructuredText, with [1]_ and [SOMEREF]_, then three wrong things happen:

1) In case of the footnote, the footnote reference in the text is not in superscript

2) In both cases, there is no visual separation from the footnotes and the rest of the text (by a horizontal line for instance)

3) In both cases, the formatting of the footnote contents are very strange. It seems to be presented in a table with two columns. Left is the footnote number or reference in grey, and on the right is the content. In between there is a huge space, which makes it very difficult to read, especially when more footnotes/references are present, it is very difficult to see which number/reference belongs to which text.

**Comment by talha131** [comment]
@fladd thank your reporting this issue and #144 . During development, I tested Elegant on Markdown almost exclusively. No wonder its not scaling to reST smoothly. reST has more markups that Markdown, style for each of which must be defined explicitly. 

I am working on [Elegant 3](https://github.com/talha131/pelican-elegant/tree/upgrade-bootstrap-agnostically), I will swat these issues in this version.

Is it possible for you to share your reST markup-ed article file here, so that I can use it for testing?

**Comment by fladd** [comment]
@talha131 Good to hear that you are working on it. I am certainly looking forward to the new version!

I was actually using the official demo.rst document from docutils itself. The only thing I did was to remove the intended errors they put in there for showcasing.

Please find this document here: http://stuff.fadd.de/demo.rst. It contains most, if not all, what is possible with ReST and should not produce any errors.

Here is how it renders in Elegant 2: http://stuff.fladd.de/pelican/restructuredtext-demonstration.html

As you can see, there are actually a couple of other things that are not properly styled in Elegant. Amongst them are sidebars, rubrics, topics and admonitions.

**Comment by talha131** [comment]
Thank you @fladd. I will look into it.

Note to self: reST document is at http://stuff.fladd.de/demo.rst

**Comment by talha131** [comment]
There is not much we can do here. Pelican uses docutil for reST support. The html it generates is not compatible for footnotes.

I just tried this content

```rest
Footnote references, like [5]_.
Note that footnotes may get
rearranged, e.g., to the bottom of
the "page".


.. [5] A numerical footnote. Note
   there's no colon after the ``]``. 
```

The html I got was

```html
  <p>Footnote references, like <a class="footnote-reference" href="#id2" id="id1">[5]</a>.
Note that footnotes may get
rearranged, e.g., to the bottom of
the&nbsp;“page”.</p>
<table class="docutils footnote" frame="void" id="id2" rules="none">
<colgroup><col class="label"><col></colgroup>
<tbody valign="top">
<tr><td class="label"><a class="fn-backref" href="#id1">[5]</a></td><td>A numerical footnote. Note
there’s no colon after the <tt class="docutils literal">]</tt>.</td></tr>
</tbody>
</table>
```

Obvious issues are

1. footnote is not enclosed in `sup` tag
1. No `hr` before footnotes sections
1. using tables for footnotes

Surprisingly, if you see the html of [official example](http://docutils.sourceforge.net/docs/user/rst/quickref.html#footnotes), it is very different from what Pelican has generated.

Therefore, this issue should be raised with Pelican developers. Elegant is not responsible for this bug.
