### ISSUE TITLE
Integrate HTML and CSS validator tags

### ISSUE THREAD

**Issue by silverhook** [Pelican-Elegant/elegant#152]
IMHO having valid HTML and CSS is important and I always try comply with it.

It’d be great if (maybe once we get compliant) we could have two small tags to notify the visitor (so 2000’s, I know!) that the website is HTML5 and CSS3 valid. Ideally with a link to the W3C validator.

The official W3C tags are just too chunky and ugly, but I think the Font Awesome variants of [HTML5](https://fortawesome.github.io/Font-Awesome/icon/html5/) and [CSS3](https://fortawesome.github.io/Font-Awesome/icon/css3/) e.g. in the footer would be more then enough. And these icons are already extensively used by Elegant, so they wouldn’t strike out too much.

**Comment by silverhook** [comment]
I added the following code to the footer template:
<li class="elegant-w3c"><a href="//validator.w3.org/check?uri=referer"><i class="fa fa-html5"></i></a><a href="//jigsaw.w3.org/css-validator/validator?uri={{ SITEURL }}"><i class="fa fa-css3"></i></a></li>

A down side is that for some reason, now my blog generates 2-4 times as slow as before.

**Comment by silverhook** [comment]
The slower generation seems to have been caused by the system at that time being busy with other processes. In the past days the generator seems to work fine.

**Comment by iranzo** [comment]
Probably having a setting to show/hide this based on value? like
BACK_TO_THE_FUTURE=False ;-)

**Comment by silverhook** [comment]
I’m still of the strong opinion that a website must pass W3C tests, but am OK making the validator tags show as an option – e.g. `W3C_VALIDATOR_LINK=False`

**Comment by iranzo** [comment]
Years ago, I even tried to have them 'bobby' compliant: <https://en.wikipedia.org/wiki/Bobby_(software)>

In general, anything that ensures standard compliance plus accessibility compliance should be really good to have

**Comment by talha131** [comment]
We have it in travis.
