### ISSUE TITLE
base.html is hardcoded to english

### ISSUE THREAD

**Issue by solbu** [Pelican-Elegant/elegant#156]
Hi.
I was trying to validate a new site for our team, and is trying elegant as one of the posible themes to use.

We where checking it against w3c.org's validator, and discovered that the template is hardcoding the content as being english. We write in norwegian, and the validator detected this, and reported it as an error that the content language is different that the claimed language tag.

The base.html currently have: `<html lang="en">`
The correct way is: `<html lang="{{ DEFAULT_LANG }}">`

This way it will populate the claimed language by the configuration file 
variable `DEFAULT_LANG = u'XX'`.
In our case this will result in the generated html to have the code showing as `<html lang="no">`

**Comment by solbu** [comment]
I see it is fixed in Pull Request  #168

**Comment by talha131** [comment]
Close via ecc8f0e81b1c96b6025203aa088f7ded36623edc
