### ISSUE TITLE
Bug: disqus_scripts grabs the first accordion element, not necessarily the correct one

### ISSUE THREAD

**Issue by leotrs** [Pelican-Elegant/elegant#157]
On line 27 [here](https://github.com/talha131/pelican-elegant/blob/master/templates/_includes/disqus_scripts.html#L27), the script grabs all elements of class 'accordion-toggle' and then proceeds to modify the first one of them. 

If there are more accordions than the one from the comment section, this will modify the wrong one.

**Comment by leotrs** [comment]
@talha131 submitted PR.

**Comment by iranzo** [comment]
@leotrs with the merge of the PR for protocol, is this still an issue? You can check on the rendered website at http://pelican-elegant.github.io to validate

**Comment by talha131** [comment]
Close via 484b0ee1b97e568393fedf21f33ed51817341f01
