### ISSUE TITLE
Theme not compatible with Jinja2 version 2.9

### ISSUE THREAD

**Issue by cszhe** [Pelican-Elegant/elegant#162]
The following code in archives.html does not work with 2.9

`<div class="blog-archives">
            {% set last_year = 0 %}
            {% for article in dates %}
            {% set year = article.date.strftime('%Y') %}
            {%if last_year != year %}
            <h2 id="{{year }}"><a href="#{{year}}">{{ year }}</a></h2>
            {% set last_year = year %}
            {% endif %}
            {% set next_year = 0 %}
            {% if not loop.last %}
            {% set next = loop.index0 + 1 %}
            {% set next_article = dates[next] %}
            {% set next_year = next_article.date.strftime('%Y') %}
            {% endif %}
            {% if next_year != year %}
            <article class="last-entry-of-year">
            {% else %}
            <article>
            {% endif %}
            <a href="{{ SITEURL }}/{{ article.url }}">{{ article.title }} {%if article.subtitle %} <small> {{ article.subtitle }} </small> {% endif %} </a>
            <time pubdate="pubdate" datetime="{{ article.date.isoformat() }}">{{ article.locale_date }}</time>
            </article>
            {% endfor %}
        </div>`

Please refer to: 
https://github.com/pallets/jinja/issues/641

**Comment by silverhook** [comment]
I think @talha131 is planning more to re-write this theme in a new repo:
https://github.com/talha131/uncss-pelican-elegant

This might explain and excuse his relative quietness in this repo.

**Comment by talha131** [comment]
Closing it in favor of https://github.com/Pelican-Elegant/elegant/issues/202

**Comment by talha131** [comment]
Thanks a lot @cszhe. Without your pointer, I would not have been able to fix this bug at all.

In case you didn't know, there has been a change in project management. Please see #173 for detail. 

In this regard, it would be great to have technical person like you on board. Kindly ping us via Github issues, if you can manage even a little bit time for this project. Every little contribution counts.

**Comment by talha131** [comment]
@all-contributors please add @cszhe for bug
