### ISSUE TITLE
bugfix:HTTPS support problem

### ISSUE THREAD

**Issue by pythonwood** [Pelican-Elegant/elegant#166]
Thank you for a good theme.

As you can see,   I deployed it on my vps server https://blog.pythonwood.com/. but js file 'http://code.jquery.com/jquery.min.js' request has been blocked. the content must be served over HTTPS.

![screenshot - 2017 11 20 - 10 24 12](https://user-images.githubusercontent.com/5157880/32999433-14ec4ae8-cddd-11e7-9b30-aeb682dcbfa5.png)

I know to fix and try to fix it and make a pull request. (^_^)
"http://" => "//"

**Comment by silverhook** [comment]
Dear @pythonwood, there is already a fix/PR here: https://github.com/talha131/pelican-elegant/pull/153

Unfortunately, @talha131 doesn’t have time to actively maintain this theme any (see [here for more info](https://github.com/talha131/pelican-elegant/pull/77#issuecomment-169541444)). He already [started an effort to port Elegant to UnCSS](https://github.com/talha131/uncss-pelican-elegant), but that hasn’t seen an update for over a year now either.

**Comment by fangying** [comment]
@pythonwood Thanks for your patch, I can now use elegant smoothly with https support. Disqus now works fine with my blog.

**Comment by pythonwood** [comment]
@fangying worth to do it  :-)

**Comment by silverhook** [comment]
It’s not merged yet. If memory serves me right, there are pull requests to handle this a) in a way to force HTTPS explicitly, or b) in a protocol-agnostic manner (e.g. with just `//`).

I think it’s worth having a vote on how to tackle this and then work on the right pull request.

**Comment by iranzo** [comment]
probably // is better as it would serve both use cases

**Comment by silverhook** [comment]
Proposal 1: **Force HTTPS everywhere**

pro:

- encryption by default

con:

- we would need to check for all URLs if they actually have a HTTPS version

**Comment by silverhook** [comment]
Proposal 2: **Protocol-agnostic solution**

We could change all references to `http://` and `https://` to simply `//`

pro:

- more likely to work out of the box

con:

- not 100% sure you will get https all the time

**Comment by talha131** [comment]
> not 100% sure you will get https all the time

I don't think it should be the job of a theme to ensure user "gets https all the time". It's just a presentation layer.

**Comment by iranzo** [comment]
Theme shouldn't enforce protocol so "//" should be the more 'agnostic' way to have a theme independent way

**Comment by silverhook** [comment]
@pythonwood, it seems you don’t use Elegant on your blog right now. Can you at least indicate whether you have interest in pushing this pull request forward still regardless?

Some relevant info: Elegant has grown now from a single-maintainer to a community-led project, so we’re picking up speed at an astounding pace (see #173 for more info). It might be the perfect time to join in, if Elegant is still on your radar ;)

**Comment by pythonwood** [comment]
> @pythonwood, it seems you don’t use Elegant on your blog right now. Can you at least indicate whether you have interest in pushing this pull request forward still regardless?
> 
> Some relevant info: Elegant has grown now from a single-maintainer to a community-led project, so we’re picking up speed at an astounding pace (see #173 for more info). It might be the perfect time to join in, if Elegant is still on your radar ;)

@silverhook right, and thanks to everybody at anyway. ( close now )

**Comment by iranzo** [comment]
@silverhook can we leave this open again and reassign so that we put another PR to remove all protocol references?

**Comment by silverhook** [comment]
Yeah, I think we can simply reopen this bug and use it to track the protocol-reference.

Anyone wanting to pick it up, please self-assign (or if you can’t let me know).

**Comment by pythonwood** [comment]
@silverhook   @iranzo  ok, it is good to keep it open.
