### ISSUE TITLE
Check for compatibility with Pelican 4.0

### ISSUE THREAD

**Issue by silverhook** [Pelican-Elegant/elegant#174]
Pelican 4.0 was released this month:

https://blog.getpelican.com/pelican-4.0-released.html

We should test if the theme still works as expected and what would be good changes to have in line with the the changes of the new major release of Pelican.

**Comment by ashwinvis** [comment]
The best (and definitely not the fastest) way to do that will be setup a continuous deployment to github pages on Travis, something like what I use here https://github.com/ashwinvis/ashwinvis.github.io/blob/develop/.travis.yml

**Comment by silverhook** [comment]
Super sweet idea!

@ashwinvis, would you be willing to tackle this? It’s *far* from urgent, but eventually we should set up things, so we scale well.

**Comment by silverhook** [comment]
@ashwinvis, do you think https://github.com/Pelican-Elegant/documentation/issues/1 would be a good test-case? Killing two birds with one stone, so to say.

**Comment by iranzo** [comment]
https://blog.getpelican.com/category/news.html

It breaks at least with my rss feed

**Comment by iranzo** [comment]
~~~
-> Writing /home/iranzo/DEVEL/private/www/output/feeds/all.atom.xml
-> Writing /home/iranzo/DEVEL/private/www/output/feeds/all.rss
CRITICAL: TypeError: not all arguments converted during string formatting
Traceback (most recent call last):
  File "/usr/bin/pelican", line 11, in <module>
    load_entry_point('pelican==3.7.1', 'console_scripts', 'pelican')()
  File "/usr/lib/python3.7/site-packages/pelican/__init__.py", line 487, in main
    pelican.run()
  File "/usr/lib/python3.7/site-packages/pelican/__init__.py", line 179, in run
    p.generate_output(writer)
  File "/usr/lib/python3.7/site-packages/pelican/generators.py", line 599, in generate_output
    self.generate_feeds(writer)
  File "/usr/lib/python3.7/site-packages/pelican/generators.py", line 312, in generate_feeds
    % cat.slug, feed_title=cat.name)
TypeError: not all arguments converted during string formatting
~~~

**Comment by ashwinvis** [comment]
A [patch like this](https://github.com/ashwinvis/pelican-elegant/commit/c8bf9c9a9dcfc7fb7fe0c1f7fbefcb4cc6b904d4) is needed if RSS/atom feeds are enabled (something which has been overlooked in the tests and documentation, I think). Without it, it would raise a TypeError, however even with the patch and `publishconf.py` containing

```python
...
FEED_ALL_ATOM = 'feeds/all.atom.xml'
CATEGORY_FEED_ATOM = 'feeds/{slug}.atom.xml'
...
```

`categories.html` rendering is not correct

```diff
-        <link href="https://fluiddyn.bitbucket.io/feeds/articles.atom.xml" type="application/atom+xml" rel="alternate" title="FluidDyn blog - Articles Category Atom Feed" />
-        <link href="https://fluiddyn.bitbucket.io/feeds/news.atom.xml" type="application/atom+xml" rel="alternate" title="FluidDyn blog - News Category Atom Feed" />
+        <link href="https://fluiddyn.bitbucket.io/feeds/{slug}.atom.xml" type="application/atom+xml" rel="alternate" title="FluidDyn blog - Articles Category Atom Feed" />
+        <link href="https://fluiddyn.bitbucket.io/feeds/{slug}.atom.xml" type="application/atom+xml" rel="alternate" title="FluidDyn blog - News Category Atom Feed" />
 ```

**Comment by talha131** [comment]
@ashwinvis Would you care to open a PR for this?

**Comment by iranzo** [comment]
@talha131 we do have it in 'next' branch as per https://github.com/Pelican-Elegant/elegant/commit/b2397e8f9d2095952f98bcd83685ef33ec6e43fd

**Comment by iranzo** [comment]
We should probably try to have it released and start implementing it in 4.0 for 'master'

**Comment by ashwinvis** [comment]
I wasn't aware of the 'dev-*' branches. Can someone add a note on what the 'next' branch is all about in https://github.com/Pelican-Elegant/elegant/blob/master/CONTRIBUTING.md ?

**Comment by iranzo** [comment]
Next is used to showcase whatever is coming in next release and we use it
to render the demo website (documentation in the /next ) without being
limited to actual compatibility

Regards

**Comment by talha131** [comment]
Thank you @iranzo.

@ashwinvis Have a look at the [updated guideline](https://github.com/Pelican-Elegant/elegant/blob/master/CONTRIBUTING.md#contributing-code).

We have this confusion about `master` vs `next` branch, until we get 2.0 out of the door. After it all development will be done in `next` branch.

**Comment by iranzo** [comment]
I'm deploying my site with Pelican 4 and only issue so far is the one that we've fixed in next, has anyone done more tests?

**Comment by ashwinvis** [comment]
So the bug I mentioned is reproduced here:

https://travis-ci.org/Pelican-Elegant/elegant/jobs/474031399#L806

**Comment by iranzo** [comment]
That's failure for the w3c validator, not pelican execution (both tests succeed) :

- https://travis-ci.org/Pelican-Elegant/elegant/jobs/474031399#L768
- https://travis-ci.org/Pelican-Elegant/elegant/jobs/474031399#L1121

What do you suggest for fixing it? setting the slugs/uris?

**Comment by ashwinvis** [comment]
I don't know :) Beats me.

**Comment by iranzo** [comment]
I think we're only missing the commit for slug generation and pelican 4 for this release to happen.

I was also working on this project: https://github.com/iranzo/blog-o-matic/ that could ease this part and have other users to update to newer pelican version (either virtualenv, etc)
