### ISSUE TITLE
Adopt a Code of Conduct

### ISSUE THREAD

**Issue by silverhook** [Pelican-Elegant/elegant#176]
As indicated in https://github.com/talha131/pelican-elegant/issues/173#issuecomment-440668456 Pelican Elegant is missing a Code of Conduct.

While, personally, I don’t necessarily think we need one, if it was already requested, it would make sense to adopt one.

So to kick off the debate, I would propose something simple and battle-tested, as the [IEEE Code of Ethics][ieee_coc] – or rather, [The Commons Conservancy’s¹ take on it][tcc_coc]:

> # Introduction
> 
> As a professional organisation and as an open community our guiding principles are respect for the individual, the right to self-determination, the right to make informed decisions and the spirit of cooperation. We aim to be a safe and inclusive environment, fostering a rich diversity of human talent. The Code of Conduct is a codification of the ethical and professional behaviour expected of those engaging with our activities. 
> 
> The Code of Conduct is based (mutatis mutandis) on the 2016 version of the `IEEE Code of Ethics`_, as established by the Institute of Electrical and Electronics Engineers through its Ethics and Member Conduct Committee. Maintaining the Code of Conduct is the responsibility of the Board of [The Commons Conservancy], but the demand, ambition and knowledge to do the very best we can is shared throughout our community. Anyone is therefore encouraged to contribute suggestions how to improve the Code of Conduct.
> 
> # Code of Conduct
> 
> We expect the following behaviour to be the norm within [The Commons Conservancy], and thus commit ourselves:
> 
> 1) to accept responsibility in making decisions consistent with the safety, health, and welfare of the public, and to disclose promptly factors that might endanger the public or the environment;
> 2) to avoid real or perceived conflicts of interest whenever possible, and to disclose them to affected parties when they do exist;
> 3) to be honest and realistic in stating claims or estimates based on available data;
> 4) to reject bribery in all its forms;
> 5) to improve the understanding of technology; its appropriate application, and potential consequences;
> 6) to maintain and improve personal and collective technical competence and to undertake technological tasks for others only if qualified by training or experience, or after full disclosure of pertinent limitations;
> 7) to seek, accept, and offer honest criticism of technical work, to acknowledge and correct errors, and to credit properly the contributions of others;
> 8) to treat fairly all persons and to not engage in acts of discrimination based on race, religion, gender, disability, age, national origin, sexual orientation, gender identity, or gender expression;
> 9) to avoid injuring others, their property, reputation, or employment by false or malicious action;
> 10) to assist others in their professional development and to support them in following this code of ethics.
> 
> # References
> 
> [IEEE Code of Ethics](http://www.ieee.org/about/corporate/governance/p7-8.htm)
> 

Clearly this is just a suggestion and if someone else has a different suggestion, we should discuss which one seems a better match for us.

As opposed to the license clarification in #175, I think we can take our time with adopting a CoC, for three reasons:

- #175 is just to clarify the project’s license, not change it. This bug is about adopting new rules, which we didn’t have before.
- A CoC is one of the most sensitive (and sometimes disputed) governance documents of a project, so we should really make sure we’re all comfortable with it and that it would foster a vibrant community (instead of stifling it).
- Not having a clear CoC does not prevent us from moving forward at this early stage, so we can take some time to discuss it still.

---

1: Note, I was involved with The Commons Conservancy when it was started and am a co-author of their governance documents. I am not employed, part of their board or anything similar though.

[ieee_coc]: https://www.ieee.org/about/corporate/governance/p7-8.html
[tcc_coc]: https://dracc.commonsconservancy.org/0015/

**Comment by silverhook** [comment]
This is another popular option, but I haven’t read it thoroughly yet:

https://www.contributor-covenant.org/

**Comment by talha131** [comment]
> While, personally, I don’t necessarily think we need one

We don't need one. We have been doing well before and since this issue was first opened.
