### ISSUE TITLE
Update the pointer in getpelican/pelican-themes

### ISSUE THREAD

**Issue by silverhook** [Pelican-Elegant/elegant#177]
The official [pelican-themes][] repository currently still points to Talha’s repository. I suspect that the redirection works, but once we are are sure the name of the organisation and repository is decided upon, we should update the link.

- [x] decide we’re cool with our org/repo name ↦ #179 
- [x] open a bug in [pelican-themes][] to change the pointer to the new repository
- [ ] https://github.com/getpelican/pelican-themes/issues/623 gets resolved

[pelican-themes]: https://github.com/getpelican/pelican-themes

**Comment by talha131** [comment]
Close via https://github.com/getpelican/pelican-themes/commit/5b810b8835d1bd742b5c814a160742ee8af6e358#diff-8903239df476d7401cf9e76af0252622
