### ISSUE TITLE
Basic governance for the project

### ISSUE THREAD

**Issue by silverhook** [Pelican-Elegant/elegant#180]
As discussed in #173, we should at least agree on some basic rules how we want to govern Elegant, before pushing forward willy-nilly.

Here is my suggestion:

# Development style

I suggest that for now we stick to the already existing rules and conventions as they stand in [`CONTRIBUTING.md`](https://github.com/Pelican-Elegant/pelican-elegant/blob/master/CONTRIBUTING.md). For any changes, let’s open an issue and discuss/vote on it (see below).

# Governance

## Contributing code

I would suggest that we make it a rule that all code should go through the following steps:

1. create a pull request
2. get someone (other than you) to review your code
3. after code reviewer approves it, it can get merged

At this stage, I don’t think we need special permissions for code review – any active member may review the code. Also, I think for the sake of simplicity, we should apply the same rule for all – whether drive-by contributions, members, or even owners of the project.

Since coding is not my strong skill, I really ask you all for your feedback and better suggestions.

## Voting on new features, milestones, goals etc.

I would suggest that we keep it simple and relatively fast …at least initially, to gain momentum and get 2.0 released.

So (temporarily), I would suggest that for any new features, bigger changes, decisions on what should constitute the next milestone or wider goals etc. we should:

- open a new issue
- a deadline, no shorter than 10 days, as soon as a suggestion (or several) is set in place
- people can vote with :+1: and :-1: for individual suggestions, where they may cast votes for as many suggestions they want
- at the end of the deadline, the suggestion with most votes (`=` № of :+1: `-` № of :-1:) is taken

After 2.0 is out, it may be time to re-address whether we should change the pace to be more slow and easy, with even more emphasis on collaboration and consensus.

---

Now, to eat my own dogfood, I suggest we apply the above voting proposal to this suggestion.

**Deadline: 2018-12-03**

To push this forward faster, I also suggest that if there is no agreement on a specific part (e.g. development style), we take that part out and start assembling better suggestions for that part separately.

**Comment by silverhook** [comment]
A further topic to discuss would be to choose between:

- `master` as always stable – there is a separate main development (e.g. `dev`) branch
- `master` as the main development branch

In both suggestions, I think stable releases should be done by tags and releases, with separate branches for testing/working on specific features.

But I feel this is a discussion on how to handle Elegant after the 2.0 release. For now let’s move fast and agile, so we finally push 2.0 out. So this is _not_ part of the suggestion above, but a note to refer to in the future.

**Comment by talha131** [comment]
I think master should only be used for releases.

development and hot fixes should be on separate branches. If an alpha or beta release is necessary than it should be from development branch, and should be marked as pre-release in Github.

Of course, frequent releases i.e. merging development to master is something to strive for. This way all branches stay in sync with master and do not diverge too much.

**Comment by silverhook** [comment]
It seems we are in agreement for the very basic rules. I’ll write up a pull request in the coming days.
