### ISSUE TITLE
Author blurb at the end of an article?

### ISSUE THREAD

**Issue by AWegnerGitHub** [Pelican-Elegant/elegant#185]
I've added an author blurb that appears at the end of each of my posts. Would something like this be useful for Elegant as a whole or is this better left as a customization for my site only?

The blurb looks like this at the bottom of each post:

![Author Blurb](https://user-images.githubusercontent.com/6462439/49228047-24ae5a80-f3b0-11e8-8a8d-4961693f7882.png)

It can handle a single author per article and the author needs to be defined in your Pelican configuration. The configuration looks like this:

```
AUTHORS = {
    u'Andy Wegner': {
        u'blurb': """ is a father, an engineer and a computer scientist. He is interested in online
            community building, tinkering with new code and building new applications.
            He writes about his experiences with each of these.""",
        u'friendly_name': "Andy Wegner",
        u'url': 'https://andrewwegner.com/'
    }
}
```

At the end of `article.html`, before comments, the article author is added via this:

```
    <div>
    {% from '_includes/article_author.html' import article_author with context %}
    {{ article_author(article) }}
    </div>
```

With the `_includes/article_author.html` looking like this:

```
{% macro article_author(article) %}
    {% if article.author %}
        <span class="author_blurb"><a href="{{ AUTHORS[article.author|string]['url'] }}" rel="author"><span class="author_name">{{ AUTHORS[article.author|string]['friendly_name'] }}</span></a> -
            {{ AUTHORS[article.author|string]['blurb'] }}</span>
    {% endif %}
{% endmacro %}
```

If this is something that would be useful for Elegant, I'll create a pull request.

**Comment by silverhook** [comment]
Can you provide a screenshot with more context? E.g. the whole screen on how it looks like in the article?

In general, as long as it’s optional, I can see how some would like that feature.

What I am concerned about is what happens if the author of an article is not the same as the one in the general configuration file? There is a `Authors:` field in every blog post source (see [docs][]).

Could we somehow make it read the `Authors:` tag instead?

Or at least have a loop that it would display the blurb only if the `Authors:` tag matches the `AUTHORS` variable in the main configuration?

If this gets approved, I have a feature in my fork (https://github.com/silverhook/pelican-elegant/commit/d35a5e9bb779d69493feca989f99b214b8408b33) that is somewhat similar – if a `Summary:` of an article is present, it shows it on the first page.

[docs]: http://docs.getpelican.com/en/stable/content.html#file-metadata

**Comment by AWegnerGitHub** [comment]
Below is a larger screenshot of the end of an article, including the author blurb.

![Larger Context](https://user-images.githubusercontent.com/6462439/49299936-9658d800-f486-11e8-8451-eef1a384d236.png)

I will look at the documentation you provided. I didn't realize multiple authors could be included, but I think a simple loop with a bit more error checking around whether an author exists in the configuration file would be simple enough to implement. 

As for reading the `Authors:` tag, aren't I already doing that, just with the poor assumption that there is only one author with this `AUTHORS[article.author|string]`? If not, I can change it to use the proper tag.

**Comment by silverhook** [comment]
What I was referring to is the fact that in each article you can have a different author – e.g. if you run a website for an organisation, you can have different authors write different articles/posts on the same “blog”. All that takes is to have a different author listed in `Author` or `Authors` tag in the article rst/markdown source – AFAIK, this is what refers to the `article.author` and the variable in the pelican configuration file is just a default, if the article does not mention that tag.

How about – and I am talking completely out of my arse now – we display the author blurb only if the `Author` (or part of the `Authors`) tag matches the author tag of the blurb.

This way we could potentially store author blurbs in (a separate file imported by) the config file that the theme would check for.

E.g.
- if the article said `Author: Alice` and sha has a blurb, it would include Alice’s blurb,
- if the article did not state any specific author, but Bob is the default author in the configuration file, and has a blurb, it would include Bob’s blurb instead
- if the article said `Carla` and she has no blurb set, it would simply not generate the blurb section.

In that case, I would suggest that the blurbs are being checked only if they exist in the settings, to avoid unnecessary checks for pages that don’t use blurbs.

---

A separate feature request for multiple authors would be really cool, but not likely a priority for 2.0. Still, do open it, so we can track it if someone picks it up.

It would be really cool if with multiple authors, we would also display multiple author blurbs (if they exist).

**Comment by AWegnerGitHub** [comment]
My plan is to make the included `article_author.html` page look like this: 

```
{% macro article_author(article) %}
    {% for author in article.authors %}
        {% if author|string in AUTHORS %}
            <span class="author_blurb"><a href="{{ AUTHORS.get(author|string).url }}"><span class="author_name">{{ author }}</span></a> -
                {{ AUTHORS.get(author|string).blurb }}</span><br />
        {% endif %}
    {% endfor %}
{% endmacro %}
```

This will:

 - work with the default author in the configuration file as long as they are listed in the `AUTHORS` dictionary
 - work with and display multiple `authors:` as long as all are listed in the `AUTHORS` dictionary 
 - work with a single `author:` listed as long as they are listed in the dictionary. This method is useful for over riding the default author
 - work with multiple `authors:` even if one or more aren't in the dictionary. This will only generate a blurb for the known author(s) and the others won't be listed.
 - with with a single author even if the `authors:` meta tag is used.

It will not generate a blurb for anyone that does not have an entry in `AUTHORS`. 

It will not work if a user uses the `author:` meta tag improperly by specifying multiple authors. In this case, no blurb will be generated. This is invalid:

```
author: Milton Bradley, Betty Crocker
```

The proper way to specify multiple authors is to use `authors:`

---

Design questions:

 - How do you want to separate multiple authors? With the example above, it is simply placing a `<br />` after each author. Is this ok?
 - Do we want to display *something* for unknown authors?
