### ISSUE TITLE
Find a logo for the github organization representing elegant

### ISSUE THREAD

**Issue by iranzo** [Pelican-Elegant/elegant#190]
Define a logo for the repository :-)

**Comment by talha131** [comment]
Or a pelican with bow tie 😆 That's what I always had in mind of the theme.

Anyway, whatever you guys decide. Great initiative! 👍

**Comment by silverhook** [comment]
https://www.toonpool.com/cartoons/Fliege._128421

**Comment by iranzo** [comment]
Is anyone up to drawing a new one so that we don't have issues with rights and propose it ?

**Comment by iranzo** [comment]
pelican + bow tie + monocle would be perfect  :-)

**Comment by silverhook** [comment]
I don’t think this is a blocker for any release really. So we can wait and see if anyone in our wider community is talented artist in this regard.

If it comes to rights management, I’m happy to help there :)

**Comment by iranzo** [comment]
Team that could have a look from my side asked me to 'ping them' in october as they are pretty busy right now, it's on my calendar to ask them again

**Comment by talha131** [comment]
You see the Pelican logo? I was thinking if they allow it, then we can 

1. color it black
1. Append E in cursive or some better font to it

So we will end up with `PE` like thing.

It will be an alteration of Pelican login. It would make sense for its theme logo to be based it.

It's pretty simple but it depends if Pelican team will allow us to use and modify their logo.

There an [open question](https://github.com/getpelican/pelican/issues/1008#issuecomment-440740973) from @silverhook that hasn't been answered yet.

Or we pick an image from deviant art or other free image source which has a license that we can use.

**Comment by azzamsa** [comment]
For note. There are also graphic designer that look for a project that need a logo, it's a win-win effort. We get a logo, they get a point to put in their cv. Some of them:

```
https://github.com/expectocode/telegram-export/issues/49
https://github.com/kennethreitz/saythanks.io/issues/42
https://github.com/melpa/melpa/issues/5452
```

**Comment by talha131** [comment]
>  There are also graphic designer that look for a project that need a logo, it's a win-win effort. 

Right. And that's what we are waiting for someone to offer their service. 

I don't have high hopes of for it though. We are one of the most popular Pelican theme, if not the most popular, but still our traffic is not that big to attract some budding talent.

I have been thinking of picking an image from dribble or deviantart and modify it, provided its license allows us to. Or just use the image without modification. For example,

1. https://dribbble.com/shots/6067561-Pelican
1. https://dribbble.com/shots/6174321-Pelican-logo
1. https://dribbble.com/shots/5998621-Pelican-Globe-Speed-logo-for-ATG-International

Or buy $2-5 image from some website. Like 

1. https://www.iconfinder.com/search/?q=pelican&price=free
1. https://www.flaticon.com/search?word=pelican

Or (and I am leaning strongly towards it), why pigeon hole ourselves to Pelican. We can pick any other good looking logo and use it. For example,

1. https://www.iconfinder.com/icons/343126/elegant_glasses_like_a_sir_mustage_rich_sir_smiley_smiley_face_icon
1. https://www.iconfinder.com/icons/4743073/bow_bowtie_hair_ribbon_suit_icon
1. https://www.flaticon.com/free-icon/tie_204331#term=elegant&page=1&position=15

# Moving Forward

I really like following images and think we can pick one from it. You all must check them out

1. https://www.visualpharm.com/free-icons/set/pelican
1. https://www.visualpharm.com/free-icons/set/necktie
1. https://www.visualpharm.com/free-icons/set/best%20seller
1. https://www.flaticon.com/free-icon/tie_204331#term=elegant&page=1&position=15

Or we pick a logo from here

http://logodust.com/

I think we can go forward with this one with color adjustments if necessary and it its license allows it

![tie](https://user-images.githubusercontent.com/1094724/60749326-a9e69700-9fb1-11e9-8a51-5096e068acf3.png)

**Comment by azzamsa** [comment]
https://dribbble.com/shots/6174321-Pelican-logo

This is awesome :)

**Comment by silverhook** [comment]
> https://dribbble.com/shots/6174321-Pelican-logo
> 
> This is awesome :)

I like this one as well. Especially if we can ask the guy to put a tie on it :D

**Comment by talha131** [comment]
I am thinking of taking the head and beak of Pelican from here https://dribbble.com/shots/6174321-Pelican-logo and then putting it on top of tie from [here](https://www.flaticon.com/free-icon/tie_204331#term=elegant&page=1&position=15)

But then I found [this image](https://www.dreamstime.com/stock-illustration-pelican-top-hat-monocle-vector-illustration-image85482111).

It's perfect. But

1. I don't understand their license. They say royalty free but when I try to download it redirects me to their payment page
1. We will still have to color its beak


![pelican-top-hat-monocle-vector-illustration-85482111](https://user-images.githubusercontent.com/1094724/61186191-e8e4ae80-a67b-11e9-9c84-a54158419b79.jpg)

**Comment by talha131** [comment]
>  Especially if we can ask the guy to put a tie on it :D

Instead of asking,

1. See if its license allows modification
1. If it does then we can do it ourselves

**Comment by silverhook** [comment]
> > Especially if we can ask the guy to put a tie on it :D
> 
> Instead of asking,
> 
>     1. See if its license allows modification
> 
>     2. If it does then we can do it ourselves

At a quick look, it doesn’t seem there is any license attached at all, apart from Dribble’s ToS, which aren’t super helpful in this regard. I would assume we would need to obtain a license directly from the author …which comes back to asking him.

**Comment by talha131** [comment]
I like this [image a lot](https://github.com/Pelican-Elegant/elegant/issues/190#issuecomment-511215407) but the website's sketchy practice of bait and switch left a bad taste in my mouth. And I don't feel like ordering anything from them.



We can go with Photoshoping tie on dribble pelican ourselves. Though I am not confident about the result. And also it seems it would be too much work for a result that would be at best an amateur effort.

I suggest we pick one logo from here https://logodust.com/. It seems to be the path of least effort.

**Comment by talha131** [comment]
OR we pick an image of a butterfly. There are plenty of them in different styles available for use online. 

Why a butterfly? Because they are nature's elegant creature.

In any case, lets reach a consensus in 1-2 weeks and close this issue down.

**Comment by silverhook** [comment]
https://thenounproject.com/search/?q=pelican

https://thenounproject.com/search/?q=elegant

I specifically like:

- this elegant feather: https://thenounproject.com/search/?q=elegant&i=1677772
- this pelican that looks a bit mayan, but also a bit like made out of speech bubbles: https://thenounproject.com/search/?q=pelican&i=2213839

**Comment by talha131** [comment]
If we select a monochromatic icon, then we will have to

1. Decide colors to fill in
1. Slap "Elegant" on it

This will involve more back and forth. 

I am not against the idea but I do think our energy is better spent in other tasks. That's why I think we should take a shortcut. To me the best shortcut is to pick a butterfly colored image and slap Elegant on it.

Or someone should take up this task and then share the few final results here. This will be much more efficient.

**Comment by silverhook** [comment]
I see no reason why it _needs_ more colours than one or two.

And if it is a icon-like image, we can include it by default as the favicon as well :)

**Comment by silverhook** [comment]
E.g. if you tilt the elegant feather a bit, it looks like a feather pen for writing, which is suitable, as a pelican both has feathers, and the project name “Pelican” is an anagram from “calepin”, which is French for a notebook.

![Screenshot_20190717_155908](https://user-images.githubusercontent.com/3227264/61381759-d486f880-a8ab-11e9-92df-580123427a84.png)

Regarding the colours, the easy way out would be to try to re-use one of the accent colours we use in the Pelican Elegant theme already. In the quick example above I simply took a colour that I thought resembles ink.

**Comment by silverhook** [comment]
Here’s a similar outcome, if we take the pelican, encircle him and use the colour that we use for main headers.

![Screenshot_20190717_160958](https://user-images.githubusercontent.com/3227264/61382573-53306580-a8ad-11e9-8f20-152b59db8d26.png)

**Comment by talha131** [comment]
Both looks great. A rounded box would be better than a circle. 

@silverhook can you color the feather icon with the same red color for preview?

And place them inside rounded corner square for preview.

**Comment by silverhook** [comment]
I was merely playing with the website they reside on, so there is no option to have an empty rounded-corner square. If we really want to have an empty rounded-corner square, I can whip out Inkscape again and see if I can get it done.

I’ll post the two images separately, so we can have a vote, if desired.

**Comment by silverhook** [comment]
![Screenshot_20190717_170722](https://user-images.githubusercontent.com/3227264/61386884-5af40800-a8b5-11e9-99e0-2bffae903f6e.png)

The interface unfortunately does not offer an empty rounded-corner square, so I generated a full one with the `#f5f5f5` colour, which I picked from the top link bar as a middle colour.

**Comment by silverhook** [comment]
![Screenshot_20190717_171004](https://user-images.githubusercontent.com/3227264/61387081-b8885480-a8b5-11e9-93dd-8d9b70265ba9.png)

As requested, the feather pen in the Elegant red.

**Comment by talha131** [comment]
Thank you @silverhook I like [this one better](https://github.com/Pelican-Elegant/elegant/issues/190#issuecomment-512301000)

**Comment by talha131** [comment]
I meant between feather and pelican, pelican wins by a huge margin. We can tweak the border later or add colors to beak and feet etc, later.

**Comment by silverhook** [comment]
Personally, I lise

**Comment by jackdewinter** [comment]
If I can jump in here for a bit... has anyone tried reducing the proposed logos to their favicon sizes and post how they look at that resolution?

**Comment by silverhook** [comment]
Not really, no. That was more of a brainfart of mine. Do you have any experience with that, @jackdewinter ?

**Comment by jackdewinter** [comment]
![image](https://user-images.githubusercontent.com/25124582/61570349-ed74e280-aa40-11e9-951b-7ccfa088af89.png)

That would be a start.  honestly, just trimmed it down a lot and then resized it

**Comment by jackdewinter** [comment]
From talking to a friend, it is considered acceptable to have a large image be different than the favicon, but not too much.  I.e. can you see how that is a smaller version of the bigger file?

**Comment by talha131** [comment]
Guys how does this look?

![logo1](https://user-images.githubusercontent.com/1094724/61581168-2fcb1c00-ab34-11e9-8c1c-2b7e84c75391.png)

**Comment by talha131** [comment]
Your feedback about this image? **This is a rough draft**.

![logo1](https://user-images.githubusercontent.com/1094724/61581168-2fcb1c00-ab34-11e9-8c1c-2b7e84c75391.png)

Here is how it look at smaller sizes

![apple-touch-icon-76x76](https://user-images.githubusercontent.com/1094724/61581233-3c03a900-ab35-11e9-97f4-4ffac9fd21ef.png)

![apple-touch-icon-180x180](https://user-images.githubusercontent.com/1094724/61581236-3efe9980-ab35-11e9-8979-f0695e0d374b.png)

# Todo

It needs improvements, like

1. Fill areas have slight white spaces
1. Square dimensions
1. Remove white area outside the border

# Should I proceed with it?

1. Is the logo fine?
1. Colors selection is ok?

I am not looking for 100% perfection. If on scale of 0 to 10, you feel 5 about it, it's good enough for me. (Whatever it takes to close this long standing issue).

I will fix the todo items once I get a consensus for one or two active users.

Good thing is that this an SVG image. I didn't had to touch Photoshop.

**Comment by jackdewinter** [comment]
From what I checked online, we need a 16x16 and a 32x32 for favicon.  Can you show us one at that resolution?

**Comment by talha131** [comment]
![apple-touch-icon-57x57](https://user-images.githubusercontent.com/1094724/61581879-a3255b80-ab3d-11e9-90ce-858c73a12b13.png)

>  we need a 16x16 and a 32x32 for favicon

Seems old standard. I have been using https://iconifier.net/ for all these years. The minimum it generates is 57x57.

**Comment by jackdewinter** [comment]
I agree, and I did find a number of sites that supported 144x144.   Most of the favicon specific sites, like this one https://convertico.com/favicon/  only support 16x16 and 32x32.

**Comment by talha131** [comment]
So you are Ok with the submission?

**Comment by jackdewinter** [comment]
Yup... looks like a pelican wearing a black format jacket.
