### ISSUE TITLE
Guidelines on adding new members and admins to the organization?

### ISSUE THREAD

**Issue by talha131** [Pelican-Elegant/elegant#193]
Continuing discussion from #180.

Since the development model changed from single developer to a community driven dev (see #173), the member list has grown from 2 to 4 in few days. It's pertinent if we discuss guidelines on adding new members to the organizations. 

I will get the ball rolling. 

1. Keep number of admins to the minimum
1. Enable 2FA for added security
1. Add new members if the current members and admin do not have time to support the project so that the show keeps going on
    1. They are not blocked by admins and other members. For example waiting for other members to merge their PR etc
     1. Are committed to own a feature i.e. if they add a feature then can support it for at least a couple of months. This way they can close the support issues or assign them to themselves.
1. If someone wants to retire then let others know so that he can be removed from the organization.

These are few guidelines that I had in mind. @silverhook has more experience of community driven development. He and everyone else is invited to share his thoughts on this.

**Comment by talha131** [comment]
@silverhook and @iranzo can we close this issue. I want to enforce 2FA before closing this issue. What do you guys think?

**Comment by silverhook** [comment]
I think this is quite lightweight, but works.

**Comment by iranzo** [comment]
I already use 2FA, so go ahead!
-- 

Pablo Iranzo Gómez

GnuPG: 0x5BD8E1E4
Web: https://iranzo.github.io  ||  https://citellus.org

**Comment by silverhook** [comment]
@ashwinvis, @AWegnerGitHub, @calfzhou, we are discussing making 2FA (two-factor authentication) obligatory for all all owners/team members. Would that be OK with you?

**Comment by ashwinvis** [comment]
I enabled 2FA. Go ahead.

**Comment by silverhook** [comment]
Perfect, thank you :)

@calfzhou, @AWegnerGitHub, can you two enable 2FA as well?

Here is more info on GitHub’s 2FA, if you are interested:
https://help.github.com/en/articles/securing-your-account-with-two-factor-authentication-2fa

The idea behind is that owners and members have a lot of power over the organisation and its repositories, so it would be prudent to put an additional layer of security when it comes to access to it.

**Comment by calfzhou** [comment]
I enabled 2FA. Thanks!

**Comment by calfzhou** [comment]
I enabled 2FA. Thanks!

Best Regards,
Ji

**Comment by AWegnerGitHub** [comment]
I am on vacation until the middle of next week. I will enable it when I get
back

**Comment by silverhook** [comment]
@AWegnerGitHub, perfectly fine. We’ll wait for you to come back. Enjoy your vacation! :tropical_drink: 

@calfzhou, many thanks :+1:

**Comment by AWegnerGitHub** [comment]
I have enabled 2FA as well

**Comment by talha131** [comment]
Thank you @AWegnerGitHub 

Now, 2FA is enabled for all team members.

----

**Comment by silverhook** [comment]
:clap: :tada:
