### ISSUE TITLE
Archives page is messed up

### ISSUE THREAD

**Issue by talha131** [Pelican-Elegant/elegant#202]
I am not sure is it a bug in the elegant or some configuration is messed up

https://pelican-elegant.github.io/archives.html

![](https://i.imgur.com/L4pSwkX.png)

**Comment by AWegnerGitHub** [comment]
I don't see it in the blame history for [archives.html](https://github.com/Pelican-Elegant/elegant/blame/master/templates/archives.html), nor can I find it in the issues history, but I'm pretty sure I found the solution here at some point.

The solution I'm using on my blog is adding a `<br />` at the end of [line 57 in archives.html](https://github.com/Pelican-Elegant/elegant/blob/95311cb81271bcd16d3ddc606f5fe1b5135c887c/templates/archives.html#L57)

The full line becomes 

```
                </article><br />
```

**Comment by talha131** [comment]
The year is supposed to appear only once. Like 2014 and then a whole list of articles published in the year.

We have two bugs here,

1. Year is displayed for every article
1. All lines are intended to the right with respect to their predecessor.

**Comment by talha131** [comment]
Looks like Jinaj is to be blamed for it.

https://github.com/Pelican-Elegant/elegant/issues/162

**Comment by iranzo** [comment]
It's back in NEXT branch:

<https://pelican-elegant.github.io/next/archives.html>

Something missing to have in that branch?

**Comment by iranzo** [comment]
I've cherry-picked again the fixing change in 'next' so the proper nesting in loops is done and it's now building
