### ISSUE TITLE
[RFE] Include article summary in recent posts

### ISSUE THREAD

**Issue by iranzo** [Pelican-Elegant/elegant#209]
Would this be something we want for the theme (I do for sure):

![image](https://user-images.githubusercontent.com/312463/49855850-b4132f00-fdee-11e8-9337-167aba23d7e6.png)

or

![image](https://user-images.githubusercontent.com/312463/49855909-da38cf00-fdee-11e8-86cd-1421fe9fee04.png)

If so, what will the variable we want to define to enable/disable the feature?

Code change is quite simple on 'template/index' and I can submit PR for it

**Comment by iranzo** [comment]
~~~
            <article>
                <a href="{{ SITEURL }}/{{ article.url }}">{{ article.title }} {%if article.subtitle %} <small> {{ article.subtitle }} </small> {% endif %} </a>
                <div class="content summary">
                <small>
                {% if article.description %}
                    <p>{{ article.description }}</p>
                {% else %}
                    <p>{{ article.summary | striptags | replace(' …', ' ...') | replace(' ...', '&nbsp;&#8230;') }}</p>
                {% endif %}
                </small>
                </div>
                <section>
                    posted in
                <a href="{{ SITEURL }}/{{ CATEGORIES_URL }}#{{ article.category.slug }}-ref">{{ article.category }}</a>
                <div class="recent-posts-time">
                <time pubdate="pubdate" datetime="{{ article.date.isoformat() }}">{{ article.locale_date }}</time>
                </div>
                </section>
            </article>
~~~

**Comment by talha131** [comment]
Thanks for the explanation. I am waiting for @silverhook feedback to close #125. Lets give it few more days.

**Comment by silverhook** [comment]
The approach in #125 already renders either:

1. the `Summary` tag, if it exists; or
1. if that is not available, the first X words of the article (and appends the ellipsis), which can be set by `SUMMARY_MAX_LENGTH` and is defaulted to 50 words – see [Pelican docs: Settings](http://docs.getpelican.com/en/stable/settings.html?highlight=summary_max_length#basic-settings).

From my understanding, this is exactly what the `article.summary` is for already – see [Pelican docs: Creating Themes](http://docs.getpelican.com/en/stable/themes.html?highlight=summary#article)

@iranzo, where did you find `article.description`? I can’t find it in the Pelican documentation, so I assume it’s a lower-level variable that Pelican operates with internally and eventually renders into `article.summary`.

Unless I’m missing something, I’d say that #125, without the `<footer>` block is the more elegant and cleaner version.

**Comment by iranzo** [comment]
I think that article.description is taken from the yaml preamble.

For example: https://github.com/getpelican/pelican/blob/master/pelican/themes/simple/templates/article.html#L14

**Comment by iranzo** [comment]
Let's close this and wait for #125
