### ISSUE TITLE
Upgrade fontawesome

### ISSUE THREAD

**Issue by talha131** [Pelican-Elegant/elegant#217]

**Comment by iranzo** [comment]
According to web:

<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.1/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">



so it's a bump from 4.0 to 5.7.1...

**Comment by iranzo** [comment]
bump to 4.7 seems just a drop-in replacement
