### ISSUE TITLE
'.html' is hardcoded on Categories, Tags, and Archives

### ISSUE THREAD

**Issue by tshepang** [Pelican-Elegant/elegant#22]
I saw this in `templates/base.html`.

**Comment by tshepang** [comment]
this went stale, so closing

**Comment by iranzo** [comment]
Is this still the case? updates are from some years ago, but still I do see hardcoded archives, tags and categories while my pelican setup does use /tags/ vs /tags.html and likelywise for the others

**Comment by silverhook** [comment]
If this still happens, we should address it IMHO.

On my website, it does seem to still be the case, so re-opening.

**Comment by iranzo** [comment]
I was trying to find a new theme that is responsive for mobile devices and doing initial 'simple' checks found this :/

**Comment by silverhook** [comment]
@iranzo We have just expanded Elegant from a single maintainer to a community-driven projects and are currently picking up the pace again, so it’s a great time to get involved (see #173 for more).

I can’t promise we’ll be able to tick all your checkboxes, but if you see anything missing (or better yet, have a proposal/pull request), please do file an issue.

**Comment by iranzo** [comment]
I saw it, but I'm not an expert in pelican (nor to talk about elegant), and so far just did some small patch some years ago for blue-penguin theme I'm currently using at my site.

Please do assign this to me as I think I can do it

**Comment by silverhook** [comment]
I’m not even a coder and fixing stuff in Elegant (or any other Jinja-based theme) is very doable. So I’m sure you’ll rock it! :metal: 

Assigning to @iranzo now.

**Comment by iranzo** [comment]
https://github.com/Pelican-Elegant/elegant/pull/186

**Comment by iranzo** [comment]
> I’m not even a coder and fixing stuff in Elegant (or any other Jinja-based theme) is very doable. So I’m sure you’ll rock it! 
> 
> Hmmm, odd, it doesn’t seem like I can assign it to you, @iranzo. Can you try to assign it to yourself?

Probably as I'm not member of the project staff you can't do that (I had a similar issue with a project I own)

**Comment by silverhook** [comment]
That makes sense. I don’t have a lot of experience with admining a project that has several outside contributors.

I’ll assign myself then, so it’s my fault if this doesn’t push forward.

The way I understand it, as soon as your pull request gets merged, you should be able to be assigned issues as well.

**Comment by iranzo** [comment]
@silverhook check https://iranzo.github.io/ and try the tags, categories, archives

**Comment by iranzo** [comment]
Just tested and the 'rendered' file gets the vars verbatim:


exclude_pages = ['/{{ ARCHIVES_URL }}', '/{{ TAGS_URL }}', '/index.html', '/{{ CATEGORIES_URL }}', '/search.html'];

**Comment by iranzo** [comment]
I did submitted the PR, so it should be someone else to validate and merge :-)
