### ISSUE TITLE
Commit c0624f9 breaks Pelican on Jinja 2.8

### ISSUE THREAD

**Issue by silverhook** [Pelican-Elegant/elegant#223]
As mentioned in https://github.com/Pelican-Elegant/elegant/pull/207 that PR breaks compatibility with Jinja 2.8 (and older).

I suggest that we revert commit c0624f9 in master and move it to 2.1.

That way we would (eventually) have:

- 2.0 – that would (continue to) work on Pelican and Jinja versions that are often bundled with common Linux distros (e.g. latest Debian stable has Pelican 3.7.1 and Jinja 2.8)
- 2.1 – that would be similar, but work on latest and greatest Pelican and Jinja
- 3.0 – that is the future, even leaner and even more elegant :)

**Comment by silverhook** [comment]
As you can imagine, since I filed this bug, I disagree to _some_ extent.

I understand your comment from the delevoper’s PoV, but given the wide use of both Pelican and Elegant, I suspect there are not few who do not run the latest and greatest in a virtual environment, but simply use package provided to them by the distro they use (e.g. I do that). Also, since Pelican is a static website generator, the risk to your system when _not_ running the latest version is close to zero.

Imagine someone wants to build a blog (perhaps for the first time!) and they find Pelican. They then find that there is a package in the package manager of the distro they run on the server – awesome! because they’re not a Python dev! – and install it. Cool, it works! They set it up, write the first post and all is peachy. Next they start looking for a better looking theme and find Elegant. They pull the latest (stable) release of Elegant and suddenly hit this bug. Do we really expect them to set up a virtual env, install Pelican and Jinja there, and remember to use the virtual env every time they upgrade, just so they can use a theme?

I know that we can’t support all old versions and we can’t support them for a long time.

I’d say that supporting versions that are in the latest stable branches of the most commonly used (server) distros is a reasonable compromise.

I’m also not suggesting that we scrape this commit. We need it! It future-proofs Elegant. I just suggest that we at make at least one release that works with what is currently available in stable distros.

Looking forward to hear what others think.

**Comment by iranzo** [comment]
If we document on 'how to get started' we can instruct to use virtual env, or suggest a 'travis-ci.yml' similar to the one we do use to automate publishing on github for setting up a blog

Anyone else, willing to do more things like setting their own domain, can still do it on github and if a separate webserver is used, supposedly the skills will be higher to understand how to setup a virtualenv, etc

It's not just pelican, but we also require some other plugins like bs4, etc to be installed to have theme working properly...

**Comment by silverhook** [comment]
I just don’t want us to limit our user base to developers.

I know about `pip` (and `virtualenv`), but if all dependencies are in a standard Linux distro, I see no reason why we should expect our users to learn to use either, just because our theme expects a newer version of dependencies than the Pelican package in the distro.

See e.g.:

- https://packages.debian.org/search?keywords=python3-jinja2
- https://packages.debian.org/search?keywords=pelican

I realise that in most other modern distros Jinja is of newer version, but Debian stable is one of the most common server distros out there.

So the way to get stuck with an older Jinja right now is either:

- be on Debian stable (i.e. Debian 9 “Stretch”), or
- set up `virtualenv` with an older Jinja and forget about it and don’t remember how you get to that place (happened to me before – yes, I can be that thick)

Also see:

- https://repology.org/metapackage/python:jinja2/versions
- https://repology.org/metapackage/pelican/versions

Debian 10 “Buster” should come out mid-2019, at which time we could re-evaluate if Jinja older than 2.9 is still the default in any major distro.

**Comment by talha131** [comment]
So one way to get around this issue is to educate the user. We already are one and only Pelican theme that has comprehensive and increase repertoire of documentation.

I favor this approach because in my experience most people who use Pelican are already teach savvy, at least to some extent. Otherwise they would be using WordPress or SquareSpace. Familiarity with command line is a must to use Pelican and Elegant.

Other solution is to use your approach and revert the commit. 

Votes and feedback from others especially @calfzhou  and @AWegnerGitHub  would be appreciated.

## Note

**If we decide to revert the commit** then we must remember to test the theme on the specified Jinja and Pelican version. It is advised to tackle this issue the last, i.e. only when all other issues in the milestone has been fixed.

**Comment by silverhook** [comment]
I am OK to solve this in documentation given the fact that:

1. the only major distro causing issues seems to be Debian 9; and
1. in probably 6-12 months from now Debian 10 should be the next stable and fix this.

But the debate of how tech-(un)savvy our target group is (or we want to have), remains …

**Comment by iranzo** [comment]
Instruct users to use pip to install things outside of a virtualenv should be forbidden it can badly break environments :-)

**Comment by silverhook** [comment]
> Instruct users to use pip to install things outside of a virtualenv should be forbidden it can badly break environments :-)

Agreed.

Which means we have the options of either:

1. rely on distros; or
1. limit ourselves to users who are tech-savvy enough to actually use `pip` and `virtualenv` (or their equivalents) properly and consistently – TBH, I don’t trust myself with it too much either.

**Comment by iranzo** [comment]
I usually recomend to install 'pipsi' if available to automate invokation, load and execution of software in a virtualenv.

We can also create a tox.ini that automate the full setup via the requirements.txt and include commands for it, but this will require users to install 'tox' command on their distro

**Comment by talha131** [comment]
@silverhook to be clear, when a debian user installs Pelican, he uses `apt-get` or `yum` to install Pelican. 

It automatically installs Jinja from the package repository? Or user has to install Jinja separately using `apt-get`?

----

Is anyone willing to take up the following task?

1. Install Pelican and Jinja versions that @silverhook reported.
1. Make sure you are not using any other versions.
1. Get elegant and revert the said commit
1. Run and see if everything is working.

If everything is fine, then I will revert the commit and release 2.0. I will release 2.1 immediately afterwards with the commit.

Let me know if anyone have a better idea.

**Comment by silverhook** [comment]
If Pelican 3.x works with newer Jinja, we could get away with just having an explanation how to pin a newer Jinja on Debian 9.

But Pelican 4.x is not even in Debian Sid (i.e. unstable) yet, so at this stage it’s unsure if it will be in Debian 10.

**Comment by silverhook** [comment]
@iranzo That’d work, of course.

But then we have to accept that we will receive support requests also for virtualenv-related issues.

Your blog-o-matic is really cool, and IMHO we should promote it, but it shouldn’t be the only officially supported way. That would be limiting our users too much to just one way to run/deploy Pelican and even that on one specific host.

**Comment by iranzo** [comment]
If Debian doesn't support pelican 4.x, we can tell user to install pipsi (for the virtualenv) and from it, install newest pelican so that should be good.

About Talha's plans:

Go ahead :-)

**Comment by talha131** [comment]
close via e541ba3

**Comment by silverhook** [comment]
Updating the issue, for future reference: Debian 10 (Buster) is out and it includes Pelican 4.0.x, which works with newer Elegant versions.

I tested it with a few V2.x versions and V3.0.0.
