### ISSUE TITLE
Make sure Elegant is compatible with text-only browsers (e.g. lynx, elinks, w3m)

### ISSUE THREAD

**Issue by silverhook** [Pelican-Elegant/elegant#224]
It would be **nice to have** Pelican with Elegant work fine on text-only browsers as well.

It may very well be that this is not possible to pull off in the theme alone. But it would be a nice thing to check and try to get right, if it’s reachable in 3.0 or after it :)

**Comment by talha131** [comment]
Last time I check, most of it worked. It shouldn't be a hard goal.

Good idea @silverhook. Lets do it in 3.0

**Comment by talha131** [comment]
I have tested in lynx. It works well.
