### ISSUE TITLE
¿Redirect template?

### ISSUE THREAD

**Issue by iranzo** [Pelican-Elegant/elegant#238]
I was thinking the other day, about creating a 'redirect' template (not even sure if it's possible), but idea would be to use an HTTP REFRESH so that a 'slug' can redirect to another one, in case for example an article name is updated and you want to keep the new one and still redirect older users, or even to redirect to another site.

What do you think?

**Comment by talha131** [comment]
It's good to have. 

On my blog, I too had a redirect set for `http://oncrashreboot.com/pelican-elegant`, that redirects to [detailed article](http://oncrashreboot.com/elegant-best-pelican-theme-features). Now for the life of me, I can't recall how I setup the redirect. Neither can I find code for it in the [source](https://github.com/talha131/onCrashReboot) or [generated output](https://github.com/talha131/talha131.github.io/).

Anyway, I am not against adding it to the theme.

**Comment by iranzo** [comment]
Covered in https://github.com/Pelican-Elegant/elegant/pull/244
