### ISSUE TITLE
Need to specify the link in nav-bar

### ISSUE THREAD

**Issue by azzamsa** [Pelican-Elegant/elegant#250]
Hi

I saw [some issue](https://github.com/Pelican-Elegant/elegant/issues/203) about this. The original code using "hard coded" .html url. Then [someone change it](https://github.com/Pelican-Elegant/elegant/pull/186/files) to non hard code.

It took me long time to read the issue and searching the web. Till I find [this solution](https://github.com/getpelican/pelican/issues/2490#issuecomment-446666400)

It works after I specify

```
TAGS_URL = 'tags.html'
CATEGORIES_URL = 'categories.html'
ARCHIVES_URL = 'archives.html'
```

Why it doesn't work by default, at least for me ? Am I missing something ?

Thank you for this beloved theme :)

**Comment by talha131** [comment]
@azzamsa that's strange. You should not have to add these settings. See our code here

https://github.com/Pelican-Elegant/elegant/blob/master/templates/base.html#L70-L72

Notice the `defaults` function. For example,

```
 CATEGORIES_URL|default('categories') 
```

The code should have worked outside the box.

Can you please,

1. Make sure you have the latest HEAD from elegant repo?
1. If it is, then please create a repo with your source and we will try to reproduce it at our end.

**Comment by azzamsa** [comment]
> See our code here

@talha131 Sure I read those code carefully. So that I opened the issue here. I am using the latest version of this repo. I read the code carefully, even I modify archives.html, categories.html  and other to have ability for hiding page with my custom metadata.

> If it is, then please create a repo with your source and we will try to reproduce it at our end.

This is [my source](https://github.com/azzamsa/azzamsa.github.io/tree/source/themes/elegant)

**Comment by azzamsa** [comment]
> glad you like the theme!

@silverhook yes. it's very neat and beautiful :). I migrated from octopress this morning after using it for about 2 year. Very happy today, because I understand what every files are doing. I don't have any ideas why those bunch of octropess exist. Have more control now with pelican :)

> We have also set up a new website for Elegant, 

This [conf](https://github.com/Pelican-Elegant/documentation/blob/master/pelicanconf.py) and article examples help me a lot in this migration. It easier to see the real world example. Those "real" source really helped A LOT.

> Since you’ve done some research on this already, but weren’t involved with writing the change in the first place, you’d be a perfect candidate to write that little piece. If you’re willing to volunteer, of course wink

Sure, I love python, I may take a look at this.

**Comment by talha131** [comment]
@azzamsa Thanks for the quick response. I need the source code of your blog. What you have pointed me towards, is the generated html.

I need the repository which has your markdown files and pelican configuration in order to reproduce the issue at my end.

**Comment by azzamsa** [comment]
@talha131 Indeed that was the "source". 

I put them together with the output in Github, in different branch. One for [source files](https://github.com/azzamsa/azzamsa.github.io/tree/source), another for [output](https://github.com/azzamsa/azzamsa.github.io/tree/master)

**Comment by talha131** [comment]
@iranzo if possible can you spare some time for this? 

I tested it cursory on my end but failed to reproduce the issue. I will revisit it later, but meanwhile please look into it if it's not a trouble for you.

**Comment by talha131** [comment]
I am lost here. I thought `default` function in [the code](https://github.com/Pelican-Elegant/elegant/blob/master/templates/base.html#L76-L78) should have made sure such issue do not occur.

If we change `default('categories')` to `default('categories.html')` for eg, would it fix the issue?

**Comment by iranzo** [comment]
AFAIK, it should, if @azzamsa confirms, I'll use the source files he indicates without the variables he indicated in this post to test

**Comment by azzamsa** [comment]
1) If I disable the variables setting and add '.html' to base.html : **worked**

``` diff
modified   pelicanconf.py
@@ -6,9 +6,9 @@ AUTHOR = 'azzamsa' 
-TAGS_URL = 'tags.html'
-CATEGORIES_URL = 'categories.html'
-ARCHIVES_URL = 'archives.html'
+# TAGS_URL = 'tags.html'
+# CATEGORIES_URL = 'categories.html'
+# ARCHIVES_URL = 'archives.html'
 
modified   templates/base.html
@@ -73,9 +73,9 @@
-                            <li {% if page_name == 'archives' %} class="active"{% endif %}><a href="{{ SITEURL }}/{{ ARCHIVES_URL|default('archives') }}">Archives</a></li>
-                            <li {% if page_name == 'categories' %} class="active"{% endif %}><a href="{{ SITEURL }}/{{ CATEGORIES_URL|default('categories') }}">Categories</a></li>
-                            <li {% if page_name == 'tags' %} class="active"{% endif %}><a href="{{ SITEURL }}/{{ TAGS_URL|default('tags') }}">Tags</a></li>
+                            <li {% if page_name == 'archives' %} class="active"{% endif %}><a href="{{ SITEURL }}/{{ ARCHIVES_URL|default('archives.html') }}">Archives</a></li>
+                            <li {% if page_name == 'categories' %} class="active"{% endif %}><a href="{{ SITEURL }}/{{ CATEGORIES_URL|default('categories.html') }}">Categories</a></li>
+                            <li {% if page_name == 'tags' %} class="active"{% endif %}><a href="{{ SITEURL }}/{{ TAGS_URL|default('tags.html') }}">Tags</a></li>
```

HTTP request indicates that the file found
```
127.0.0.1 - - [14/Jan/2019 20:00:15] "GET /archives.html HTTP/1.1" 200 -
127.0.0.1 - - [14/Jan/2019 20:00:17] "GET /categories.html HTTP/1.1" 200 -
127.0.0.1 - - [14/Jan/2019 20:00:18] "GET /categories.html HTTP/1.1" 200 -
127.0.0.1 - - [14/Jan/2019 20:00:19] "GET /tags.html HTTP/1.1" 200 -
```

2) If I disable the variables setting and _without_ adding '.html' to base.html : **failed**

```
127.0.0.1 - - [14/Jan/2019 20:02:18] "GET /categories HTTP/1.1" 404 -
127.0.0.1 - - [14/Jan/2019 20:02:18] code 404, message File not found
127.0.0.1 - - [14/Jan/2019 20:02:18] "GET /favicon.ico HTTP/1.1" 404 -
127.0.0.1 - - [14/Jan/2019 20:02:25] code 404, message File not found
127.0.0.1 - - [14/Jan/2019 20:02:25] "GET /tags HTTP/1.1" 404 -
```

![2019-01-14-20 08 09](https://user-images.githubusercontent.com/17734314/51114542-318bee00-1838-11e9-8816-0e92e47ef280.png)

3) adding `.html` manually in step 2. 

![2019-01-14-20 08 24](https://user-images.githubusercontent.com/17734314/51114567-423c6400-1838-11e9-99a6-2653052b454b.png)

**Comment by iranzo** [comment]
While testing #270 , I've tried removing the values for:

#TAGS_URL = 'tags.html'
# CATEGORIES_URL = 'categories.html'
# ARCHIVES_URL = 'archives.html'

by commenting them and it worked fine.

Please note that my updated files for 270 were rebased against master, so not sure if there was any other missing commit there

Categories, archives and tags does work and the default is the 'folder' so /categories/  /tags/ or /archives/

@azzamsa can you test the files attached to 270 and revalidate this issue?

**Comment by azzamsa** [comment]
> @azzamsa can you test the files attached to 270 and revalidate this issue?

Dunno what happened. Tried:

1) `make html` with master revision


![2019-01-15-11 09 50](https://user-images.githubusercontent.com/17734314/51158291-65a5f400-18b6-11e9-9529-e4fb63d970fe.png)

2) `make html` with hide-article branch

![2019-01-15-11 12 47](https://user-images.githubusercontent.com/17734314/51158319-840bef80-18b6-11e9-9808-c7df0214674d.png)

Nothing works. Maybe the error comes from my local machine.

**Comment by iranzo** [comment]
Check too with the tarball on 270

**Comment by azzamsa** [comment]
Downloaded, tried, no luck.


![2019-01-15-14 42 52](https://user-images.githubusercontent.com/17734314/51165782-f0e1b280-18d3-11e9-8f54-91d8e6c1868d.png)

No different in code, just some untracked files.

**Comment by iranzo** [comment]
That's my diff for your pelicanconf:
diff --git a/pelicanconf.py b/pelicanconf.py
index 5c776d6..4e0d8d3 100755
--- a/pelicanconf.py
+++ b/pelicanconf.py
@@ -6,9 +6,9 @@ AUTHOR = 'azzamsa'
 SITENAME = 'AZZAMSA'
 SITEURL = 'http://localhost:8000'
 
-TAGS_URL = 'tags.html'
-CATEGORIES_URL = 'categories.html'
-ARCHIVES_URL = 'archives.html'
+# TAGS_URL = 'tags.html'
+# CATEGORIES_URL = 'categories.html'
+# ARCHIVES_URL = 'archives.html'


And the tarball uploaded again, with 'standard' Elegant pelican theme (without customizations):

rm -Rfv themes plugins
git submodule update
peru sync

[azzamsa.github.io-v2.zip](https://github.com/Pelican-Elegant/elegant/files/2763246/azzamsa.github.io-v2.zip)


When running make devserver, the generated page has working ccategories, archives and tags, and the url shown in my browser is:

http://localhost:8000/archives
http://localhost:8000/tags
http://localhost:8000/categories/

**Comment by azzamsa** [comment]
Tried `azzamsa.github.io-v2.zip` with no changes : failed. then tried with `make html`:faied

Btw, I never use `make deserver`. I use `make html/make publish` then `$ python -m http.server`

![anim](https://user-images.githubusercontent.com/17734314/51247884-05e83f80-19c1-11e9-9d60-5de8660c7660.gif)

**Comment by iranzo** [comment]
Hi,


~~~sh

 iranzo  /  tmp  azzamsa  ls
azzamsa.github.io  azzamsa.github.io-v2.zip
 iranzo  /  tmp  azzamsa  cd azzamsa.github.io/
 iranzo   test  /  tmp  azzamsa  azzamsa.github.io  ls
content   output          peru.yaml  publishconf.py  requirements.txt  themes
Makefile  pelicanconf.py  plugins    __pycache__     tasks.py
 iranzo   test  /  tmp  azzamsa  azzamsa.github.io  make devserver
pelican -lr /tmp/azzamsa/azzamsa.github.io/content -o /tmp/azzamsa/azzamsa.github.io/output -s /tmp/azzamsa/azzamsa.github.io/pelicanconf.py 

-> Modified: content, theme, settings, [static]theme/images, [static]images. re-generating...
Done: Processed 19 articles, 0 drafts, 0 pages, 0 hidden pages and 0 draft pages in 0.59 seconds.
127.0.0.1 - - [16/Jan/2019 14:55:45] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [16/Jan/2019 14:55:45] "GET /theme/css/style.min.css?8bdcf96a HTTP/1.1" 304 -
127.0.0.1 - - [16/Jan/2019 14:55:46] "GET /archives HTTP/1.1" 200 -
127.0.0.1 - - [16/Jan/2019 14:55:47] "GET /categories/ HTTP/1.1" 200 -
127.0.0.1 - - [16/Jan/2019 14:55:49] "GET /tags HTTP/1.1" 200 -
127.0.0.1 - - [16/Jan/2019 14:55:50] "GET /archives HTTP/1.1" 304 -

~~~

Still works for me on a new temporary folder being created for this.

If you've pipsi installed can you try with latest pelican version and use make devserver which uses the pelican builtin server?

**Comment by azzamsa** [comment]
Strange, `make devserver` work, but why `python -m http.server` didn't work.

So, if `make devserver` worked. If I do `make github` if this work in my github pages deployment ?

**Comment by azzamsa** [comment]
As far as I know browser will read index.html if it read a folder, this same behavior of jekyll, when we created pages about. it created about-dir/index.html.

I suspect devserver handle this 'magically'.

**Comment by iranzo** [comment]
I always did make devserver, tested and then make github and it worked, but it's easy for you to give it a try :-)

**Comment by azzamsa** [comment]
DONE. Summary:

- non direct link doesn't work with normal python server e.g `python -m http.server`. We have to use `ARCHIVES_URL = 'archives.html'`
- non direct link worked, when serving site using `make serve` / `make devserve`.

Even if non direct link didn't work with `python -m http.server` github pages will render it just fine.

I think pelican had already [handle non direct link magically](https://github.com/getpelican/pelican/blob/686206161beb517d681c2cba59568c658e8576aa/pelican/tests/test_generators.py#L341). If I am not mistaken.

Thank you for all the help, thanks a ton for very very kind and supportive, Elegant team. :tada:

**Comment by talha131** [comment]
Thanks a lot @iranzo. Great job.
