### ISSUE TITLE
ico extension favicon didn't work

### ISSUE THREAD

**Issue by azzamsa** [Pelican-Elegant/elegant#253]
I don't why. But 'ico' extension didn't work for me. 'png' extension worked.

So I need to change this in `templates/_includes/favicon_links.html`

```
<link rel="shortcut icon" href="{{ SITEURL }}/theme/images/favicon.png" type="image/x-icon" type="image/png" />
```

PS: I also use png format for my old site

Related : https://github.com/Pelican-Elegant/elegant/issues/159

**Comment by talha131** [comment]
@azzamsa can you share the ico and png files so that I can try to reproduce the issue?

**Comment by azzamsa** [comment]
I've tried to change the code below to both `ico` and `png`, dunno, both of them worked now.

`<link rel="shortcut icon" href="{{ SITEURL }}/theme/images/favicon.png" type="image/x-icon" type="image/png" />`

I saw this log too:

when using `png` or `ico`

```
127.0.0.1 - - [06/Jul/2019 02:21:10] "GET /theme/css/style.min.css?8bdcf96a HTTP/1.1" 200 -
127.0.0.1 - - [06/Jul/2019 02:21:11] "GET /theme/images/favicon.ico HTTP/1.1" 200 -
```

```
127.0.0.1 - - [06/Jul/2019 02:18:31] "GET /theme/images/favicon.png HTTP/1.1" 200 -
```

These are the files if you want to try.

[favicon.tar.gz](https://github.com/Pelican-Elegant/elegant/files/3363803/favicon.tar.gz)

**Comment by talha131** [comment]
hmm, if it's working then let's close this issue. 

If someone comes up with similar issue then we will dig deeper.
