### ISSUE TITLE
Ease bing and google validations on search engines

### ISSUE THREAD

**Issue by iranzo** [Pelican-Elegant/elegant#255]
Both Google and Bing require tokens to be created, either via a file on disk, which can be done more or less easily or via a token in headers of page, like:

~~~html
<meta name="msvalidate.01" content="8ASDASDASDUF8235242F0" />
~~~

Would it make sense to create a config setting for it in pelican.conf that it's then used by the templates automatically?

**Comment by silverhook** [comment]
Can you provide a link to some documentation explaining why that is needed or what it does in practice?

My experience with blogging is that as long as the content is relevant enough, the post will get found. I never bothered with SEO.

**Comment by iranzo** [comment]
For many sites, it means that you 'claim' that site is yours, so that you can configure some settings for crawler, category of site, etc (and submit sitemaps).

Google has something similar in the 'search console'

Try: https://bing.com/webmaster and add a site it will require to 'verify' a site as yours and will ask either for a CNAME or a file or  a <meta> to be created in the main page it crawls

**Comment by iranzo** [comment]
So either we add a file with 'extra' files and define path, or set 'meta' in headers, instead of modifying, setting it via var makes it easier for end user

**Comment by silverhook** [comment]
Personally, I don’t have much interest in having SEO specific to certain search engines – even if the most commonly used.

That being said, if there is enough demand for it, we can certainly turn it into an option. So I am not voting either for or against it.

If there is not enough demand (or others are against it), we could also just extend our documentation on [customisation](https://pelican-elegant.github.io/how-to-customize-elegant) with these meta tags as an example.

**Comment by iranzo** [comment]
ACK!

**Comment by talha131** [comment]
@iranzo it would be a good addition, provided, we keep it optional.

Many users don't have much time to understand and learn the SEO basics. This addition will lower the barrier to some extent.

**Comment by iranzo** [comment]
I'll handle both in the same PR
