### ISSUE TITLE
Round search corner missing, making bar taller

### ISSUE THREAD

**Issue by iranzo** [Pelican-Elegant/elegant#260]
With fix for #258 , search field is bigger and lacks the rounded aspect:

![image](https://user-images.githubusercontent.com/312463/50864856-9e6c3780-13a3-11e9-9372-b328018f3964.png)

**Comment by iranzo** [comment]
vs previous aspect:

![image](https://user-images.githubusercontent.com/312463/50864913-c22f7d80-13a3-11e9-8757-5f409b4b4f6a.png)

**Comment by iranzo** [comment]
From my little css understanding, there's now a crash between previous bootstrap selector and tipue selector.

We cannot change ID as it's used for the search functionality, so we do need to 'patch' the style to use the rouded one in boostrap vs the square one in tipue

**Comment by talha131** [comment]
@iranzo are you going to submit the patch or I should look into it?

**Comment by iranzo** [comment]
@talha131 if you can do it, better, I'm too new here in css world, so I was doing so far trial-error

Original

![image](https://user-images.githubusercontent.com/312463/50935000-ba86dc00-146a-11e9-984f-5a4854cbff13.png)


New tipue:

![image](https://user-images.githubusercontent.com/312463/50935012-ca9ebb80-146a-11e9-8430-67d329cc65b4.png)


So in new tipue, without changes in our form it loads the one from tipue and fails (round default) vs 'bootstrap' rounded one

**Comment by iranzo** [comment]
Some of the values overriden via browser that makes it look like it was:

![image](https://user-images.githubusercontent.com/312463/50935126-4ac52100-146b-11e9-9b54-cb3f3b159a46.png)


remove height, change border-radious, etc

**Comment by iranzo** [comment]
![image](https://user-images.githubusercontent.com/312463/50935141-5add0080-146b-11e9-8a46-15e650b6568c.png)

**Comment by talha131** [comment]
Thank you @iranzo for the pointer. I will submit PR for it by the weekend.

**Comment by iranzo** [comment]
Thanks!

**Comment by iranzo** [comment]
New aspect:

![image](https://user-images.githubusercontent.com/312463/50970542-f5782680-14e1-11e9-87be-2be6e4f739b3.png)



custom.css contents:
~~~css
/* Patch for TIPUE round box */

#tipue_search_input {
    margin-bottom: 0;
    padding: 4px 14px;
    font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
    font-size: 13px;
    font-weight: normal;
    line-height: 1;
    -webkit-border-radius: 15px;
    -moz-border-radius: 15px;
    border-radius: 15px;
    border: 2px;
    box-sizing: 0;
    height: 32px;
}

~~~

**Comment by iranzo** [comment]
If so, I can add the custom.css to the PR we do have for tipue and we're good to go until we do rewrite in 3.0

**Comment by iranzo** [comment]
Minimal changes and actual aspect:

![image](https://user-images.githubusercontent.com/312463/50970908-04aba400-14e3-11e9-9a75-2e5b99620bf2.png)



~~~css
/* Patch for TIPUE round box */

#tipue_search_input {
    -webkit-border-radius: 15px;
    -moz-border-radius: 15px;
    border-radius: 15px;
    line-height: 1;
    height: 32px;
}
~~~

**Comment by iranzo** [comment]
Updated on elegant.css in PR #259

**Comment by talha131** [comment]
Thank you @iranzo.

**Comment by iranzo** [comment]
Closed, now working properly ( <https://iranzo.github.io/> )  as an example

**Comment by talha131** [comment]
Is elegant responsible for this

![](https://i.imgur.com/OMKRVVX.png)

Or you are using a custom fork?

**Comment by talha131** [comment]
> Closed, now working properly ( iranzo.github.io ) as an example

Now it's fixed after https://github.com/Pelican-Elegant/elegant/commit/3650d68725a024d5fa9eba5b5c5d31f80eb4e161

Before

![](https://i.imgur.com/vdBOqSj.png)

After

![](https://i.imgur.com/f8t77PU.png)
