### ISSUE TITLE
Make labels prettier and easier to navigate

### ISSUE THREAD

**Issue by silverhook** [Pelican-Elegant/elegant#267]
Now that we’re gaining traction again, it would help with contributions to review or issue labels and select both the names and colours for them that would visually help everyone to navigate them easier.

inspiration:
https://help.github.com/articles/helping-new-contributors-find-your-project-with-labels/
http://blog.cornelius-schumacher.de/2019/01/beautiful-github-labels-with-terraform.html
(I’m not suggestiing TerraForm – it seems a bit overkill for us – but the ideas are good)

**Comment by iranzo** [comment]
+1

**Comment by talha131** [comment]
1. We have labels
1. Our colors are fine
1. Since Jan 2019, no one has complained or suggested anything about labels
1. We are not a big project to need a cli tool to manage labels
1. All team members can edit, add labels so they are free to improve labels
