### ISSUE TITLE
Question: Jinja template indentation

### ISSUE THREAD

**Issue by azzamsa** [Pelican-Elegant/elegant#271]
Hi

Anyone using Emacs [web-mode](https://github.com/fxbois/web-mode) here ?

I've some difficulties to work with jinja indentation. I've tried:

1) changing [indent-style](https://github.com/fxbois/web-mode/issues/669)
2) set [web-mode-set-engine](https://emacs.stackexchange.com/questions/23810/getting-proper-indentation-for-python-flask-templates)

Still I have [different](https://gist.github.com/azzamsa/90b3778ac8209596165d24be866b6b5d/revisions) indentation from you guys.

I don't think we need editorconfig, if we agree on 2/4 and tab/spaces.

**Comment by talha131** [comment]
If I remember correctly, I used vim for it. If you can wait for few days, I am going to try to add prettify support via git hook. See discussion [here](https://github.com/Pelican-Elegant/elegant/issues/191#issuecomment-453081060).

**Comment by azzamsa** [comment]
I just heard of pre-commit. I think it's nice to have one auto-format for our code. So we all share the same style

+1 for pre-commit. Btw, never used it before.

**Comment by talha131** [comment]
@azzamsa Unfortunately jinja-lint didn't work. 😞 

https://github.com/Pelican-Elegant/elegant/issues/191#issuecomment-462147591

You will have to do manual indentation.

**Comment by azzamsa** [comment]
As long as we have same indentation properties. it's ok.
