### ISSUE TITLE
Add "Proudly" in footer note

### ISSUE THREAD

**Issue by azzamsa** [Pelican-Elegant/elegant#272]
Anyone interested in adding "Proudly" in footer note. It would be awesome IMHO.

```diff
@@ -9,7 +9,7 @@
         {% if SITE_LICENSE %}
         <li class="elegant-license">{{ SITE_LICENSE }}</li>
         {% endif %}
-        <li class="elegant-power">Powered by <a href="http://getpelican.com/" title="Pelican Home Page">Pelican</a>. Theme: <a href="https://github.com/Pelican-Elegant/elegant/" title="Theme Elegant Home Page">Elegant</a></li>
+        <li class="elegant-power">Proudly powered by <a href="http://getpelican.com/" title="Pelican Home Page">Pelican</a> and <a href="https://github.com/Pelican-Elegant/elegant/" title="Theme Elegant Home Page">Elegant theme</a></li>
     </ul>
 </div>
 </footer>
```

![2019-01-16-07 19 13](https://user-images.githubusercontent.com/17734314/51218552-9aba5100-195f-11e9-9a75-cd1aa9b64b11.png)

If none, indeed I still can keep it my self ;)

**Comment by silverhook** [comment]
I don’t know. It may look odd to some (potential) users. Especially if we want to keep professional users or even institutions as part of our target group.

I don’t have strong feelings about this though.

**Comment by talha131** [comment]
I agree with @silverhook. Lets keep it minimal.
