### ISSUE TITLE
"Contents"  appears in article even with no TOC

### ISSUE THREAD

**Issue by codecachet** [Pelican-Elegant/elegant#278]
Template checks `{% if article.toc %}`. However, `article.toc` appears to be full of html.  In my case: `<div class="toc"> <ul></ul>  </div>`.

**Comment by talha131** [comment]
@codecachet Do you have extract_toc plugin?

Kindly share the source code of your blog so that we can reproduce it?

**Comment by codecachet** [comment]
I'll try to figure out what is wrong, and let you know. Thanks!

**Comment by talha131** [comment]
@codecachet yes please do report back so that we can fix the issue or update our documentation.

**Comment by iranzo** [comment]
@codecachet were you able to dig further? is this still relevant?

**Comment by codecachet** [comment]
I think the issue is the Table of Contents Markdown extension itself - as long as you have [TOC] in your Markdown, it will always return the `<ul>...</ul>`, even if there is nothing in the table of contents list, and the `<ul>` contains no `<li>`s.

**Comment by iranzo** [comment]
I was checking the extract_toc and it uses beautiful soup to extract it from the generated document, so the theme shows it if the article contains the [TOC]

**Comment by iranzo** [comment]
As a way forward, user should not add [TOC] or either we can hack the post generated code (dirty) to remove it if no TOC has been created (empty one)

I vote for 1 which is simpler and then add only '[TOC]' where intended

**Comment by talha131** [comment]
A better solution is to modify the `extract_toc` plugin to

1. Extract toc whether it is empty or not
1. Do not populate the `article.toc` field if the list is empty

**Comment by iranzo** [comment]
extract_toc should then get an issue to have it fixed there?

**Comment by talha131** [comment]
Yeah, an issue the pelican-plugins repository linking to this issue should
be enough to close this issue.

**Comment by talha131** [comment]
This issue should be fixed in extract_toc plugin.

**Comment by talha131** [comment]
@codecachet see https://github.com/getpelican/pelican-plugins/pull/1156
