### ISSUE TITLE
Update link at getpelican/pelican-themes to point to the latest release

### ISSUE THREAD

**Issue by silverhook** [Pelican-Elegant/elegant#281]
Currently https://github.com/getpelican/pelican-themes points to a 4-year-old release. We should let them know to point to the newest release – or better yet, directly to master, as we now treat that as a stable branch.

**Comment by iranzo** [comment]
https://github.com/getpelican/pelican-themes/issues/642

**Comment by iranzo** [comment]
Will be closed by https://github.com/getpelican/pelican-themes/pull/643

**Comment by iranzo** [comment]
> Will be closed by [getpelican/pelican-themes#643](https://github.com/getpelican/pelican-themes/pull/643)

This is already merged in pelican, closing

**Comment by talha131** [comment]
Here's the issue. Whenever we do a release, we will have to update the pelican-themes repo. Because submodules track commits. We can't make submodules to always track the latest tag or master.

So what can we do here? Have a travis task to automatically open a PR? 

This is important because Pelican-Themes repository is one of the biggest source of Elegant discovery, or at least the first place new users look for a theme.

What can we do here?

**Comment by iranzo** [comment]
It should be pelican repo to automatically/periodically run git submodules update on their end....

**Comment by talha131** [comment]
Well we have little control on Pelican repo. Can we make a travis task for automatically opening the PR?

I have seen such bots for JS. They open PR if a dependency used in your project has a latest release.

Can we have such bot to open PR on their repo?

**Comment by iranzo** [comment]
I was checking PR for something at work and it's not 'easy' as it requires using 'hub' cli which requires authentication.

If we've some contact like Justin, we can reach, it would be great to add basic travis checks on their side and even consider creating a regular job to update submodules, I'll open issue to them too

**Comment by iranzo** [comment]
https://github.com/getpelican/pelican-themes/issues/651

**Comment by talha131** [comment]
Good job. Lets see what they have to say.

**Comment by iranzo** [comment]
thanks!

**Comment by talha131** [comment]
We have opened up PR in pelican themes repo. There isn't much we can do here.
