### ISSUE TITLE
Change subtitle style

### ISSUE THREAD

**Issue by talha131** [Pelican-Elegant/elegant#284]
Current

![](https://i.imgur.com/WKBcUVr.png)

![](https://i.imgur.com/NHoC2yd.png)

1. Push it to new line
1. Make it italic

![](https://i.imgur.com/QX8fgen.png)
![](https://i.imgur.com/JOWGSpy.png)

Feedback welcome.

**Comment by iranzo** [comment]
Like it

**Comment by silverhook** [comment]
I like it as well :+1:

**Comment by talha131** [comment]
7ca7331c0c
