### ISSUE TITLE
Add live reload support

### ISSUE THREAD

**Issue by talha131** [Pelican-Elegant/elegant#285]
When a markdown is edited or theme source code is edited, we want to reload all the pages that are affected by the edit and already open in the browser in to reload.

1. If markdown of article `example.md` is edited and it is already open in the browser, then reload the page automatically
1. Reload all the pages if elegant theme source code (including CSS) is edited.

We will have to rerun the pelican command (like `make devserver`).

Not sure if theme can handle the reload. This feature may have to be added in the pelican itself.

**Comment by iranzo** [comment]
I think that this fall's in pelican area like devserver nor the theme. Even
if theme changes, pelican already rebuilds

**Comment by talha131** [comment]
You are right. 

Last time I used live reload, user had to add a small JS snippet in the HTML. So we will have to look if theme has to insert that JS snippet and pelican will take care of the rest. Or if pelican can do end to end integration.

Lets see.

**Comment by iranzo** [comment]
Theme can add a live reload script by reasking the server for changes to the file and then triggering it, however as pelican is  a static blog generator, once the markdown has been created and pushed, it should not do this as it will just 'overload' remote server rechecking for the same file right?

**Comment by silverhook** [comment]
I share @iranzo’s concern, especially on smaller self-hosted servers this could be annoying.

**Comment by talha131** [comment]
Live reload is supposed to happen only when you are running dev version.

`make devserver` already notices changes in the file system and triggers a recompile of changed files.

All I am suggesting is that when this happens, if there is an already opened tab in the browser, it should be auto-reloaded.

Production version (like github pages etc) will not be affected by it at all.

# How it can be done?

Off the top of my head without going into too much details.

1. Add https://github.com/livereload/livereload-js to theme. Enclose it in dev or debug macro so that it does not get added in the production version of the generated html
1. Add live reload server https://github.com/lepture/python-livereload to pelican

We will go into further details (or close this issue and move to Pelican repository) when the dev starts.

**Comment by talha131** [comment]
Pelican has now support for livereload. See https://github.com/getpelican/pelican/pull/2526

When the new version of Pelican is released

* [ ]  Move from `Makefile` to `tasks.py`
* [ ]  Add invoke and livereload to requirements
* [ ]  Add a short article on this feature to help documentation writers
* [ ]  To convert, `sync-plugins` task, see [invoke docs - Running Shell Commands](http://docs.pyinvoke.org/en/1.2/getting-started.html#running-shell-commands)

**Comment by jackdewinter** [comment]
Is this ready for documentation?
