### ISSUE TITLE
What do we have for picture galleries?

### ISSUE THREAD

**Issue by iranzo** [Pelican-Elegant/elegant#293]
I found https://github.com/getpelican/pelican-plugins/tree/master/photos 

And was wondering what do we have in Pelican for this, is there anything I've missed?

Thanks,
Pablo

**Comment by talha131** [comment]
No, we have nothing for it. Yet!

**Comment by iranzo** [comment]
Based in your experience, what would be good to add?

**Comment by iranzo** [comment]
![image](https://user-images.githubusercontent.com/312463/59153286-25f2cb00-8a56-11e9-9020-469d20f5f401.png)

**Comment by iranzo** [comment]
Simple attempt, pics 'link' to full size image, no other modifications on https://github.com/getpelican/pelican-plugins/tree/master/photos but adding extra plugin, dependencies on requirements and define header to article

~~~
---
author: Pablo Iranzo Gómez (pablo.iranzo@gmail.com)
title: Lego mini MOC adaptation
tags: lego, moc
layout: post
date: 2019-06-09 01:16:14 +0200
comments: true
category: blog
description:
gallery: {filename}gallery-source/minicooper
---

Based on the Lego MOC <https://rebrickable.com/mocs/MOC-24636/Keep%20On%20Bricking/75894-mini-transporter/> which I was unable to pay instructions for (Paypal complained), I tried to make my own based on the pictures appearing there, adding some more options like sizing cabin for allowing a minifigure to `drive`, plus some other alternatives for the front facing engine area and better holding of the rear wheels area.

Hope you like it!

~~~

**Comment by iranzo** [comment]
Want me to PR it ? @talha131 @silverhook ?

**Comment by iranzo** [comment]
Submitted the PR just for the thumbnail listing, if OK, I'll also add DOC on how to set it up before final merge (or create a new issue for tracking the doc need)

**Comment by talha131** [comment]
@iranzo If there is nothing left in this issue then please close it. Otherwise please mention what needs to be done here.

**Comment by iranzo** [comment]
Closing!
