### ISSUE TITLE
Update articles instructing to use MD_EXTENSIONS to MARKDOWN

### ISSUE THREAD

**Issue by iranzo** [Pelican-Elegant/elegant#301]
Articles like 'toc' instruct to use MD_EXTENSIONS and should be updated to MARKDOWN setting as per:

https://blog.getpelican.com/pelican-3.7-released.html

**Comment by jackdewinter** [comment]
PR submitted to address this issue.

https://github.com/Pelican-Elegant/elegant/pull/438

**Comment by talha131** [comment]
Closed via https://github.com/Pelican-Elegant/elegant/pull/441
