### ISSUE TITLE
Document post_stats

### ISSUE THREAD

**Issue by iranzo** [Pelican-Elegant/elegant#302]
Document https://github.com/Pelican-Elegant/elegant/pull/268

**Comment by azzamsa** [comment]
Any suggestion where to put the file here https://github.com/Pelican-Elegant/elegant/tree/master/documentation/content ? Should it in "Analytics" ?

**Comment by iranzo** [comment]
@talha131 , suggestions?

**Comment by talha131** [comment]
Supported Plugins

**Comment by talha131** [comment]
@azzamsa any update on it?

Our new member @jackdewinter has taken up documentation tasks. Let me know how you feel if I  assign this task to @jackdewinter. If you already have a draft then please share it with us.

----

@jackdewinter 

> From what I am reading there, this is a net new article, correct?  Would I be correct that adding post_stats to plugins is the only required step?

1. Yes a new article.
1. Yes adding `post_Stats` plugin is the only required step.
1. Necessary detail to add is `READING_TIME_LOWER_LIMIT`

Have a look at code

1. https://github.com/Pelican-Elegant/elegant/blob/master/templates/_includes/post_stats.html
1. https://github.com/Pelican-Elegant/elegant/blob/master/templates/_includes/_defaults.html#L148-L154

But before you write, lets wait for @azzamsa to get back to us.

**Comment by azzamsa** [comment]
When I will work on this, you [recommend me](https://github.com/Pelican-Elegant/elegant/issues/303#issuecomment-508718884) to better take the 'code' side. So I step back and (thought) that this already handled by Jackdewinter.

**Comment by talha131** [comment]
My apologies. Our earlier conversation slipped from my mind.

**Comment by jackdewinter** [comment]
Just submitted a PR for this.  https://github.com/Pelican-Elegant/elegant/pull/448
