### ISSUE TITLE
Add Release Notes of all previous releases

### ISSUE THREAD

**Issue by silverhook** [Pelican-Elegant/elegant#306]
To make sure our documentation is complete, it would be nice to write short release notes posts for previous releases as well.

It should be enough to just copy-paste the relevant lines from https://github.com/Pelican-Elegant/elegant/blob/master/CHANGELOG.md

Just make sure the category is right: `Category: Release notes` and that the article date is the date of when the [release happened](https://github.com/Pelican-Elegant/elegant/releases).

This is low priority, but also easy to do. So a great first issue for someone new wanting to help out.

**Comment by talha131** [comment]
I have done as best as I could. See 02a83e71e1f67e053448d42a6f551e1ae333ec51

From here onwards, changelog is automatically generated so this won't be an issue any longer.

**Comment by silverhook** [comment]
Great work! Thanks
