### ISSUE TITLE
Add article and example of series plugin

### ISSUE THREAD

**Issue by talha131** [Pelican-Elegant/elegant#308]
We have an article on using multi-part plugin. But the plugin has been deprecated.

https://pelican-elegant.github.io/how-to-use-multi-part-plugin

Now we need,

1. A new article on series plugin (it can cannibalize the multi-part article)
1. Few example articles that use series plugin (Text can be just lorem ispum)
1. Mark multipart plugin article as deprecated. Do not delete it. But show a warning box in the top that mentions deprecation of the plugin. Point it to new article.

We can take advantage of admonition in markdown and reST.

Markdown admonition are here

https://python-markdown.github.io/extensions/admonition/

**Comment by knz** [comment]
This was fixed by  #462 - the doc is there now.
