### ISSUE TITLE
Add page to encourage visitors to contribute

### ISSUE THREAD

**Issue by talha131** [Pelican-Elegant/elegant#309]
1. Add a page
1. Show it in the top menu bar

Content needs to be about

1. Please contribute, even if a little
1. If you can't code then help in documentation
1. Please, please contribute.
1. Please, please contribute.
1. Please, please contribute.

You get the idea.

**Comment by iranzo** [comment]
https://pelican-elegant.github.io/contribute is already live, so I think we can close this.
