### ISSUE TITLE
Add FAQ: Https and styling gone

### ISSUE THREAD

**Issue by silverhook** [Pelican-Elegant/elegant#310]
Q: If I use https my page looks funny – there seems to be no style at all!

A: Make sure you have your URL in the `SITEURL` with http**s**.

Perhaps explain the protocol-agnostic approach, its pros and its limitations.

https://github.com/Pelican-Elegant/elegant/pull/200#issuecomment-445733216

**Comment by iranzo** [comment]
I'm closing this one as we moved the templates to use // as a way to have them working on both http and https
