### ISSUE TITLE
Explain why links' CSS style uses mute colors and dashes 

### ISSUE THREAD

**Issue by talha131** [Pelican-Elegant/elegant#312]
For reference 
1. [Nicholas Carr's Experiments in delinkification](http://www.roughtype.com/?p=1378)
2. @tshepang [tweet](https://twitter.com/tshepang_dev/status/385916228314750976)

**Comment by talha131** [comment]
@jackdewinter 

> If I am reading the issue correctly, I should take the two articles in the first comment for the issue and explain why Elegant uses muted colors.  Is that correct?

Yes you are right. You will see that most websites make their links very prominent. Their links have blue colors and have underline style. For example,

![](https://i.imgur.com/gJJleD0.png)

Elegant wants to make the reading experience distraction free. Which is why we use muted styles for links. 

Mentioning Nicholas Carr in the article is important. In fact, if you can Google and add more references to research on the topic, that would be great.

**Comment by jackdewinter** [comment]
Working with Tahla to solidify the text, should have something in next week.

**Comment by jackdewinter** [comment]
Have a document completed and reviewed by Talha, waiting until weekend and new submit documentation.
