### ISSUE TITLE
Documentation: Pics alongside articles?

### ISSUE THREAD

**Issue by iranzo** [Pelican-Elegant/elegant#349]
Hi,
Based on a PR I faced issues with w3c online validator, long story short:

- My doc and associated image were in the same folder, but documentation folder contained a blank space that was not expanded (urlescaped) to %20 by pelican on generation.

I think that makes more sense to store images close to documents so in case an article has lot of them (like for example, 'gallery' articles) it's easier to see what's relevant for each one instead of having the files hanging around in other places.

This, is at the moment a problem until https://github.com/getpelican/pelican/issues/2581 gets solved or workadounded.

Alternatively we can:
- keep putting images in /images
- rename folders in documentation to remove the space

Feelings about?

**Comment by talha131** [comment]
> rename folders in documentation to remove the space

No.

> keep putting images in /images

How about creating folders inside images if an article has lots of images?

I don't think this issue is related to Elegant. Pelican should handle this issue.

**Comment by iranzo** [comment]
Yes, I agree this should be on Pelican, my approach was to 'avoid it' or 'mitigate' in the meanwhile

**Comment by talha131** [comment]
@iranzo reopen this issue if you think there is something that needs to be done.

---

BTW, I just tried following and I didn't get any error

```
![example or Pablo]({static}./blah blah/Beautiful loft in the winter.jpg)
```

Both folder and file name has spaces in it.
