### ISSUE TITLE
Add author support to the project documentation site

### ISSUE THREAD

**Issue by talha131** [Pelican-Elegant/elegant#360]
We have support for authors since #185. We need to use it for our documentation site.

I hope this will encourage contributors to write more articles, as it will offer them a venue for exposure.

# Needs to be decided

Quite often more than one person touches the article. Like one adds it and other people do spell and grammar fixes. How should be expose those contributors?

**Comment by iranzo** [comment]
We can generate an automated file content with both git logs for authors and 'hardcoded' list

**Comment by talha131** [comment]
@iranzo @silverhook 

I have added it. Now,

1. @iranzo you need to write your blurb.
2. @silverhook there are some articles that I think you wrote but it does not mention so. Please go through the articles you wrote and fill authors.

I have used `authors` metadata because most articles have been edited by more than one person.

**Comment by talha131** [comment]
@AWegnerGitHub  if I remember correctly, you too wrote few articles. Please define authors field for the articles that you wrote, your author blurb and then open PR.

**Comment by iranzo** [comment]
I've checked with latest 'next' on my blog and set the blurb on my pelicanconf.py, where should it be PR here? against which file?

Thanks!

**Comment by talha131** [comment]
@iranzo what's so confusing?

1. create a new branch from next
1. edit `pelicanconf.py`
1. edit articles that you wrote but forgot to set `authors`
1. commit 
1. open PR.

Commit message would read
```
docs(update): set author information
```

Let me know what confused you. I have a feeling I haven't done a good job of explaining the new build and release process.

**Comment by iranzo** [comment]
Hi, yes, it is clear, my doubt was about seeing no Author blurb there and
then that confused me if it was outsorced to other files.

Thanks,
Pablo
-- 

Pablo Iranzo Gómez

GnuPG: 0x5BD8E1E4
Web: https://iranzo.github.io  ||  https://citellus.org

**Comment by talha131** [comment]
> my doubt was about seeing no Author blurb there and then that confused me if it was outsorced to other files.

Well it's present. See for example 

![](https://i.imgur.com/oarjwFh.png)

See the code here

https://github.com/Pelican-Elegant/elegant/blob/next/documentation/pelicanconf.py#L155-L164

https://next.elegant.oncrashreboot.com/unique-home-page-features

**Comment by talha131** [comment]
@azzamsa please add yourself to `AUTHORS` dictionary and set `authors` field for the articles that you have written.

**Comment by silverhook** [comment]
@talha131 I thought I’ve done what was needed, but it seems I pushed to master by mistake. Sorry, it’s been a while :/

**Comment by talha131** [comment]
It's alright. I have removed those commits.

Please us PR for any sort of contribution. I can't stress it enough.

**Comment by silverhook** [comment]
Thanks. Sorry again. I’ll try to find the contribution guide again and follow it.

**Comment by talha131** [comment]
For now here is a short summary.

1. Create a fork
2. Open PR against next branch
3. use angular commit style
https://github.com/angular/angular.js/blob/master/DEVELOPERS.md#-git-commit-guidelines
4. NO need to update change log
