### ISSUE TITLE
Gravatar hovercards ?

### ISSUE THREAD

**Issue by iranzo** [Pelican-Elegant/elegant#362]
I found http://en.gravatar.com/support/profile-hovercards/ while checking for something else, something we want to add?

**Comment by talha131** [comment]
Our author field is much better than this. Don't you think? See #185 

Pelican even has option of creating author pages.

What we can do is to fetch avatar from gravatar and show it beside author. We will probably have to make a plugin first.

**Comment by iranzo** [comment]
If we want to fetch from gravatar it's really easy (https://es.gravatar.com/site/implement/images/ ): 

- [ ] define author email
- [ ] get md5 hash of email
- [ ] Request image from https://www.gravatar.com/avatar/HASH

Seems that https://github.com/getpelican/pelican-plugins/tree/master/gravatar does that for us providing that data to the templates

**Comment by talha131** [comment]
Good find. I have added it to the roadmap.

**Comment by silverhook** [comment]
How about <https://www.libravatar.org/>?

**Comment by talha131** [comment]
We can't use [gravatar plugin](https://github.com/getpelican/pelican-plugins/tree/master/gravatar). It won't work with our `authors` field.

What we can do here is 

* [ ]  add a `avatar` field to the `AUTHORS` dictionary
* [ ]  if it is defined then we show it along with the blurb

This way user can himself decide whether he wants to use gravatar, imgur or libravatar.

**Comment by iranzo** [comment]
Sounds good

**Comment by talha131** [comment]
cc92230769

**Comment by talha131** [comment]
Guys let me know (esp. @iranzo @azzamsa) what do you think of this dict keys 

```python
    "Talha Mansoor": {
        "url": "https://www.oncrashreboot.com/",
        "blurb": "is the creator and lead developer of Elegant theme.",
        "avatar": "/images/avatars/talha131.png",
    },
```

specifically do you think `avatar` key should be replaced with something better?

I will hold on the release for few days until I hear back from you.

**Comment by iranzo** [comment]
Can we provide 'avatar' as 'url' ? In that case we can use gravatar or whatever we want, we can either go to gravatar and copy url from there and one file less to add to repo as static one

for example, in my case: https://es.gravatar.com/userimage/47837087/6e8d2c6bc801fb6ea9cdad090b4f5814.jpg?size=200


BTW, what about the size for the image? any limitation or does the template fixes it? (Seems 32x32 right? )

thanks

**Comment by talha131** [comment]
Yes, you can give any url, gravatar or imgur or whatever.

I have fixed size to 32x32. Least distractive.

**Comment by iranzo** [comment]
+1 from me to merge then :)

**Comment by azzamsa** [comment]
Looks good tp me. Github use the same thing except it has `gravatar_id`

```
"avatar_url": "https://github.com/images/error/octocat_happy.gif",
"gravatar_id": "",
```

**Comment by talha131** [comment]
Cool. Then we are going to stay with `avatar` key.
