### ISSUE TITLE
Automate the release process

### ISSUE THREAD

**Issue by talha131** [Pelican-Elegant/elegant#369]
Of all the available tools, this one is the most popular.

https://github.com/semantic-release/semantic-release

It requires writing commits [in a specific format](https://github.com/angular/angular.js/blob/master/DEVELOPERS.md#commits). (Alternatives also follow the same guidelines).

* [ ]  Try it out locally
* [ ]  If it works, then update the contribution rules to follow the commit conventions
* [ ]  Can we add checks to PR to ensure commits conform to the rules?
* [ ]  Add CI support so that whenever we merge to master a new version is released
* [ ]  Exclude documentation updates in the master branch, i.e., do not release a new version if only documentation has been updated

(This list is a WIP)

**Comment by talha131** [comment]
4fb3edee8d97795b427dd44c61f052bb12186e83

**Comment by ashwinvis** [comment]
Okay so this explains the rapid releases. Are we following [semver](semver.org) style (`major.minor.patch`)? Some of the most recent releases could have just been limited to a patch release, as they seem to contain bugfixes alone.

**Comment by talha131** [comment]
It depends on the commits. If we have `feat` commits then it's a minor release. If we have `fix`, then it's a patch release. If we have breaking change, then it's a major release.

Recent releases are mostly `feat` hence the minor release.

We don't control the versioning manually. It's all handled automatically. We just need to make sure our commits follow the convention.

Let me know if you have more questions.

**Comment by ashwinvis** [comment]
Thanks for the clarification! I should really study the development machinery that you guys have put together. Seems very modern.

**Comment by talha131** [comment]
I am writing help articles to describe it. That should help.
