### ISSUE TITLE
Disable google crawling of all domains except the master deploy domain

### ISSUE THREAD

**Issue by talha131** [Pelican-Elegant/elegant#374]
Our documentation deploys to two domains.

1. https://elegant.oncrashreboot.com (master branch)
1. https://next.elegant.oncrashreboot.com (next branch)

We want to Google to crawl only the first one.

**Comment by talha131** [comment]
@iranzo can you please look into this issue. You will have to configure the robots.txt file for it.

* [ ]  Is there a way to test that our configuration is working?
* [ ]  When we merge the branches, then `robots.txt` will be mostly likely overwritten. Can we avoid it?

**Comment by iranzo** [comment]
If we create a prod-robots.txt and a next-robots.txt and using travis we copy the one named like the branch being build to 'robots.txt' on final destination could work, does it fit this approach?

For testing, ask for domain/robots.txt and validate manually or with one of the services that appear on 'robots.txt validation' search results

**Comment by talha131** [comment]
We are on Netlify now. Travis is only used for testing the PR. We can't use it to copy files etc.

**Comment by iranzo** [comment]
Is there a way for netlify to behave diferently based on branch being built to accomplish similar behavior?

**Comment by talha131** [comment]
yeah, using environment variables. See https://github.com/Pelican-Elegant/elegant/blob/master/documentation/publishconf.py#L15-L32

**Comment by iranzo** [comment]
Then we can tweak the publishconf to do the file copy with python based on branch before rendering the website

**Comment by talha131** [comment]
Let's split this task. I will handle the master and next branch part. 

You please tackle the rest.

**Comment by talha131** [comment]
Ok, I have just tested a patch locally and it is working. I will open PR for it tomorrow.

Thanks for your help @iranzo

**Comment by talha131** [comment]
257d3e69e8d8816ff22343f879d5cfea4b9d1e9b
