### ISSUE TITLE
Add hosted on variabled 

### ISSUE THREAD

**Issue by talha131** [Pelican-Elegant/elegant#376]
* [ ]  add a new named tuple variable `HOSTED`
* [ ]  Keys are `text`, `link`
* [ ]  default values is empty
* [ ]  if both keys are present in the dictionary or just text key is present then add text `Hosted On: <a href={link}>{text}<a/>` in the footer. Right after "Theme: Elegant".
* [ ]  if link is not present then do not add link
* [ ]  if text is empty then do not append anything. 

Rationale: Netlify requirement for using their generous Open Source Plan is to mention them on the production site.

Other users may need this feature.

**Comment by talha131** [comment]
@iranzo  can you please add this feature?

**Comment by iranzo** [comment]
Define in pelicanconf.py:

~~~py
HOSTED = {"text": "Netlify",
          "link": "netlify.com"}
~~~

Modify footer template for containing something like:

~~~jinja
        {% if (('text' in HOSTED) and ('link' in HOSTED)) %}
        <li class="elegant-power">Hosted on <a href="{{ HOSTED['link'] }}">{{ HOSTED['text'] }}</a></li>
        {% endif %}
~~~

**Comment by talha131** [comment]
Thanks a lot. I will open PR for it tomorrow.

**Comment by talha131** [comment]
https://github.com/Pelican-Elegant/elegant/commit/9de2dab
