### ISSUE TITLE
Document on how to use gists

### ISSUE THREAD

**Issue by iranzo** [Pelican-Elegant/elegant#382]
There's #123  on gist addition based on RST, but nothing is documented on the webpage on markdown, etc

**Comment by iranzo** [comment]
https://github.com/streeter/pelican-gist ¿?

**Comment by iranzo** [comment]
@talha131 do we support gists in elegant or we require external plugin for it? that coul also clarify on #123 where it seems it should be supported out of the box. If the procedure is the <html> embed they make it's not really on elegant but we can work with the above plugin

**Comment by talha131** [comment]
No. We don't need any plugin for it. You can embed any thing, like YouTube video or gists.

That plugin only simplifies the syntax. Not sure if it's addition requires any changes in the theme.

**Comment by talha131** [comment]
Just tested it in a markdown file.

```
---
Title: Test
date: 2019-07-05 05:33
slug: test
---

## Blah

<script src="https://gist.github.com/talha131/6372388.js"></script>
````

It works out of the box. Nothing needs to be done.
