### ISSUE TITLE
Investigate plugin for galleries instead of storing images in website

### ISSUE THREAD

**Issue by iranzo** [Pelican-Elegant/elegant#385]
Check https://github.com/La0/pelican-flickr/tree/e1b6dddf2cd12aef4096d2b01e5af6e15d46683a

**Comment by talha131** [comment]
@iranzo can you please look into this issue?

If no one is willing to take this issue in near future then lets close this one.

**Comment by iranzo** [comment]
Yes, I have it on my todo to allow 'smaller' websites, thing is that it requires getting flicker ID, etc which makes it harder.

In telegram, instagram galleries are automatically shown with some specifics so wanted to investigate that too

![image](https://user-images.githubusercontent.com/312463/63260366-0ca1a280-c281-11e9-8324-b1514412354a.png)


Would be great to find some similar way to do that (and no require extra config like API id's, etc), so still under my radar :-)

**Comment by talha131** [comment]
Thank you @iranzo for updating us.

**Comment by iranzo** [comment]
Tried with liquid for both instagram and flickr and no luck, just one image is shown on the post (even if it works):
![image](https://user-images.githubusercontent.com/312463/73144675-77fd6500-40a8-11ea-978c-1309b67af73f.png)

**Comment by iranzo** [comment]
I did a hack with some javascript and I get this:

![image](https://user-images.githubusercontent.com/312463/73175876-71eca000-410b-11ea-9a8c-b660f22d73a5.png)


So I can display instagram galleries easily, without any api code, etc with just adding some code to athe article.html and a new 'yaml' preamble tag.

I'll pr to get feedback

**Comment by iranzo** [comment]
For checking PR: please do add to your yaml preamble:

```instagram: B6-6UjeqgA-```

And using the updated article.html it should work

**Comment by iranzo** [comment]
@talha131 here I'll need your help for tuning the css, as I just copied/pasted what I found to get it working.

Also, I had to add jquery when supposedly should be loaded from `base.html`.

Thanks for your help

**Comment by iranzo** [comment]
Instagram inclusion by ID is pretty 'useful', but we could also consider define a json of image data so that we can alternatively link url's in any website by just using that linked file

**Comment by talha131** [comment]
>  we could also consider define a json of image data so that we can alternatively link url's in any website by just using that linked file.

Can you please share an example or a dummy json to explain this feature?

**Comment by iranzo** [comment]
Check https://github.com/kubevirt/kubevirt.github.io/pull/450/files for an example (in this case the way it's implemented here it's different)

**Comment by talha131** [comment]
I see. We would need a plugin to read the JSON file. Secondly, I don't think users would go for it because it is manual and difficult to setup JSON.

**Comment by talha131** [comment]
I am closing this issue in favor of our ongoing discussion on https://github.com/Pelican-Elegant/elegant/pull/560

**Comment by iranzo** [comment]
> I see. We would need a plugin to read the JSON file. Secondly, I don't think users would go for it because it is manual and difficult to setup JSON.

In this case, the 'plugin' is just a javascript that does the processing/reading so it shoudln't be that 'hard' no need for plugins at pelican level

**Comment by talha131** [comment]
No we would need a plugin to get json from the metadata. Pelican metadata does not support JSON. User will have to write the JSON file somewhere else. Plugin will load the JSON file and pass it to the theme.

**Comment by iranzo** [comment]
My idea was to use javascript for that, it can issue ajax to get the json file and then parse. Each user would then need to write the json with the image data, etc

**Comment by talha131** [comment]
In which case, the user will have to mention the fine URL in the metadata.

Elegant will load the JSON and then render it. It's a good idea, but does not offer much utility over other existing methods.

I would wait for someone to request it specifically before we pour our resources into it.

**Comment by iranzo** [comment]
ok!

**Comment by iranzo** [comment]
About photoswipe: 'https://photoswipe.com/documentation/faq.html#image-size' Requires to know 'in advance' image dimensions, so additional preprocessing is needed (just FYI)

**Comment by talha131** [comment]
Responded here https://github.com/Pelican-Elegant/elegant/pull/567#issuecomment-580275770
