### ISSUE TITLE
The build error is not going away

### ISSUE THREAD

**Issue by talha131** [Pelican-Elegant/elegant#387]
@iranzo do you see this cross right beside the name

![](https://i.imgur.com/1Mpgh4k.png)

Although we pass all the tests, but this cross does not go away.

Any idea what's going on here? How can we fix it?

**Comment by iranzo** [comment]
Where's the url where you get it?

**Comment by talha131** [comment]
hmm, it must be an addon issue. Just opened the repo in a clean browser and this mark disappears.

So it's not a travis or github issue.

Thanks for your time.
