### ISSUE TITLE
Pelican 4.0.1 + Tipue Search Fails to Generate Search.html

### ISSUE THREAD

**Issue by jackdewinter** [Pelican-Elegant/elegant#392]
Recently installed and am using elegant.  

The only issue I cannot seem to fix is the search.html and the search box, and such I have temporarily disabled it.

Using Pelican 4.0.1, the latest tipue plugin and elegant theme, as of 29 Jun 2019.

Went through the file that should be there, and all of the js and css files are where they should be, included the tipuesearch_content.js.  When I press the search button, it states that the page "search.html" is not there.   

Went through documentation for tipue and elegant, and can't see anything that should be preventing "search.html" from being written.  I am not sure if it is a documentation issue or a bug.

Happy to debug and test on this side if I can get a primer on where to start!

**Comment by talha131** [comment]
What's is the value of `DIRECT_TEMPLATES`? For reference see [our configuration](https://github.com/Pelican-Elegant/elegant/blob/master/documentation/pelicanconf.py#L86).

If this does not help then please share the source code of your blog.

**Comment by iranzo** [comment]
@jackdewinter you can check https://iranzo.github.io that uses lastest pelican and latest tipue plugins, etc on each 'build' of the website try the search box and for example 'paella' once you check what @talha131 commented, let us know!

**Comment by jackdewinter** [comment]
Thanks for the pointer.  When I cut and pasted from the configuration page, it somehow pasted the configuration as

DIRECT_TEMPLATES = (('index', 'tags', 'categories','archives', 'search', '404'))

fixed it to

DIRECT_TEMPLATES = ('index', 'tags', 'categories','archives', 'search', '404')

and now working.   Does this happen often? Configuration issues I mean?  If so, would it be worth some kind of comment in the documentation? I had to search for that file, but having "this was tested against https://elegant.oncrashreboot.com/configuration-variables-and-metadata-list" would have helped early on.

And can I help with that?

**Comment by talha131** [comment]
We so desperately need someone to take over our documentation. It is 5 years old. We are updating it, albeit slowly.

You can view our soon to be release version of docs and features [here](https://next.elegant.oncrashreboot.com/). (Please ignore the SSL error for now).

> Does this happen often? Configuration issues I mean? 

Most of Elegant features work out of the box. But for some, user has to read the documentation and fix his configuration.

> And can I help with that?

As I said we are desperate. If you can write few help articles that would be of great help to us.

For example, 

1. an article on how to setup search
1. an article on enabling FreeLists support
1. review existing articles and simplify it
1. how to install Elegant (like if you are using pelican-themes repo then you need to update the elegant submodule regularly)
1. help article on where to start reading the documentation 

Let me know if you are interested. I will guide you with the process. 

(We have recently setup some automation which requires contributions to be made under some specific rules. I am adding docs for it but it's going to take a week or more)

**Comment by talha131** [comment]
@jackdewinter have a look at this article 

https://elegant.oncrashreboot.com/add-tipue-search

Let me know if it can be improved.

**Comment by jackdewinter** [comment]
Giving it a look... will have something later today.
