### ISSUE TITLE
Fix date for 2.1.0 release notes

### ISSUE THREAD

**Issue by silverhook** [Pelican-Elegant/elegant#410]
The following blog post in Documentation needs to have its date fixed from 2018 to 2019:

https://elegant.oncrashreboot.com/version-2-1-0-release-notes

Clearly 2.1.0 came _after_ 2.0.0 ;)

**Comment by talha131** [comment]
Already fixed. See next branch.

https://github.com/Pelican-Elegant/elegant/blob/next/documentation/content/Release%20Notes/release-notes-2.1.0.md

**Comment by silverhook** [comment]
Perfect, thanks :)
