### ISSUE TITLE
[BUG] FreeLists form is deprecated

### ISSUE THREAD

**Issue by talha131** [Pelican-Elegant/elegant#412]
## Mandatory Step

- [x] I am using latest production release of Elegant

## Description

**Describe the bug**

Using FreeLists subscription form does not work. Instead it redirects user to a new page which says the form has been deprecated.

**Screenshots**

![](https://i.imgur.com/nsGHuIf.png)

https://www.freelists.org/cgi-bin/subscription.cgi

**Comment by talha131** [comment]
@ashwinvis you added this feature in  2bbfb0ff9.

Let me know what can we do to fix it. New form has a Captcha field. 

Possible solutions

1. Update the form code
1. or Instead of form, have a link that takes user to the form hosted on FreeList website

**Comment by ashwinvis** [comment]
Thanks for checking. I wasn't aware of it. I don't think option 1 is feasible now [according to the docs](https://www.freelists.org/wiki/doku.php?id=subscribe_from_my_site):

> this process is deprecated and will be sunset and replaced with something else in the future. 

We can have something very simple like like:

```html
<form action=""https://www.freelists.org/list/{{ FREELISTS_NAME }}">
    <input type="submit" value="Subscribe" />
</form>
```

Ref: https://stackoverflow.com/questions/2906582/how-to-create-an-html-button-that-acts-like-a-link

**Comment by talha131** [comment]
Cool. Can you open a PR for it?
