### ISSUE TITLE
Tables should be more distinct 

### ISSUE THREAD

**Issue by silverhook** [Pelican-Elegant/elegant#440]
Tables in Pelican Elegant are very simple and un-elegant. Case in point:

```markdown
…the visual representation would be:

| | | | | | | | | | |   |
|----:|:----:|----:|:----:|----:|:----:|----:|:----:|----:|:----:|------|
|     |   M  |  | **_O_** |   |  **_N_** |   |  T |   |  Y |     |
|  0 |    |  **_1_** |         |  **_2_** |          |  **_3_** |    |  4 |    |  5   |
| -5 |    | **_-4_** |         | **_-3_** |          | **_-2_** |    | -1 |    | None |

As you can see, this logic works for both positive and negative numbers as well as mixing the two in sequences.
```
produces this:
![Screenshot_20190714_143843](https://user-images.githubusercontent.com/3227264/61183733-1a8e5300-a645-11e9-83b1-3b561227d1cc.png)
https://matija.suklje.name/understanding-how-python-counts

Perhaps adding alternating backgrounds for the fields would help here to make it more appealing and easier to read as table.

**Comment by iranzo** [comment]
I would suggest options to either use lines, alternate colours, etc not to force just one format.

BTW (off topic), some editors allow 'formatting' the visual 'code' representation so that it looks more 'similar' to final result:

![image](https://user-images.githubusercontent.com/312463/62270149-93f3b700-b435-11e9-8ab9-f29213c0a3e8.png)


It adds spaces, etc but seems easier to 'see'

**Comment by talha131** [comment]
> I would suggest options to either use lines, alternate colours, etc not to force just one format.

This is the style I am working on

![](https://i.imgur.com/SBFujfM.png)

Adding options is great but how would user specify which option to use in Markdown, unless  we create a Pelican plugin for this purpose?

I say we offer a sensible default that is good enough for most of the users.

> BTW (off topic), some editors allow 'formatting' the visual 'code' representation so that it looks more 'similar' to final result:

If you use prettier via Git hook, then it does this automatically for you.

https://elegant.oncrashreboot.com/use-pre-commit-git-hooks

**Comment by talha131** [comment]
Note that the in the image I provided,

1. Table is bordered
1. Alternating Rows have background color

**Comment by talha131** [comment]
Fixed

**Comment by ptkin** [comment]
Hi @silverhook , I met the same issue as you, i.e., there were no borders or background colors with the rendered tables. 

But I found that I was using an old version of the Elegant theme by mistake. The latest version is v4.0.0, while the version involved by the getpelican/pelican-themes repo is v3.0.0. So I remove the old version and reinstall the latest one, and now it works!

**Comment by talha131** [comment]
@ptkin may I know how you update the Elegant theme and how do you get to know about our new releases?

**Comment by ptkin** [comment]
**Updating themes**

I just remove the old version by `pelican-themes -r elegant`, clone the latest repo of Elegant, and reinstall it by `pelican-themes -i path/to/elegant`.

**Knowing about new releases**

I'm new to Pelican, so I'm looking for an "elegant" theme for myself today. And that's it, the Elegant theme! When I meet this problem, I guess there may be something mismatching, then I notice that the version of the theme in the getpelican/pelican-themes repo doesn't match the latest version, so I tried to update the theme and finally solve the problem smoothly. This theme is really nice, I like it and thank you very much.

**Comment by talha131** [comment]
@ptkin thank you for your response.

> Knowing about new releases

We have a newsletter that you can subscribe to, to get notification about new releases in your inbox.

See the email field in the sidebar.

https://elegant.oncrashreboot.com/version-4-0-0-release-notes
