### ISSUE TITLE
Show Amazon disclaimer if AMAZON_BESTAZON is defined

### ISSUE THREAD

**Issue by talha131** [Pelican-Elegant/elegant#442]
@iranzo currently we show Amazon affiliate link disclaimer if `AMAZON_ONELINK` is defined.

Shouldn't we also show this warning if `AMAZON_BESTAZON` is defined, regardless if `AMAZON_ONELINK` is defined or not. 

Because to my understanding `AMAZON_BESTAZON` will work even if `AMAZON_ONELINK` is not defined.

Let me know what you think.

**Comment by iranzo** [comment]
Yes on any of both cases

**Comment by talha131** [comment]
Can you please

1. Open a PR with the fix
1. Update the docs
