### ISSUE TITLE
Bring back contribution guide

### ISSUE THREAD

**Issue by silverhook** [Pelican-Elegant/elegant#449]
It seems we lost out contribution guide along the way.

`CONTRIBUTING.md` points to a bogus link: http://localhost:9000/categories.html#contributing-ref

And on our documentation/home page, I could not find anything useful.

- [ ] bring back the the contribution guides in `CONTRIBUTING.md` and/or the documentation page
- [ ] link to it on the landing page

**Comment by talha131** [comment]
It's a WIP. Related to #343 

> CONTRIBUTING.md points to a bogus link: http://localhost:9000/categories.html#contributing-ref

Good catch. Please open PR to fix it. `localhost` needs to be replaced with docs new home.
