### ISSUE TITLE
Add spell check guideline to the Contributing guideline

### ISSUE THREAD

**Issue by talha131** [Pelican-Elegant/elegant#463]
1. We use https://github.com/hcodes/yaspeller
1. If you want to test locally then do `yarn global add yaspeller`
1. To run from the root of the folder run `yaspeller --only-errors content/ *.md`
1. To ignore a section 
    ```
    <!-- yaspeller ignore:start -->
    <!-- yaspeller ignore:end -->
    ```
1. To ignore a line `<!-- yaspeller ignore -->`
1. To add words to the ignore list add it to `dictionary` array in `.yaspeller.json` file
1. If you add words in lower case like "talha" then "Talha" will automatically be ignored.
1. If you add "Talha" then "talha" will not be ignored

**Comment by jackdewinter** [comment]
Addressed by https://github.com/Pelican-Elegant/elegant/pull/477 .

Specifically the article ya-spell-check.md.
