### ISSUE TITLE
Add logo to included template files

### ISSUE THREAD

**Issue by AWegnerGitHub** [Pelican-Elegant/elegant#488]
With the discussion occurring in #237 (and more specifically [this comment](https://github.com/Pelican-Elegant/elegant/issues/237#issuecomment-519389771) ), the logo should be included with the theme in a way that is accessible to template files. 

This should be a static asset. Perhaps including the .png (or moving the entire `elegant-logo` directory) into a `static/images` directory makes sense to me. 

If we move the entire `elegant-logo` directory, instead of just copying the single png, we need to look for this path in documentation and update it too.

**Comment by iranzo** [comment]
+1 on moving into static/images

**Comment by talha131** [comment]
I have used svg for logo to reduce number of web requests. A separate png or svg file will result in one more web request. 

`elegant-logo` directory is for future contributors. In case they want to modify or animate the logo or something. It is better than keeping the logo files on my HDD. 

> the logo should be included with the theme in a way that is accessible to template files.

Why should template need to access logo? Logo is for Elegant documentation site only. Any other consumer like my blog, or yours is not going to use Elegant logo.

**Comment by AWegnerGitHub** [comment]
As we move to including structured data in the template, we need to accommodate requirements for the structured data. 

One of the requirements on [Articles](https://schema.org/Article) and [BlogPostings](https://schema.org/BlogPosting) is a [publisher](https://schema.org/publisher). Despite what schema.org says, `Person` is not a valid target type for a publisher according to Google.

![Person Publisher](https://user-images.githubusercontent.com/6462439/62890589-6813e380-bd09-11e9-8ee4-fe436543ec15.png)

We want to have valid data for Google. I argue that we do, so that we can take advantage of how Google uses structured data to display results. (Their introduction is available [here](https://developers.google.com/search/docs/guides/intro-structured-data))

In that case, we need to validate against what they expect using the [Structured Data testing tool](https://search.google.com/structured-data/testing-tool/u/0/). Using this, we need publisher to be an Organization. Organizations require a logo. 

![Organization Publisher](https://user-images.githubusercontent.com/6462439/62890877-fbe5af80-bd09-11e9-8263-5cacbd959aae.png)

We need a valid default in case users don't define such a logo. While I'm still early in the process of building #237, and haven't figured out *how* we'll configure all of this supporting data, I can build the templates needed to validate correctly. Once those are built, adding in user defined and/or default values should be much easier.

My proposal here is to use the Elegant logo as the default, if a user doesn't define a logo.

**Comment by talha131** [comment]
Thank you for writing is so great detail.

> We need a valid default in case users don't define such a logo. 

Let's say an email was a requirement of publisher type. What would you have done then? Would you have defined a default email address?

Though we are not a legal entity but still, a logo is used to represent an organization. To define the organization for the Elegant documentation site, we are surely going to use the logo present in the repository. But for any other site, including my home page, the onus is on the user to create and define his logo.

---

Moving the discussion to #237 to consolidate all points.
