### ISSUE TITLE
[Request] Add new social icon in the sidebar

### ISSUE THREAD

**Issue by JoshuaACasey** [Pelican-Elegant/elegant#494]
- Keybase
- Mastodon
- Twitch
- Spotify
- LastFM
- Goodreads
- Telegram
- Riot/Matrix
- Signal
- Wire

**Comment by talha131** [comment]
- [ ] Keybase
- [ ] Mastodon
- [ ] Twitch
- [ ] Spotify
- [ ] LastFM
- [ ] Goodreads
- [ ] Telegram
- [ ] Riot/Matrix
- [ ] Signal
- [ ] Wire

**Comment by talha131** [comment]
@jacnoc I have added 7 new icons. For the rest 3, I invite you to open PR.

**Comment by talha131** [comment]
Closing for lack interest.
