### ISSUE TITLE
<meta> tags on frontpage

### ISSUE THREAD

**Issue by iranzo** [Pelican-Elegant/elegant#505]
Should we fill the opengraph protocol tags also on header?

meta keywords could be filled with all articles in website tags

meta description to be the 'about' text for website

authors to be filled with all website authors?

**Comment by talha131** [comment]
@iranzo we should be using as many tags as possible. 

Let me know which tags we can use in the header and other sections which you have pointed out.

**Comment by iranzo** [comment]
<meta keyword>
<meta property="og:image" 
<meta keywords=

**Comment by talha131** [comment]
Have a look, please, and let me know what I am missing.

1. https://github.com/Pelican-Elegant/elegant/blob/master/templates/_includes/smo_metadata.html
2. https://github.com/Pelican-Elegant/elegant/blob/master/templates/article.html#L19

To my understanding, we already have what you suggested.

**Comment by talha131** [comment]
I see. Thanks a lot for your explanation.

In this case, we will have to define custom variables that the user can leverage.

Can you open up a PR for this?

**Comment by iranzo** [comment]
Of course, that was my idea :)
