### ISSUE TITLE
Math equations are not rendered properly after update Elegant[Help]

### ISSUE THREAD

**Issue by Okroshiashvili** [Pelican-Elegant/elegant#506]
## Mandatory Step

- [ ] I am using 4.0.0 release of Elegant

## Recommended Step

- [ ] I have attached link to my blog source code repository
[blog sourse](https://github.com/Okroshiashvili/Data-Science-Fabric)
- [ ] I have reproduced my pelican configuration files
[Here is configuration file](https://github.com/Okroshiashvili/Data-Science-Fabric/blob/master/pelicanconf.py)

## I need help with

After update Elegant theme some math equations are rendered properly some equations are not rendered at all.
![image](https://user-images.githubusercontent.com/20360326/64501021-bc8e8c80-d2d0-11e9-995a-d56020e753bb.png)

**Comment by iranzo** [comment]
Hi,
Which is the file that is having issues?
I was checking your blog source and it seems that the latest updated ones are Jupyter Notebooks.

What python version are you using ? 

Any changes in the render_math plugin (https://github.com/getpelican/pelican-plugins/tree/master/render_math) you're using? Which version ?

**Comment by Okroshiashvili** [comment]
[That file has an issue](https://dsfabric.org/advances-of-linear-algebra-with-python-part-ii)

I'm using Python 3.6.

With updating Elegant theme I also updated render_math plugin and the version should be 2.7.3 if I'm not mistaken.

What can I do to solve this problem?

**Comment by iranzo** [comment]
I've tried with your checkout of your repository and regular markdown with equations (it was a simple one) was rendered correctly.

For ipnb it required additional libraries like 'nbconvert' to be installed plus others but that's part of math_render plugin not of regular Pelican-Elegant theme, I'll continue my tests later

**Comment by Okroshiashvili** [comment]
Thanks, @iranzo. I also keep trying to find the solution.

As a side note, before Elegant update, everything worked perfectly. I think this new update broke something but don't know what.

**Comment by talha131** [comment]
Is this issue resolved?

**Comment by Okroshiashvili** [comment]
The issue still persist. I did not find time to work on the solution.

**Comment by iranzo** [comment]
> Is this issue resolved?

No still being checked, had little time for this this week

**Comment by talha131** [comment]
Thank you all for the updates.

@Okroshiashvili my apologies for not being able to address this issue. I am not familiar with Python Notebooks at all. Though I can tell you, we didn't alter math render related code at all in our recent releases. We did remove Font Awesome, but I don't think it would be the cause.

**Comment by iranzo** [comment]
I was thinking more along the lines of complexity, as the simple equation was rendered. I'll try to check tomorrow as I did setup the environment on the other computer but has been a bit difficult to set time aside for it

**Comment by Okroshiashvili** [comment]
I solved the problem. That was the cause of `TYPOGRIFY`. Disabling it solved the problem. We can close the issue. Thanks a lot for help.
