### ISSUE TITLE
Theme for code block and shrank the plot size

### ISSUE THREAD

**Issue by Okroshiashvili** [Pelican-Elegant/elegant#512]
## Mandatory Step

- [ ] I am using latest production release of Elegant

## I need help with

I need to change the code block theme on my blog site. The new code block theme seems a little bit blurry. Here is the pic 
![image](https://user-images.githubusercontent.com/20360326/65869081-b305bb00-e38a-11e9-8ce2-79ecf2f2d13f.png)

end most importantly, before I updated "Elegant" them to the 4.0.0 version, interactive plots made by "Plotly" was rendered correctly. I mean the sizes of the plot. Now it seems somehow shrank compared to the older version of an Elegant theme - version 2.5.0

![image](https://user-images.githubusercontent.com/20360326/65869259-260f3180-e38b-11e9-8bbb-58d4f0165751.png)

The plot has slide bar after Elegant update, which was not presented in the old version. I need to get rid of this slide bar below to the plot.

**Here is the [link](https://dsfabric.org/plotly-express) of the blog post te see**

**Comment by talha131** [comment]
We have not changed the code theme. I inspected the page and noticed some CSS rules in ploty-express are overriding the Elegant theme rules. When I disabled them, our Solarized theme returned. 

![](https://i.imgur.com/RCwTEfX.png)

You need to tweak CSS of plotly-express

> The plot has slide bar after Elegant update, which was not presented in the old version. I need to get rid of this slide bar below to the plot.

Can you please clarify what you mean by sidebar? Where?

**Comment by Okroshiashvili** [comment]
Sorry for unstructured question. I removed the plotly blog post and still the same code block theme for other posts.
[Here](https://dsfabric.org/taylor-series-expansion-with-python) you can check.

In side bar I mean this 
![image](https://user-images.githubusercontent.com/20360326/65872755-5e663e00-e392-11e9-822b-b0df38314259.png)

**Comment by talha131** [comment]
Let's focus on the code theme issue first.

In the link you shared, I notice the same thing. Elegant rules are overridden by some other rules.

![](https://i.imgur.com/fKvkvgv.png)

I am not sure where these rules are coming from.

My guess is that they are added by your Python notebook.

**Comment by talha131** [comment]
You have to figure out which part of the toolchain is adding these rules to the output.

**Comment by Okroshiashvili** [comment]
I will transit from Jupyter notebooks to Markdown and everything will be fine. I made some tests and with "Pweave" everything works as expected. [Here](https://dsfabric.org/test-post) the link

**Comment by talha131** [comment]
Cool. If we are done here, can you please close this issue?

**Comment by Okroshiashvili** [comment]
No more questions. Closing the issue.
