### ISSUE TITLE
[BUG] C# and C++ misbehave in the tags list

### ISSUE THREAD

**Issue by talha131** [Pelican-Elegant/elegant#516]
C# and C++ in tags are treated as one.

1. The tag count doubles
1. C++ does not appear in the tags list

https://www.oncrashreboot.com/iterate-over-an-array-and-remove-elements

![](https://i.imgur.com/c3CxlDe.png)

![](https://i.imgur.com/w8Zk6Jd.png)

**Comment by iranzo** [comment]
URL above doesnt' seem to work

**Comment by talha131** [comment]
About to publish it.

**Comment by talha131** [comment]
This is related to pelican. Elegant has nothing to do with this bug.

https://github.com/getpelican/pelican/pull/2658
