### ISSUE TITLE
Add applause button support

### ISSUE THREAD

**Issue by azzamsa** [Pelican-Elegant/elegant#532]
https://applause-button.com/

**Comment by talha131** [comment]
I tried it a week or two ago. Then it wasn't working reliably. I was thinking of using the Google Analytics event tracker to implement this feature.

Related to #522

**Comment by azzamsa** [comment]
@azzamsa don't you want to open the issue [there](https://github.com/ColinEberhardt/applause-button) ?

I've something like 66 visitors a day (in some occasion). It's very rare to find a visitor that leave a comments, and it's easier for them to just do clap/kudos.

**Comment by talha131** [comment]
Actually I didn't test it thoroughly or tried to reproduce the issue again. It could be a temporary issue or one my browser addons could be interfering with it. That's why I didn't open the issue there.

**Comment by azzamsa** [comment]
Do you have any suggestion where to add it :)

This is what I've tried.

modified   templates/article.html
```diff
@@ -142,7 +143,8 @@
             {{ freelists(article) }}
         </div>
         </section>
-</div>
+        <applause-button style="width: 58px; height: 58px;"/>
+    </div>
 </article>
 {% endblock content %}
```

modified   templates/base.html
```diff
<link rel="stylesheet" type="text/css" href="{{ SITEURL }}/theme/css/custom.css" media="screen">
+        <link rel="stylesheet" type="text/css" href="https://unpkg.com/applause-button/dist/applause-button.css" media="screen">
         {% endif %}
         {% endblock head_links %}
         {% include '_includes/favicon_links.html' %}
@@ -110,6 +111,7 @@
         {% endif %}
         <script src="//code.jquery.com/jquery.min.js"></script>
         <script src="//netdna.bootstrapcdn.com/twitter-bootstrap/2.3.2/js/bootstrap.min.js"></script>
+        <script src="//unpkg.com/applause-button/dist/applause-button.js"></script>
         <script>
             function validateForm(query)
             {
```

But the result looks so bad, I need to modify the css and learn where to put `<applause-button style="width: 58px; height: 58px;"/>` this line.

![image](https://user-images.githubusercontent.com/17734314/69932671-9870cf00-14fe-11ea-832f-ca03d7f7f2ab.png)

I checked that the green color comes from `inherit`

**Comment by talha131** [comment]
This should do

https://github.com/Pelican-Elegant/elegant/blob/8e633054c30a6f685c77a2ae54e17c9c6239802a/templates/article.html#L75

**Comment by azzamsa** [comment]
Would you like to give me a hint on what's going wrong?

I've tried to produce the MWE, and it's doing great.


![image](https://user-images.githubusercontent.com/17734314/69957294-f6200e00-1534-11ea-8e4e-76ce64125eb5.png)

But, in my blog:

![image](https://user-images.githubusercontent.com/17734314/69957350-164fcd00-1535-11ea-861d-10e4867942e1.png)

is it because the css variable name clashes?

**Comment by talha131** [comment]
My guess is that the CSS file for the applause button has not been added
correctly.
Try to see if `applause-button.css` is available in the production or not.

>

**Comment by azzamsa** [comment]
No, it's in my local.

I use CDN:

```diff
modified   templates/base.html
@@ -42,6 +42,8 @@
         <link rel="stylesheet" type="text/css" href="{{ SITEURL }}/theme/css/elegant.css" media="screen">
         <link rel="stylesheet" type="text/css" href="{{ SITEURL }}/theme/css/admonition.css" media="screen">
         <link rel="stylesheet" type="text/css" href="{{ SITEURL }}/theme/css/custom.css" media="screen">
+        <!-- <link rel="stylesheet" type="text/css" href="{{ SITEURL }}/theme/css/applause-button.css"> -->
+        <link rel="stylesheet" href="https://unpkg.com/applause-button@3.3.0/dist/applause-button.css" />
         {% endif %}
         {% endblock head_links %}
         {% include '_includes/favicon_links.html' %}
@@ -110,6 +112,8 @@
         {% endif %}
         <script src="//code.jquery.com/jquery.min.js"></script>
         <script src="//netdna.bootstrapcdn.com/twitter-bootstrap/2.3.2/js/bootstrap.min.js"></script>
+        <!-- <script src="//unpkg.com/applause-button/dist/applause-button.js"></script> -->
+        <script src="https://unpkg.com/applause-button@3.3.0/dist/applause-button.js"></script>
         <script>
             function validateForm(query)
             {

```

Am I missing something?

**Comment by talha131** [comment]
Seems fine. No idea what's going on here.

Perhaps, share the live version of the final output. That may help me zero in on the problem.

**Comment by azzamsa** [comment]
I'm afraid I can't do that, as I don't have something like 'staging' version of it.

I don't want my reader surprised by that clunky clap button while we're investigating it :(

I will dig more locally.

**Comment by talha131** [comment]
If you open a PR here, then netlify will automatically create a demo of it.

You can read about this feature here.

https://elegant.oncrashreboot.com/how-to-contribute#previewing-changes

But of course, for this, you will have to work on adding the button to the elegant directly, instead of adding it to your site only.

**Comment by azzamsa** [comment]
Wow, it work great in netlify preview:

![image](https://user-images.githubusercontent.com/17734314/70014543-afbac580-15ad-11ea-9856-065da96423b2.png)

also work great in localhost:

![image](https://user-images.githubusercontent.com/17734314/70014797-2f489480-15ae-11ea-9390-2ca79a65b205.png)

I don't have any idea why it didn't work in my local blog :)


If elegant want to support it. We need:
1) to adjust the location
2) is the claps button will always be in the bottom or following user scroll (like medium blog)

**Comment by talha131** [comment]
> to adjust the location

Yeah, that needs tweak. I will fix it once you resolve the issues I have pointed out in your PR.

> the claps button will always be in the bottom or following user scroll (like medium blog)

should be bottom. "Following user scroll" is distracting.
