### ISSUE TITLE
[Help]

### ISSUE THREAD

**Issue by GerBreOwn** [Pelican-Elegant/elegant#533]
## Mandatory Step

- [x ] I am using latest production release of Elegant

## Recommended Step

- [ ] I have attached link to my blog source code repository
- [ ] I have reproduced my pelican configuration files

## I need help with
Style of LINKS
**Describe your question**
When I create a LINK it shows up with very faint dots under it instead of a BLUE underline and BLUE text.  Is there a way to show this link like ALL others do?
Thanks.

**Comment by iranzo** [comment]
I would say it's part of the CSS:

https://github.com/Pelican-Elegant/elegant/blob/master/static/css/elegant.css#L192

**Comment by iranzo** [comment]
Check https://elegant.oncrashreboot.com/customize-style for customization to suit your needs

**Comment by talha131** [comment]
> When I create a LINK it shows up with very faint dots under it instead of a BLUE underline and BLUE text.

To understand the rationale, please see this post

https://elegant.oncrashreboot.com/look-and-feel

> Is there a way to show this link like ALL others do?

We hear you. The muted form of links is suitable for long-form articles. We have plans to adding an option to disable muted links on per article basis in the next release. See https://github.com/Pelican-Elegant/elegant/issues/519

**Comment by azzamsa** [comment]
@talha131 would you please to edit this issue title, so newcomers will find it

**Comment by azzamsa** [comment]
Help. I've the similar problem.

- I've tried to follow this guide: https://elegant.oncrashreboot.com/customize-style, but I can't have something like: ` border-bottom: thin dashed none`. What I can do is: ` border-bottom: thin dashed white`. But I can still see it, even though it's not that clear.

![image](https://user-images.githubusercontent.com/17734314/69898667-fa122b80-138e-11ea-8b72-bef335e95be1.png)


- This is my custom css: https://github.com/azzamsa/elegant/blob/myhack/static/css/custom.css#L111, https://github.com/azzamsa/elegant/blob/myhack/static/css/custom.css#L69

- this is my blog content: https://raw.githubusercontent.com/azzamsa/blog/source/content/pages/about.markdown

**Comment by talha131** [comment]
Ok. @azzamsa will fix. Looking into it.
