### ISSUE TITLE
[Help] 'Stay in Touch' button in the 'pages'

### ISSUE THREAD

**Issue by azzamsa** [Pelican-Elegant/elegant#534]
## Mandatory Step

- [X] I am using latest production release of Elegant

## Recommended Step

- [X] I have attached link to my blog source code repository
- [X] I have reproduced my pelican configuration files

## I need help with

Pelican omit everything in the pages: 'Published', 'Modified', 'Category'. But elegant still shows the 'Stay in Touch' button in 'pages'.

Is this behavior intended? Shouldn't the 'Stay in Touch' omitted in 'pages'?

Example: (Taken from Iranzo's Blog)

- pages

![image](https://user-images.githubusercontent.com/17734314/69896825-e8705a00-1375-11ea-89f8-b4b7ddc9bb38.png)

- article

![image](https://user-images.githubusercontent.com/17734314/69896831-f7efa300-1375-11ea-9630-1ef0737280d6.png)

Thank you

**Comment by talha131** [comment]
We should remove it. I will fix it today.
