### ISSUE TITLE
[Help] Explain utterancess identifier

### ISSUE THREAD

**Issue by azzamsa** [Pelican-Elegant/elegant#547]
## Mandatory Step

- [X] I am using latest production release of Elegant

## I need help with

@jackdewinter would you like to add explanation in [Comments — Enable Utterances ](https://elegant.oncrashreboot.com/enable-utterances-comments) or [Comments — Thread ID](https://elegant.oncrashreboot.com/comments-thread-id) explaining what [will be passed as](https://github.com/Pelican-Elegant/elegant/blob/0e7f5f8616c5eb6ce4bbba42601a6431f8750c65/templates/_includes/comments.html#L14) utterances identifier.

Thank you.

**Comment by azzamsa** [comment]
@talha131 why did we choose [to append `siteurl`](https://github.com/Pelican-Elegant/elegant/blob/0e7f5f8616c5eb6ce4bbba42601a6431f8750c65/templates/_includes/comments.html#L10) as article identifier to commenting system (disqus/utterances), isn't slug is already unique on its own?

**Comment by talha131** [comment]
> @talha131 <https://github.com/talha131> why did we choose to append
siteurl
<https://github.com/Pelican-Elegant/elegant/blob/0e7f5f8616c5eb6ce4bbba42601a6431f8750c65/templates/_includes/comments.html#L10>
as
article identifier to commenting system (disqus/utterances), isn't slug is
already unique on its own?

Not necessarily. Like we have two sites, elegant and next.elegant. They
have same slugs. Base URL is important to differentiate.

Also I think, (I do not have code in front of me rug right now), these
sites require complete URL.

**Comment by talha131** [comment]
> @talha131 why did we choose to append siteurl as article identifier to commenting system (disqus/utterances), isn't slug is already unique on its own?

Not necessarily. Like we have two sites, elegant and next.elegant. They
have same slugs. Base URL is important to differentiate.

Another reason is that official examples of all the comment systems, use a complete URL as the identifier. Elegant just does exactly the same.
