### ISSUE TITLE
[BUG] "AttributeError: 'str' object has no attribute 'slug'". 

### ISSUE THREAD

**Issue by GerBreOwn** [Pelican-Elegant/elegant#548]
## Mandatory Step

- [ X] I am using latest production release of Elegant

## Recommended Step

- [ ] I have attached link to my blog source code repository, so that developers can try to reproduce the issue at the end
- [ ] I can't my source code but I have linked my pelican configuration files to help developers reproduce the issue

## Description

**Describe the bug**
I just downloaded and installed the latest version of Elegant and have started getting the error "AttributeError: 'str' object has no attribute 'slug'". Previous to the upgrade it was working VERY GOOD.
**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS: [e.g. iOS] Linux Mint 19.2
- Browser [e.g. chrome, safari] firefox

**Smartphone (please complete the following information):**

**Additional context**

**Comment by iranzo** [comment]
Can you provide a copy of the source used to create the website? the 'slug' part looks like pelicanconf.py is not properly configured

for example mines include:
~~~py
CATEGORY_FEED_ATOM = 'feeds/{slug}.atom.xml'
CATEGORY_FEED_RSS = 'feeds/{slug}.rss'
AUTHOR_FEED_ATOM = 'feeds/{slug}.atom.xml'
AUTHOR_FEED_RSS = 'feeds/{slug}.rss'
TAG_FEED_ATOM = 'feeds/tag_{slug}.atom.xml'
TAG_FEED_RSS = 'feeds/tag_{slug}.rss'
FILENAME_METADATA = '(?P<date>\d{4}-\d{2}-\d{2})-(?P<slug>.*)'
ARTICLE_URL = 'blog/{date:%Y}/{date:%m}/{date:%d}/{slug}/'
ARTICLE_SAVE_AS = 'blog/{date:%Y}/{date:%m}/{date:%d}/{slug}/index.html'
ARTICLE_LANG_URL = 'blog/{date:%Y}/{date:%m}/{date:%d}/{slug}-{lang}/'
ARTICLE_LANG_SAVE_AS = 'blog/{date:%Y}/{date:%m}/{date:%d}/{slug}-{lang}/index.html'
CATEGORY_URL = 'blog/category/{slug}/'
CATEGORY_SAVE_AS = 'blog/category/{slug}/index.html'
TAG_URL = 'blog/tag/{slug}/'
TAG_SAVE_AS = 'blog/tag/{slug}/index.html'
PAGE_URL = '{slug}/'
PAGE_SAVE_AS = '{slug}/index.html'

~~~

**Comment by iranzo** [comment]
@GerBreOwn can you please update on the current status? was the proposed approach tested?

**Comment by GerBreOwn** [comment]
I thought I reported that the problem was fixed.  There was one line having to do with metadata (I think) but don't remember for sure what the line was.  It looks like I deleted the line instead of just commenting it out. Sorry I can't be more helpful and in the future if I find a problem will try to remember to not delete the problem code.  It had to do with the pelicanconf.py file.
