### ISSUE TITLE
Cannot customize date format with on article page

### ISSUE THREAD

**Issue by alxpettit** [Pelican-Elegant/elegant#552]
Since I've pinpointed the exact code that causes this, I will skip supplying debugging info.

The code `<time itemprop="dateCreated" datetime="{{ article.date.isoformat() }}">{{ article.date.strftime('%b') }} {{ day }} {{- article.date.strftime(', %Y') }}</time> ` on line 118 of `article.html` hardcodes the date format when displaying an article. I think this should be changed to allow the end user to customize this format via `pelicanconf.py`, e.g. by adding a `BRIEF_DATE_FORMAT` option. Thoughts?

**Comment by talha131** [comment]
I noticed that in all other places, we use `article.locale_date`.

Only inside, Published section, the date format is hard-coded. At the time of writing, it was a feature. 

But I understand some users would want to customize it.

I think, replacing 

```html
{{ article.date.strftime('%b') }} {{ day }} {{- article.date.strftime(', %Y') }}
```

with 

```
{{ article.locale_date }}
```

should be enough, and we do not need to add new variable.

**Comment by talha131** [comment]
@all-contributors please add @alxpettit for bug.
