### ISSUE TITLE
Navbar menu will not expand on search page

### ISSUE THREAD

**Issue by blairconrad** [Pelican-Elegant/elegant#557]
## Mandatory Step

- [x] I am using latest production release of Elegant
   Also reproduced with next (28bcb8592cf595761d96904b004df3f425259849) and on https://elegant.oncrashreboot.com/

## Recommended Step

**I didn't bother, since this repo contains the source that reproduces the problem**

~~- [ ] I have attached link to my blog source code repository, so that developers can try to reproduce the issue at the end~~
~~- [ ] I can't my source code but I have linked my pelican configuration files to help developers reproduce the issue~~

## Description

**Describe the bug**
After searching, the collapse navbar menu will not expand, denying access to categories, tags, further searches, etc. One must navigate to another page (e.g. home) to access the menu again.

**To Reproduce**
1. Navigate to https://elegant.oncrashreboot.com/ or the landing page of some other site built with a recent Pelican.
1. If mobile, ensure that you are  **not** requesting the desktop site
1. Ensure your browser is narrow enough to hide the navigation menubar entries, leaving only the collapsed menu:
    
    ![image](https://user-images.githubusercontent.com/3275797/73065907-abef4500-3e72-11ea-99cf-29eebff26558.png)

1. Expand the menu, which works fine, and search for some term
    ![image](https://user-images.githubusercontent.com/3275797/73066022-fb357580-3e72-11ea-8701-09526fd8d71f.png)

1. Note that on the search page, hovering over the menu changes its state:
    ![image](https://user-images.githubusercontent.com/3275797/73066168-4f405a00-3e73-11ea-82b6-f08b1bba7a54.png)
    ![image](https://user-images.githubusercontent.com/3275797/73066232-6ed78280-3e73-11ea-8e85-ca4859134fb7.png)

1. Clicking on the menu does not expand it.

**Expected behavior**

That the menu button would expand to show the menu items, even on the search page.

**Desktop (please complete the following information):**

- OS: Windows 10 Home 1903 build 18362.592.
- Browser: Chrome
- Browser Version 79.0.3945.117 (Official Build) (32-bit)

**Smartphone (please complete the following information):**

- Device: ASUS Zenfone 3
- OS: Android 8.0.0; ASUS_Z0123DC Build/OPR1.170623.026
- Browser: Chrome
- Version: 79.0.3945.116

**My wife's tablet**

- Device: iPad Pro
- OS: iOS 13.3
- Browser: Safari
- Browser Version: Whatever's latest. It's up to date as I type.

**A friend's smartphone**

- Device: iPhone of some sort. That's all I know.

----
I'm otherwise enjoying the theme. Thanks for it.

**Comment by iranzo** [comment]
Confirmed, just need to reduce browser window to get the 'responsive' theme with collapsed menu

**Comment by iranzo** [comment]
@blairconrad can you test https://5e2ae90841f44e0008e59e65--pelicanelegant.netlify.com/ to see if it works for you?

**Comment by blairconrad** [comment]
@iranzo, tested on Chrome Version 79.0.3945.88 (Official Build) (32-bit) (on Windows 7, alas) and works :100:.

Speedy response. Thanks!

**Comment by iranzo** [comment]
Great, let's then have @talha131 having a review on how I messed with the code to see if it's merged in master and next branches :-)

Thanks for confirming!

**Comment by talha131** [comment]
@all-contributors please add @blairconrad for bug.

**Comment by talha131** [comment]
@blairconrad great bug report. Much appreciated!
