### ISSUE TITLE
[BUG] "Write About Me" does not mention required LANDING_PAGE_TITLE

### ISSUE THREAD

**Issue by neirbowj** [Pelican-Elegant/elegant#561]
## Description

**Describe the bug**

The documentation does not mention that it is necessary to set `LANDING_PAGE_TITLE` before the landing page will be included.

**To Reproduce**

1. Set `THEME='elegant'`
2. Create a simple page with `slug` set to `landing-page-about-hidden` and `status` set to `hidden` containing "XYZZY"
3. Generate site
4. See that `index.html` does not contain "XYZZY"

**Expected behavior**

Documentation will specify all steps necessary to achieve desired outcome.

**Screenshots**

N/A

**Desktop (please complete the following information):**

N/A

**Smartphone (please complete the following information):**

N/A

**Additional context**

**Comment by talha131** [comment]
Thanks a lot @neirbowj for pointing it out.

@all-contributors please add @neirbowj for doc.
