### ISSUE TITLE
[BUG] Add Jinja-Ninja validation to templates

### ISSUE THREAD

**Issue by iranzo** [Pelican-Elegant/elegant#562]
**Describe the bug**

Use pip package jinjaninja to run jinja-ninja to detect recommendations to be applied on templates

It reports spaces ot left between `{{` and variable or between `{%` and next command, etc.

**Comment by iranzo** [comment]
templates/archives.html:21:35 Tags should have one (and only one) space `{{FEATURED_IMAGE}}`
templates/archives.html:22:36 Tags should have one (and only one) space `{{FEATURED_IMAGE}}`
templates/archives.html:39:28 Tags should have one (and only one) space `{{year }}"><a href="#{{year}}`
templates/archives.html:42:20 Tags should have one (and only one) space `{%if prevyear != year %}`
templates/archives.html:43:32 Tags should have one (and only one) space `{{year }}"><a href="#{{year}}`
templates/archives.html:61:20 Tags should have one (and only one) space `{%if article.subtitle %}`
templates/base.html:29:8 Tags should have one (and only one) space `{%if TWITTER_USERNAME %}`
templates/base.html:30:47 Tags should have one (and only one) space `{{TWITTER_USERNAME}}`
templates/categories.html:21:35 Tags should have one (and only one) space `{{FEATURED_IMAGE}}`
templates/categories.html:22:36 Tags should have one (and only one) space `{{FEATURED_IMAGE}}`
templates/categories.html:61:40 Tags should have one (and only one) space `{%if article.subtitle %}`
templates/_includes/applause_button.html:13:25 Tags should have one (and only one) space `{{identifier}}`
templates/_includes/_defaults.html:29:0 Tags should have one (and only one) space `{% if not EMAIL_FIELD_PLACEHOLDER  %}`
templates/_includes/_defaults.html:32:0 Tags should have one (and only one) space `{% set EMAIL_FIELD_PLACEHOLDER  = EMAIL_FIELD_PLACEHOLDER  %}`
templates/_includes/_defaults.html:36:0 Tags should have one (and only one) space `{% if not SUBSCRIBE_BUTTON_TITLE  %}`
templates/_includes/_defaults.html:39:0 Tags should have one (and only one) space `{% set SUBSCRIBE_BUTTON_TITLE  = SUBSCRIBE_BUTTON_TITLE  %}`
templates/_includes/_defaults.html:43:0 Tags should have one (and only one) space `{% if not RECENT_ARTICLES_COUNT  %}`
templates/_includes/_defaults.html:46:0 Tags should have one (and only one) space `{% set RECENT_ARTICLES_COUNT  = RECENT_ARTICLES_COUNT  %}`
templates/_includes/_defaults.html:197:0 Tags should have one (and only one) space `{%if not TAGS_URL %}`
templates/_includes/_defaults.html:203:0 Tags should have one (and only one) space `{%if not CATEGORIES_URL %}`
templates/_includes/_defaults.html:209:0 Tags should have one (and only one) space `{%if not ARCHIVES_URL %}`
templates/_includes/_defaults.html:215:0 Tags should have one (and only one) space `{%if not SEARCH_URL %}`
templates/_includes/favicon_links.html:1:0 Tags should have one (and only one) space `{%if USE_SHORTCUT_ICONS == True %}`
templates/_includes/article_author.html:13:21 Tags should have one (and only one) space `{{auth.avatar}} alt="{{author}} Avatar" title="{{author}}`
templates/_includes/related_posts.html:8:4 Tags should have one (and only one) space `{%if related_post.subtitle %}`
templates/_includes/series.html:0:0 Tags should have one (and only one) space `{%if article.series %}`
templates/_includes/series.html:1:4 Tags should have one (and only one) space `{%if SERIES_TITLE %}`
templates/_includes/series.html:10:16 Tags should have one (and only one) space `{%if part_article == article %} class="active-part"{% endif %}`
templates/_includes/series.html:11:12 Tags should have one (and only one) space `{%if part_article != article %}`
templates/_includes/series.html:12:21 Tags should have one (and only one) space `{{ SITEURL }}/{{ part_article.url }}" title="{{ part_article.title }}">Part {{article.series.all.index(part_article)+1}}`
templates/_includes/series.html:14:17 Tags should have one (and only one) space `{{article.series.index}}`
templates/_includes/footer.html:32:16 Tags should have one (and only one) space `{{HOSTED_ON.url}}`
templates/_includes/footer.html:33:12 Tags should have one (and only one) space `{{HOSTED_ON.name}}`
templates/_includes/footer.html:36:8 Tags should have one (and only one) space `{{HOSTED_ON.name}}`
templates/_includes/comments.html:17:0 Tags should have one (and only one) space `{% set intro = COMMENTS_INTRO  %}`
templates/_includes/comments.html:34:19 Tags should have one (and only one) space `{%if use_disqus %}`
templates/_includes/smo_metadata.html:1:67 Tags should have one (and only one) space `{%if article.subtitle %} - {{ article.subtitle|striptags|e }} {% endif %}`
templates/_includes/smo_metadata.html:3:41 Tags should have one (and only one) space `{{article.summary|striptags|e}}`
templates/_includes/smo_metadata.html:12:68 Tags should have one (and only one) space `{%if article.subtitle %} - {{ article.subtitle|striptags|e }} {% endif %}`
templates/_includes/smo_metadata.html:13:42 Tags should have one (and only one) space `{{article.summary|striptags|e}}`
templates/_includes/smo_metadata.html:15:35 Tags should have one (and only one) space `{{article.featured_image}}`
templates/_includes/smo_metadata.html:16:36 Tags should have one (and only one) space `{{article.featured_image}}`
templates/_includes/smo_metadata.html:20:35 Tags should have one (and only one) space `{{FEATURED_IMAGE}}`
templates/_includes/smo_metadata.html:21:36 Tags should have one (and only one) space `{{FEATURED_IMAGE}}`
templates/_includes/analytics.html:6:18 Tags should have one (and only one) space `{{GOOGLE_ANALYTICS}}`
templates/_includes/analytics.html:14:17 Tags should have one (and only one) space `{{HEAP_ANALYTICS}}`
templates/_includes/freelists.html:15:30 Tags should have one (and only one) space `{{SUBSCRIBE_BUTTON_TITLE}}`
templates/index.html:20:35 Tags should have one (and only one) space `{{FEATURED_IMAGE}}`
templates/index.html:21:36 Tags should have one (and only one) space `{{FEATURED_IMAGE}}`
templates/index.html:24:41 Tags should have one (and only one) space `{{SITE_DESCRIPTION|e}}`
templates/index.html:25:42 Tags should have one (and only one) space `{{SITE_DESCRIPTION|e}}`
templates/index.html:44:31 Tags should have one (and only one) space `{{css_class}}`
templates/index.html:55:20 Tags should have one (and only one) space `{{css_class}}`
templates/index.html:57:34 Tags should have one (and only one) space `{{landing_page.page.title}}`
templates/index.html:70:20 Tags should have one (and only one) space `{{css_class}}`
templates/index.html:80:12 Tags should have one (and only one) space `{%endfor %}`
templates/index.html:92:20 Tags should have one (and only one) space `{{css_class}}`
templates/index.html:102:20 Tags should have one (and only one) space `{%if article.subtitle %}`
templates/index.html:116:23 Tags should have one (and only one) space `{{article.summary}}`
templates/page.html:3:29 Tags should have one (and only one) space `{%if page.subtitle %} - {{ page.subtitle|striptags|e }} {% endif %}`
templates/page.html:26:65 Tags should have one (and only one) space `{%if page.subtitle %} <small> {{ page.subtitle }} </small> {% endif %}`
templates/search.html:21:35 Tags should have one (and only one) space `{{FEATURED_IMAGE}}`
templates/search.html:22:36 Tags should have one (and only one) space `{{FEATURED_IMAGE}}`
templates/tags.html:21:35 Tags should have one (and only one) space `{{FEATURED_IMAGE}}`
templates/tags.html:22:36 Tags should have one (and only one) space `{{FEATURED_IMAGE}}`
templates/tags.html:66:20 Tags should have one (and only one) space `{%if article.subtitle %}`

**Comment by talha131** [comment]
Great find @iranzo. It is not perfect though. It didn't point out `]}}`. Nonetheless I have added it.

@all-contributors please add @iranzo for tool.
