### ISSUE TITLE
the archive list does not format correctly with few articles per year

### ISSUE THREAD

**Issue by knz** [Pelican-Elegant/elegant#568]
## Mandatory Step

- [x] I am using latest production release of Elegant

## Description

**Describe the bug**

When there is only 1 article per year, the generated "Archives" page does not align the years properly:

![image](https://user-images.githubusercontent.com/642886/73567963-bd82af00-4467-11ea-9562-8d19a3fd8cff.png)

**To Reproduce**

- make a new site with just 3 articles spread over 3 different years
- generate, observe

**Expected behavior**
Each year title should clear from the previous section.

**Comment by talha131** [comment]
We had this issue and we have fixed it about a year ago. Can you please update your pip packages, specially Jinja.

**Comment by knz** [comment]
I have upgraded to Jinja2 2.10.3 but the issue persists

**Comment by knz** [comment]
(I have also upgraded the other packages)

**Comment by talha131** [comment]
Can you please share the source code of your blog, I will have to reproduce it at my end.

You can see our online demo does not have this issue

https://elegant.oncrashreboot.com/archives

This is our pip versions

```
beautifulsoup4==4.8.2
blinker==1.4
cssmin==0.2.0
ddt==1.2.2
docutils==0.16
feedgenerator==1.9
gitdb2==2.0.6
GitPython==3.0.5
html5validator==0.3.3
invoke==1.4.0
Jinja2==2.11.0
jinjaninja==0.1.2
livereload==2.6.1
Markdown==3.1.1
MarkupSafe==1.1.1
pelican==4.2.0
Pygments==2.5.2
python-dateutil==2.8.1
pytz==2019.3
six==1.14.0
smartypants==2.0.1
smmap2==2.0.5
soupsieve==1.9.5
tornado==6.0.3
typogrify==2.0.7
Unidecode==1.1.1
webassets==2.0
```

**Comment by knz** [comment]
Please double check the title of this issue: the problem exists when there is only 1 article per year. In your example site, you have at least 2 articles per year and then the display is correct.

The bug exists with only 1 article per year.

**Comment by talha131** [comment]
Right, and that's why source of your blog or some oter sample blog will save us time to reproduce the issue.

I will try to reproduce, but it may take some time.

**Comment by knz** [comment]
You can take the `elegant` repository, go to the `documentation/contents` then erase all the categories directories but keep 2 of them; then in each of the remaining 2 categories erase all files but 1. Then you will see the problem.

**Comment by talha131** [comment]
![](https://i.imgur.com/aXx6z1h.png)

**Comment by knz** [comment]
I found the fix, the following is missing in the CSS:

```
div.blog-archives h2 {
  clear: both;
}
```

The problem is that h2 (the year) is `float:left`.

If the layout of the last line before that has a smaller height than the previous year-h2, the new year-h2 will be positioned on the right of the previous one (left-aligned floats stack left to right).

Using `clear:both` ensures that the new year-h2 appears on a line of its own.

**Comment by knz** [comment]
This makes me understand that you can reproduce the problem by changing the font size for the year label (maybe even resizing the text size in the browser will exhibit the symptoms)

**Comment by talha131** [comment]
Thanks for the tip.
