### ISSUE TITLE
Code block should avoid auto-wrap

### ISSUE THREAD

**Issue by calfzhou** [Pelican-Elegant/elegant#58]
Shown as the following screenshot, the long-code-line wrapped, and won't align correctly with line numbers.

And if the line number is bigger than 9 (has more than one digits), it will wrap too! Which makes the code-block looks ugly.

![image](https://f.cloud.github.com/assets/3761553/1500708/191e4f28-487e-11e3-8440-9c55285ea6ee.png)

**Comment by rednafi** [comment]
Code blocks are still getting auto-wrapped like this:
![Screenshot from 2022-01-22 03-41-40](https://user-images.githubusercontent.com/30027932/150604857-6c018495-0b85-40b1-aa72-8a5d813f6a3b.png)

How can I get a scrollbar if the line is longer than a cutoff?
