### ISSUE TITLE
[BUG] Missing files referenced by CSS

### ISSUE THREAD

**Issue by iranzo** [Pelican-Elegant/elegant#587]
## Mandatory Step

- [x] I am using latest production release of Elegant

## Recommended Step

- [ ] I have attached link to my blog source code repository, so that developers can try to reproduce the issue at the end
- [ ] I can't my source code but I have linked my pelican configuration files to help developers reproduce the issue

## Description

**Describe the bug**

When running python package linkchecker against 'output' folder I get some errors like:

URL        `../img/glyphicons-halflings.png'
Parent URL file:///home/iranzo/DEVEL/private/www/output/theme/css/style.min.css, line 1, col 50402
Real URL   file:///home/iranzo/DEVEL/private/www/output/theme/img/glyphicons-halflings.png
Check time 0.002 seconds
Result     Error: URLError: <urlopen error [Errno 2] No such file or directory: '/home/iranzo/DEVEL/private/www/output/theme/img/glyphicons-halflings.png'>

URL        `../img/glyphicons-halflings.png'
Parent URL file:///home/iranzo/DEVEL/private/www/output/theme/css/style.min.css, line 1, col 50402
Real URL   file:///home/iranzo/DEVEL/private/www/output/theme/img/glyphicons-halflings.png
Check time 0.002 seconds
Result     Error: URLError: <urlopen error [Errno 2] No such file or directory: '/home/iranzo/DEVEL/private/www/output/theme/img/glyphicons-halflings.png'>

URL        `../img/glyphicons-halflings-white.png'
Parent URL file:///home/iranzo/DEVEL/private/www/output/theme/css/style.min.css, line 1, col 51192
Real URL   file:///home/iranzo/DEVEL/private/www/output/theme/img/glyphicons-halflings-white.png
Check time 0.000 seconds
Result     Error: URLError: <urlopen error [Errno 2] No such file or directory: '/home/iranzo/DEVEL/private/www/output/theme/img/glyphicons-halflings-white.png'>

URL        `../img/glyphicons-halflings-white.png'
Parent URL file:///home/iranzo/DEVEL/private/www/output/theme/css/style.min.css, line 1, col 51192
Real URL   file:///home/iranzo/DEVEL/private/www/output/theme/img/glyphicons-halflings-white.png
Check time 0.000 seconds
Result     Error: URLError: <urlopen error [Errno 2] No such file or directory: '/home/iranzo/DEVEL/private/www/output/theme/img/glyphicons-halflings-white.png'>
 8 threads active,   723 links queued,  707 links in 276 URLs checked, runtime 1 seconds

URL        `../img/glyphicons-halflings.png'
Parent URL file:///home/iranzo/DEVEL/private/www/output/theme/css/bootstrap.css, line 2143, col 24
Real URL   file:///home/iranzo/DEVEL/private/www/output/theme/img/glyphicons-halflings.png
Check time 0.002 seconds
Result     Error: URLError: <urlopen error [Errno 2] No such file or directory: '/home/iranzo/DEVEL/private/www/output/theme/img/glyphicons-halflings.png'>

URL        `../img/glyphicons-halflings-white.png'
Parent URL file:///home/iranzo/DEVEL/private/www/output/theme/css/bootstrap.css, line 2167, col 24
Real URL   file:///home/iranzo/DEVEL/private/www/output/theme/img/glyphicons-halflings-white.png
Check time 0.000 seconds
Result     Error: URLError: <urlopen error [Errno 2] No such file or directory: '/home/iranzo/DEVEL/private/www/output/theme/img/glyphicons-halflings-white.png'>

URL        `../img/glyphicons-halflings-white.png'
Parent URL file:///home/iranzo/DEVEL/private/www/output/theme/css/elegant.prod.9e9d5ce754.css, line 7, col 30074
Real URL   file:///home/iranzo/DEVEL/private/www/output/theme/img/glyphicons-halflings-white.png
Check time 0.000 seconds
Result     Error: URLError: <urlopen error [Errno 2] No such file or directory: '/home/iranzo/DEVEL/private/www/output/theme/img/glyphicons-halflings-white.png'>

URL        `../img/glyphicons-halflings.png'
Parent URL file:///home/iranzo/DEVEL/private/www/output/theme/css/elegant.prod.9e9d5ce754.css, line 7, col 29284
Real URL   file:///home/iranzo/DEVEL/private/www/output/theme/img/glyphicons-halflings.png
Check time 0.002 seconds
Result     Error: URLError: <urlopen error [Errno 2] No such file or directory: '/home/iranzo/DEVEL/private/www/output/theme/img/glyphicons-halflings.png'>
 9 threads active,   472 links queued, 5816 links in 1194 URLs checked, runtime 6 seconds

**To Reproduce**

**Expected behavior**
Files are referenced in latest pelican theme:

static/bootstrap/variables.less:@iconSpritePath:          "../img/glyphicons-halflings.png";
 iranzo   next  ~  DEVEL  private  elegant  find|grep glyphicons-halflings.png

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by iranzo** [comment]
Same happens against documentaton/output folder in latest 'next' branch

**Comment by talha131** [comment]
That's fine. We now have bootstrap 2.3 in our the source code, which we are stripping and removing as we go along. In next few releases, we would completely remove the Bootstrap.

Bootstrap rerfrences these images but we do not use those CSS classes.

If you want to fix this issue then remove these lines 

https://github.com/Pelican-Elegant/elegant/blob/master/static/bootstrap/variables.less#L152-L157

and also remove the CSS classes or style rules that access this variable.
