### ISSUE TITLE
Documentation issue in Line Numbers in Code Snippets

### ISSUE THREAD

**Issue by silverhook** [Pelican-Elegant/elegant#598]
https://elegant.oncrashreboot.com/display-line-numbers-in-code-snippets#markdown

The shebang is written in the wrong order – should be `#!` (and not `!#`).

Also the line numbers in that example do not show, which is either a documentation issue or bug in the code.

**Comment by maneesha** [comment]
I found this theme and it's great! I just used it for my website and started browsing issues to contribute back to your work. I haven't had time to fiddle with a lot, but I thought I'd start with something quick and easy.  

#604 fixes the typo in the shebang.

**Comment by talha131** [comment]
Thank you @maneesha. We hope to see more contributions from you.

---
Close via https://github.com/Pelican-Elegant/elegant/pull/604
