### ISSUE TITLE
I really love this theme 

### ISSUE THREAD

**Issue by mraza007** [Pelican-Elegant/elegant#599]
I really love this theme and I might end up using this for my blog. My question is that does it include dark mode and Can I use this as a theme for my blog

**Comment by talha131** [comment]
> I really love this theme and I might end up using this for my blog.

Thank you for your appreciation.

> My question is that does it include dark mode 

For now, only code snippets have a dark theme. 

> Can I use this as a theme for my blog

Of course!

**Comment by mraza007** [comment]
Thanks for replying I will be migrating my blog to this 

I really loved the simplicity and the documentation of this theme
