### ISSUE TITLE
Do not let user hook utternaces comment on their blog to Elegant repo

### ISSUE THREAD

**Issue by talha131** [Pelican-Elegant/elegant#603]
See this issue https://github.com/Pelican-Elegant/elegant/issues/602

This user setup the blog and set the comment repository to Elegant. We ended up receiving his comments.

This means anyone can point his utterances script to Elegant for comments. This should not happen.

I am not sure how to fix this.

**Comment by ashwinschronicles** [comment]
Hi,
This was a misconfiguration on my side,  I apologize for the trouble.  Some kind of an authentication token from the utterance side can prevent such a mishap. Passing a plain text repo URL is a bad idea.

**Comment by talha131** [comment]
Thank you @ashwinschronicles

**Comment by jdanyow** [comment]
To prevent unauthorized comments in your repo, add an `utterances.json` file to the master branch with the list of origins permitted to post in this repo.

*utterances.json*
```json
{
  "origins": ["https://elegant.oncrashreboot.com"]
}
```

**Comment by talha131** [comment]
Thank you so much @jdanyow
