### ISSUE TITLE
[Help] series.html: part_article.title may need striptags

### ISSUE THREAD

**Issue by lzimd** [Pelican-Elegant/elegant#611]
With typogrify, acronym or capitalised word in article title creates `<span class ="caps">`.

reference: [Unsightliness with typogrify and titles that start with quote](https://github.com/getpelican/pelican/issues/1930)

**Comment by talha131** [comment]
Can you please open a PR to fix this issue?

**Comment by iranzo** [comment]
@lzimd can you confirm the issue will be fixed with your PR #617  ? 
Thanks
