### ISSUE TITLE
[BUG] utterances comment doesn't work

### ISSUE THREAD

**Issue by azzamsa** [Pelican-Elegant/elegant#612]
## Mandatory Step

- [X] I am using latest production release of Elegant

![2020-05-29_16-34](https://user-images.githubusercontent.com/17734314/83245050-6e0c7f80-a1ca-11ea-8a19-ac882957a5d3.png)

**Comment by talha131** [comment]
It is not a bug. It is most likely an issue in your configuration.

Are you by any chance testing utterances locally in Chrome? Try pushing it to your host and see the live version. It should work there.

Also try to load the same URL in Firefox.

**Comment by azzamsa** [comment]
It's a live version https://elegant.oncrashreboot.com/enable-utterances-comments, I can't comment there.

**Comment by talha131** [comment]
This is from Firefox Dev edition.

![](https://i.imgur.com/bedFFgC.png)

**Comment by talha131** [comment]
From Google chrome

![](https://i.imgur.com/cDgkcYX.png)

**Comment by azzamsa** [comment]
Oh my bad, I've tried several hours searching for a fix. 

Tried in chromium it works well. Maybe something wrong with my firefox dev.

**Comment by talha131** [comment]
Probably an addon is blocking it. Because it works in my copy of FFDev.

**Comment by azzamsa** [comment]
yes, I restarted ffdev without add-ons and it's work

**Comment by azzamsa** [comment]
![image](https://user-images.githubusercontent.com/17734314/84838845-b5698b80-b065-11ea-9ede-15b8d0851275.png)


In case anyone had the same issue.
