### ISSUE TITLE
How to use pygments.css?

### ISSUE THREAD

**Issue by ekw** [Pelican-Elegant/elegant#627]
## Mandatory Step

- [x] I am using latest production release of Elegant

## Recommended Step

- [ ] I have attached link to my blog source code repository
- [ ] I have reproduced my pelican configuration files

## I need help with

Once I've updated /static/css/pygments.css, how do I actually have it used?  

base.html always uses elegant.prod.XXXXX.css and custom.css 
https://github.com/Pelican-Elegant/elegant/blob/master/templates/base.html#L11-L12

When assets plugins is enabled, it also seems to just use elegant.prod.XXXXX.css
https://github.com/Pelican-Elegant/elegant/blob/master/templates/_includes/minify_css.html#L1-L5

How do I get an updated pygments.css to be used?  Where/how is pygments.css used at all?
Thanks for your help.

**Comment by talha131** [comment]
@ekw you need to put your pygments.css code into custom.css file. CSS rules written in the custom.css, override the elegant theme, including the code theme.

**Comment by ekw** [comment]
OK, thanks.  But for my own information, how/where is pygments.css currently used?  Is it somehow used to generate elegant.prod.XXXXX.css?

**Comment by talha131** [comment]
We use PostCSS to compile and minify the CSS files into elegant.prod.XXX.css.

https://github.com/Pelican-Elegant/elegant/blob/master/gulpfile.babel.js#L106-L124

The idea is to provide an optimized CSS to the user so that they don't have to install and configure assets plugin.
