### ISSUE TITLE
Search engine for the search box? 

### ISSUE THREAD

**Issue by dclong** [Pelican-Elegant/elegant#628]
Is it possible to configure elegant to use a search engine for the search box? 

[My current blog](http://www.legendu.net/) has been using Bing for the search box and it works well. Also, I have issues setting up tipue_search with elegant.

**Comment by talha131** [comment]
> My current blog has been using Bing for the search box and it works well.

We do not have the feature to change search engine. I never investigated how to integrate with third party search engines like Bing or Google. 

PR are welcome.

>  Also, I have issues setting up tipue_search with elegant.

We do not use tipue_search anymore. We use [LunrJS](https://elegant.oncrashreboot.com/add-search). Please give it a try again. Hopefully, you will find it better than tipue.

---
Feel free to open this issue if you have further questions.

**Comment by dclong** [comment]
Is the doc update-to-date? It mentions LunrJS but in the configuration it is tipue_search.

**Comment by talha131** [comment]
yeah, doc is up to date. LunrJS uses the JSON that is generated by the tipue_search plugin. What needs to be done here is

1. Update tipue_search plugin docs to clarify it can work with LunrJS
2. Take more advantage of LunrJS features

**Comment by dclong** [comment]
I got the following error. Do I need to have a folder `plugins` to have the tipue_search plugin inside it? I thought Pelican is moving away from this and encourages installing plugins as Python packages directly. 

ERROR: Cannot load plugin `tipue_search`
  | Cannot import plugin `tipue_search`

![image](https://user-images.githubusercontent.com/824507/89740687-cfa95f80-da3f-11ea-953a-9d5b9e73879e.png)

**Comment by iranzo** [comment]
I'm using a plugins folder and Have no issue with it at https://iranzo.github.io

**Comment by talha131** [comment]
> I thought Pelican is moving away from this and encourages installing plugins as Python packages directly.

I don't know about it. 

> Do I need to have a folder plugins to have the tipue_search plugin inside it?

That's how we use it in the Elegant documentation. @iranzo and my personal site also uses the plugins folder.

1. Clone the pelican-plugins repository. (You may want to do a shallow copy)
2. Set `PLUGIN_PATHS` to the repository path in your pelican configuration. ([Example](https://github.com/Pelican-Elegant/elegant/blob/master/documentation/pelicanconf.py#L28))
3. Add tipue_search to your `PLUGINS` array. ([Example](https://github.com/Pelican-Elegant/elegant/blob/master/documentation/pelicanconf.py#L38))

**Comment by dclong** [comment]
Some Pelican plugins (e.g., pelican-render-math) have already published Python packages. Maybe it's time to publish a Python package for `tipue_search` too so that it and elegant can work with the next version of Pelican?

**Comment by talha131** [comment]
I can't comment on it at the moment, because I am unaware of the rationale, discussion, community feedback around Pelican plugins as python packages.

**Comment by dclong** [comment]
Is it possible to support external search engine? It is quite simple. Basically, it leverages the `site` tag when doing search using external engine. For example, passing `site:http://www.legendu.net/misc pyspark` to `bing.com/search` searchs for pyspark on the site `www.legendu.net`.
