### ISSUE TITLE
Is it possible to enable comments in page?

### ISSUE THREAD

**Issue by calfzhou** [Pelican-Elegant/elegant#63]
My previous WordPress pages also allow user leave comments. So I'd like to add comments to pages.

**Comment by azzamsa** [comment]
> if comments_intro is defined in a post/page but it is empty then don't show comments. It is to help user disable comments on page/post on per post basis.

@talha131 I tried it, and it didn't work. I can use `comments: true` in Octopress, by the way.

I am still curious. As far I know Elegant is pelican "theme" not "framework", but why such this thing, handled by a "theme" ?. I searched "disable comment in certain page pelican", didn't find any answer in SO, and link to here.

**Comment by azzamsa** [comment]
Luckily I [have add](https://github.com/azzamsa/elegant/commit/ddd90fcfe798f588fc0f213d01957ed8dad6939a) that ability. (Add ability to enable comments per page)
