### ISSUE TITLE
[BUG] Article 'Published' and 'Last Updated' dates have different formats

### ISSUE THREAD

**Issue by ishigoya** [Pelican-Elegant/elegant#648]
## Mandatory Step

I am using latest production release of Elegant

## Description

On pages with `date` and `modified` metadata defined, the date format used for each is different.

This results in the following appearing on pages:

![rsz_1120201121_08h46m40s_grim](https://user-images.githubusercontent.com/16798645/99860936-f7c86300-2bd7-11eb-9a2e-835ea4a843a7.png)

**To Reproduce**

1. publish a page with `date` and `modified` metadata (e.g. [the sample from the Pelican docs](https://docs.getpelican.com/en/latest/content.html#file-metadata))

**Expected behavior**
The 'Published' and 'Last Updated' sections should use the same date format.

**Additional context**

~~~~
$ pelican --version   
4.5.1
$ locale | grep LC_TIME
LC_TIME="en_GB.utf8"
~~~~

**Comment by ishigoya** [comment]
It seems the 'Published' section uses `article.locale_date`, while the 'Last Updated' section uses per-element string formatting of `article.modified` (i.e. day, then month, then year).

[From the Pelican docs](https://docs.getpelican.com/en/4.5.1/themes.html#article), `locale_date` is the date as formatted by `date_format`, so I think this could be fixed by also formatting `modified` using `date_format`.

I've checked this works with a test site and would be happy to submit a pull request.

**Comment by iranzo** [comment]
Thanks @ishigoya that would be great, remember, when submitting a PR to do it against the 'next' branch.

**Comment by ishigoya** [comment]
Duplicate of #613
