### ISSUE TITLE
[BUG] Table of contents using reStructuredText has duplicated title

### ISSUE THREAD

**Issue by asierrayk** [Pelican-Elegant/elegant#689]
## Mandatory Step

- [x] I am using latest production release of Elegant

## Recommended Step

- [x] I have attached link to my blog source code repository, so that developers can try to reproduce the issue at the end
- [ ] I can't my source code but I have linked my pelican configuration files to help developers reproduce the issue

Link to my config: https://github.com/asierrayk/asierrayk.github.io/blob/source/pelicanconf.py

## Description

**Describe the bug**
Using markdown table of contents render correctly but with reStructuredText two titles for the TOC are inserted.

**To Reproduce**
```
My super title
##############

:date: 2010-10-03 10:20
:modified: 2010-10-04 18:40
:tags: thats, awesome
:category: yeah
:slug: my-super-post
:authors: Alexis Metaireau, Conan Doyle
:summary: Short version for index and feeds

.. contents::

First
-----
one

Second
------
two
```

1. Create a rst file with the code above
2. execute `make devserver`
3. go to chrome and go to the post corresponding to the file
4. Observe Table of contents at the left margin with 2 titles.

**Expected behavior**
The expected behaviour is to render the table of contents with just one title

**Screenshots**
rst example (doube title Contents and contenido)
![image](https://user-images.githubusercontent.com/12305218/120715697-43cc5c80-c4c5-11eb-8820-edfc5ce75da5.png)

markdown example
![image](https://user-images.githubusercontent.com/12305218/120715793-6a8a9300-c4c5-11eb-9065-83ae119539d9.png)

**Desktop (please complete the following information):**

- OS: Windows 10 + WSL2
- Browser: chrome

**Comment by talha131** [comment]
Have a look at this https://elegant.oncrashreboot.com/how-elegant-displays-table-of-contents#hide-default-title-text

Feel free to reopen if it does not fix your issue.

**Comment by asierrayk** [comment]
@talha131  Just one question, where should I place the `custom.css` file?

**Comment by talha131** [comment]
@ashwinvis you need to edit [this file](https://github.com/Pelican-Elegant/elegant/blob/master/static/css/custom.css) in your copy of the Elegant theme.
