### ISSUE TITLE
Allow About Me to be written in rST or Markdown

### ISSUE THREAD

**Issue by tshepang** [Pelican-Elegant/elegant#85]
Curremtly, `LANDING_PAGE_ABOUT` is used for that, which is not ideal, especially since it needs (I think) to be written in raw html. Perhaps a solution where this file is read off some file somewhere?

(encouraged by https://github.com/talha131/pelican-elegant/pull/77#issuecomment-29552207 to request a feature before 2.0 gets released)

**Comment by codecachet** [comment]
Shouldn't there be a way in Pelican to create any particular section of text (like the About Me) from markdown? What if I wanted, say, a Message of the Day to appear in the right column of each page? How would I go about putting this md content in its own file,  and have it treated as a "section", rather than a page?

**Comment by codecachet** [comment]
Figured out an easy way to do this. Put "About Me" markdown in a page, but make it `status: hidden`. Then in the index.html template (`class="article-content"`), just look in the list `hidden_pages` for the page which has the correct title, and insert the `page.content`.

**Comment by talha131** [comment]
@codecachet very cool. Love it. Let me know if you can open a PR.

**Comment by talha131** [comment]
@iranzo can you find time to implement what @codecachet has suggested?

This is in Q3 milestone, it's not as urgent as tasks in Q2 milestone.

**Comment by iranzo** [comment]
I was having a look at this yesterday night, I need to find how to loop in jinja for this and then extract the data and make the relevant code changes

**Comment by iranzo** [comment]
Talha, do you have a pointer on how to perform the loop against the filter for articles? Not familiar enough with pelican templates for writing the loop for this :-/

**Comment by talha131** [comment]
Can you try 

```jinja
{% for article in articles %}
{% if article.status == blah and article.title == "Landing Page About Me" %}
```

I think we need a specific title for the article we are going to use for about me.

**Comment by talha131** [comment]
@tshepang and @calfzhou, it took five years 😆 but the feature is finally here. Currently in beta.

https://next.elegant.oncrashreboot.com/customize-home-page

(You may have to add ssl error exception to visit the page. Netlify SSL has some issue.)

It gives me immense pleasure to close a five year old feature request.

**Comment by talha131** [comment]
@all-contributors please add @codecachet for ideas
