### ISSUE TITLE
[BUG] Main website host (elegant.oncrashreboot.com) is NXDOMAIN

### ISSUE THREAD

**Issue by neirbowj** [Pelican-Elegant/elegant#885]
## Description

**Describe the bug**

When attempting to visit the Pelican Elegant web page, the browser reports "Server Not Found".

**To Reproduce**

1. Navigate to https://elegant.oncrashreboot.com/
2. See error

**Expected behavior**

The project's website is reachable.

**Screenshots**

<img width="787" alt="Screen Shot 2022-09-09 at 18 42 53" src="https://user-images.githubusercontent.com/1879063/189455333-e20c8462-113e-421d-9519-9c1347bd6458.png">

Via Quad9 public DNS resolver:

```
$ dig @2620:fe::fe elegant.oncrashreboot.com a

; <<>> DiG 9.18.5 <<>> @2620:fe::fe elegant.oncrashreboot.com a
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 17384
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;elegant.oncrashreboot.com.	IN	A

;; AUTHORITY SECTION:
oncrashreboot.com.	3600	IN	SOA	cleo.ns.cloudflare.com. dns.cloudflare.com. 2287182796 10000 2400 604800 3600

;; Query time: 15 msec
;; SERVER: 2620:fe::fe#53(2620:fe::fe) (UDP)
;; WHEN: Fri Sep 09 18:45:40 EDT 2022
;; MSG SIZE  rcvd: 113
```
```
$ dig @2620:fe::fe elegant.oncrashreboot.com aaaa

; <<>> DiG 9.18.5 <<>> @2620:fe::fe elegant.oncrashreboot.com aaaa
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 907
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
;; QUESTION SECTION:
;elegant.oncrashreboot.com.	IN	AAAA

;; AUTHORITY SECTION:
oncrashreboot.com.	3600	IN	SOA	cleo.ns.cloudflare.com. dns.cloudflare.com. 2287182796 10000 2400 604800 3600

;; Query time: 25 msec
;; SERVER: 2620:fe::fe#53(2620:fe::fe) (UDP)
;; WHEN: Fri Sep 09 18:46:05 EDT 2022
;; MSG SIZE  rcvd: 113
```

**Desktop (please complete the following information):**

- OS: macOS Big Sur (11.6.8)
- Browser: Firefox
- Version: 104.0.2

**Comment by lcfd** [comment]
👋 Now it shows ERR_NAME_NOT_RESOLVED.

**Comment by talha131** [comment]
@lcfd and @neirbowj thanks for reporting this issue. @silverhook had pointed this issue to me via email.

I recently changed the domain registrar from NameCheap to CloudFlare which has broken the subdomain `elegant.onCrashReboot.com`.

I am trying to figure how to make the subdomain work with Netlify like it used to.

To my surprise, the root domain `onCrashReboot.com` is working fine and did not require any changes from me during the migration.

Please hang on.

**Comment by talha131** [comment]
Thank you all for you patience.
