### ISSUE TITLE
Replace Font Awesome for Fork Awesome

### ISSUE THREAD

**Issue by silverhook** [Pelican-Elegant/elegant#905]
[Fork Awesome](https://forkaweso.me/Fork-Awesome/) is a community fork and continuation of Font Awesome. It seems to include some modern icons that are missing in the other one too.

**Comment by justinmayer** [comment]
That didn't last very long… As indicated on the top of the linked site — and the [GitHub project README](https://github.com/ForkAwesome/Fork-Awesome) — Fork Awesome is defunct, so this issue can probably be closed.

**Comment by silverhook** [comment]
Too bad. I guess we can close it now and open a new one if a better solution pops up.
